### ISSUE TITLE
container fails to start when using postgres database on the host

### ISSUE THREAD

**Issue by pratio** [mealie-recipes/mealie#1089]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I am using postgres installed on the host and have created the database for mealie.
on doing docker-compose up, I face this error

```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL SYSCALL error: EOF detected

[SQL: SELECT groups.id AS groups_id, groups.name AS groups_name, groups.webhook_enable AS groups_webhook_enable, groups.webhook_time AS groups_webhook_time 
FROM groups
 LIMIT ALL OFFSET %(param_1)s]
[parameters: {'param_1': 0}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

[2022-03-23 14:31:58 +0000] [55] [ERROR] Application startup failed. Exiting.
[2022-03-23 14:31:58 +0000] [55] [INFO] Worker exiting (pid: 55)
/opt/pysetup/.venv/lib/python3.9/site-packages/apscheduler/util.py:95: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  if obj.zone == 'local':
INFO: 23-Mar-22 14:31:58 	Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO: 23-Mar-22 14:31:58 	Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO: 23-Mar-22 14:31:58 	----INIT SCHEDULE OBJECT-----
INFO: 23-Mar-22 14:31:58 	Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-03-23 14:31:58 +0000] [56] [ERROR] Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
food      | psycopg2.OperationalError: SSL SYSCALL error: EOF detected
```
37 tables have already been created

```
mealie=# \dt
                 List of relations
 Schema |           Name           | Type  | Owner  
--------+--------------------------+-------+--------
 public | api_extras               | table | mealie
 public | categories               | table | mealie
 public | custom_pages             | table | mealie
 public | custom_pages2categories  | table | mealie
 public | event_notifications      | table | mealie
 public | events                   | table | mealie
 public | group2categories         | table | mealie
 public | groups                   | table | mealie
 public | ingredient_foods         | table | mealie
 public | ingredient_units         | table | mealie
 public | ingredients_to_foods     | table | mealie
 public | ingredients_to_units     | table | mealie
 public | long_live_tokens         | table | mealie
 public | meal                     | table | mealie
 public | mealdays                 | table | mealie
 public | mealplan                 | table | mealie
 public | notes                    | table | mealie
 public | recipe_assets            | table | mealie
 public | recipe_comments          | table | mealie
 public | recipe_instructions      | table | mealie
 public | recipe_nutrition         | table | mealie
 public | recipe_settings          | table | mealie
 public | recipes                  | table | mealie
 public | recipes2categories       | table | mealie
 public | recipes2tags             | table | mealie
 public | recipes_ingredients      | table | mealie
 public | shopping_list_items      | table | mealie
 public | shopping_lists           | table | mealie
 public | sign_ups                 | table | mealie
 public | site_settings            | table | mealie
 public | site_settings2categories | table | mealie
 public | site_theme               | table | mealie
 public | tags                     | table | mealie
 public | theme_colors             | table | mealie
 public | tools                    | table | mealie
 public | users                    | table | mealie
 public | webhook_urls             | table | mealie
```

### Deployment

Docker (Linux)

### Deployment Details

```
    environment:
      DB_ENGINE: sqlite # Optional: 'sqlite', 'postgres'
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: 
      POSTGRES_SERVER: 
      POSTGRES_PORT: 
      POSTGRES_DB: mealie
      WORKERS_PER_CORE: 0.5
      MAX_WORKERS: 8
      WEB_CONCURRENCY: 2
```

That's the change made in the `docker-compose.yml`

### Mealie Version

0.5.6

**Comment by hay-kot** [comment]
There have been similar errors reported when using Postgres and the Postgres container doesn't start before Mealie, so there's a race condition and if the startup isn't successful this will happen. This is resolved in v1 with a loop timer that will re-check the connection.

You could try adding a `depends_on` configuration for the Mealie container. But i'd suggest using SQLite if you're sticking with v0.5.6 since it's better tested database option.

**Comment by pratio** [comment]
Thanks, I'll stick with sqlite. I'm not using a container, I'm using a database on the host, so it's started already and I have other applications using it already

**Comment by pratio** [comment]
```
mealie=# SELECT groups.id AS groups_id, groups.name AS groups_name, groups.webhook_enable AS groups_webhook_enable, groups.webhook_time AS groups_webhook_time 
mealie-# FROM groups;
 groups_id | groups_name | groups_webhook_enable | groups_webhook_time 
-----------+-------------+-----------------------+---------------------
         1 | Home        | f                     | 00:00
(1 row)
```

The table is there though, please let me know if i can help debug it

**Comment by tbleiker** [comment]
I successfully tested a v1.0.0b setup with postgresql on docker linux. I am not a postgres expert. But a quick google search indicates that the error `psycopg2.OperationalError: SSL SYSCALL error: EOF detected` is most probably caused by the postgres server disconnecting the client. Can find anything in the postgres server logs?
