### ISSUE TITLE
[v1.0.0b] - Failures when in a created group

### ISSUE THREAD

**Issue by tbleiker** [mealie-recipes/mealie#1100]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I created a new group and added some users. For these users I experience the following (same for the default admin user if added to this group):

- Group settings page is empty (only showing the small header image,  the title "Group Settings" and the text "These items are shared within your group. Editing one of them will change it for the whole group!").
- Recipe cannot be scraped from link, you get the red error box "Looks Like We Couldn't Find Anything" (see logs below).

<details>
<summary>Log for failed recipe scrape</summary>

```
mealie-api  | ERROR: 26-Mar-22 20:18:46         Error parsing recipe func_call for 'performTime'
mealie-api  | ERROR: 26-Mar-22 20:18:46         Error parsing recipe func_call for 'cookTime'
mealie-api  | ERROR: 26-Mar-22 20:18:46         Error parsing recipe func_call for 'image'
mealie-api  | ERROR: 26-Mar-22 20:18:46         Error parsing recipe func_call for 'description'
mealie-api  | ERROR: 26-Mar-22 20:18:46         Error parsing recipe func_call for 'nutrition'
mealie-api  | ERROR: 26-Mar-22 20:18:46         Error parsing recipe func_call for 'totalTime'
mealie-api  | ERROR: 26-Mar-22 20:18:46         Error parsing recipe func_call for 'prepTime'
mealie-api  | INFO: 26-Mar-22 20:18:46  Image ['https://cookieandkate.com/images/2014/10/no-noodle-pad-thai-recipe-4-225x225.jpg', 'https://cookieandkate.com/images/2014/10/no-noodle-pad-thai-recipe-4-260x195.jpg', 'https://cookieandkate.com/images/2014/10/no-noodle-pad-thai-recipe-4-320x180.jpg', 'https://cookieandkate.com/images/2014/10/no-noodle-pad-thai-recipe-4.jpg']
mealie-api  | INFO: 26-Mar-22 20:18:46  Image URL: ['https://cookieandkate.com/images/2014/10/no-noodle-pad-thai-recipe-4-225x225.jpg', 'https://cookieandkate.com/images/2014/10/no-noodle-pad-thai-recipe-4-260x195.jpg', 'https://cookieandkate.com/images/2014/10/no-noodle-pad-thai-recipe-4-320x180.jpg', 'https://cookieandkate.com/images/2014/10/no-noodle-pad-thai-recipe-4.jpg']
mealie-api  | INFO: 26-Mar-22 20:18:47  File Name Suffix .jpg
mealie-api  | INFO: 26-Mar-22 20:18:47  original.jpg minified
mealie-api  | INFO: 26-Mar-22 20:18:47  Tiny image saved
mealie-api  | 192.168.64.3:46194 - "POST /api/recipes/create-url HTTP/1.1" 500
mealie-api  | [2022-03-26 20:18:47 +0100] [30] [ERROR] Exception in ASGI application
mealie-api  | Traceback (most recent call last):
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
mealie-api  |     result = await app(self.scope, self.receive, self.send)
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
mealie-api  |     return await self.app(scope, receive, send)
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 259, in __call__
mealie-api  |     await super().__call__(scope, receive, send)
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
mealie-api  |     await self.middleware_stack(scope, receive, send)
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
mealie-api  |     raise exc
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
mealie-api  |     await self.app(scope, receive, _send)
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 23, in __call__
mealie-api  |     await responder(scope, receive, send)
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 42, in __call__
mealie-api  |     await self.app(scope, receive, self.send_with_gzip)
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
mealie-api  |     raise exc
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
mealie-api  |     await self.app(scope, receive, sender)
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
mealie-api  |     raise e
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
mealie-api  |     await self.app(scope, receive, send)
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 656, in __call__
mealie-api  |     await route.handle(scope, receive, send)
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 259, in handle
mealie-api  |     await self.app(scope, receive, send)
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 61, in app
mealie-api  |     response = await func(request)
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
mealie-api  |     raw_response = await run_endpoint_function(
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
mealie-api  |     return await run_in_threadpool(dependant.call, **values)
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
mealie-api  |     return await anyio.to_thread.run_sync(func, *args)
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 28, in run_sync
mealie-api  |     return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
mealie-api  |     return await future
mealie-api  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 754, in run
mealie-api  |     result = context.run(func, *args)
mealie-api  |   File "/app/mealie/routes/recipe/recipe_crud_routes.py", line 147, in parse_recipe_url
mealie-api  |     return self.service.create_one(recipe).slug
mealie-api  |   File "/app/mealie/services/recipe/recipe_service.py", line 111, in create_one
mealie-api  |     public=self.group.preferences.recipe_public,
mealie-api  | AttributeError: 'NoneType' object has no attribute 'recipe_public'
```

</details>

### Deployment

Docker (Linux)

### Deployment Details

most current frontend-nigthly (da57184c5690) and api-nightly (4ed3545a8de7) with sqlite

**Comment by hay-kot** [comment]
I'm assuming these groups were created in the Admin section? 

Looks like the permissions aren't getting created along with the group. Probably going to lead to a larger refactoring change to get all that to happen in one place, may be a bit before that gets done. 

For the time being you can use the register page to create a new group through user-signups and add users from there.

**Comment by hay-kot** [comment]
Should be fixed in the latest build - Note that any groups you created from the Admin UI prior will need to be deleted/replaced for them to work.

**Comment by tbleiker** [comment]
Exceptionally busy week ahead... but will try to give you a feedback within the next days.
