### ISSUE TITLE
LDAP authentication does not work with Active Directory

### ISSUE THREAD

**Issue by lupolio** [mealie-recipes/mealie#1320]
Mealie version used: v0.5.6 (docker)

Relevant ettings (via environment variables)

 LDAP_AUTH_ENABLED: "true"
 LDAP_SERVER_URL: "<ADserverURL>"
 LDAP_BIND_TEMPLATE: "{}@xxx.yyy.zz"
 LDAP_ADMIN_FILTER: "memberOf=CN=Domain Admins,OU=Groups,DC=xxx,DC=yyy,DC=zz"

This will set the user_dn variable in "security.py" as follows to "myuser@xxx.yyy.zz" which breaks the admin lookup since it tries to use the user_dn as search base (which in my case is obviously the users email address).
One possible solution would be to add an environment variable: "BASE_DN" that is used for the lookup.

```
10.10.10.3:0 - "POST /api/auth/token HTTP/1.1" 500
[2022-05-31 15:08:19 +0200] [44] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/mealie/routes/users/auth.py", line 28, in get_token
    user: UserInDB = authenticate_user(session, email, password)
  File "/app/mealie/core/security.py", line 77, in authenticate_user
    return user_from_ldap(session, email, password)
  File "/app/mealie/core/security.py", line 50, in user_from_ldap
    user.admin = len(conn.search_s(user_dn, ldap.SCOPE_BASE, settings.LDAP_ADMIN_FILTER, [])) > 0
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 631, in search_s
    return self.search_ext_s(base,scope,filterstr,attrlist,attrsonly,None,None,timeout=self.timeout)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 625, in search_ext_s
    return self.result(msgid,all=1,timeout=timeout)[1]
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 535, in result
    resp_type, resp_data, resp_msgid = self.result2(msgid,all,timeout)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 539, in result2
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all,timeout)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 543, in result3
    resp_type, resp_data, resp_msgid, decoded_resp_ctrls, retoid, retval = self.result4(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 553, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 128, in _ldap_call
    result = func(*args,**kwargs)
ldap.INVALID_DN_SYNTAX: {'msgtype': 101, 'msgid': 2, 'result': 34, 'desc': 'Invalid DN syntax', 'ctrls': [], 'info': "00002032: ldb_search: invalid basedn '(null)'"}
```

**Comment by hay-kot** [comment]
There are templates for both Issues and Feature Requests, and you followed neither of them. Is this a bug or a feature request? 

I don't use LDAP or have a local ENV to test adequately. As such, this would need to be a PR from the community.

**Comment by lupolio** [comment]
Created a PR to fix this -> https://github.com/hay-kot/mealie/pull/1331
