### ISSUE TITLE
[v0.5.x] - SSLCertVerificationError for recipe site that has a valid SSL cert

### ISSUE THREAD

**Issue by xionous** [mealie-recipes/mealie#1431]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

When you visit https://www.bulkbarn.ca/en/Recipes/Categories/Salads-Dressings/Italian-Pasta-Summer-Salad in a browser the cert shows valid but if I try to import a recipe from here I get this error: 

`[2022-06-19 20:48:04 -0500] [58] [ERROR] Exception in ASGI application

Traceback (most recent call last):
File "/opt/pysetup/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
result = await app(self.scope, self.receive, self.send)
File "/opt/pysetup/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
return await self.app(scope, receive, send)
File "/opt/pysetup/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
await super().__call__(scope, receive, send)
File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
await self.middleware_stack(scope, receive, send)
File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
raise exc from None
File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
await self.app(scope, receive, _send)
File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
raise exc from None
File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
await self.app(scope, receive, sender)
File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
await route.handle(scope, receive, send)
File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
await self.app(scope, receive, send)
File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
response = await func(request)
File "/opt/pysetup/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
raw_response = await run_endpoint_function(
File "/opt/pysetup/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
return await run_in_threadpool(dependant.call, **values)
File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
return await loop.run_in_executor(None, func, *args)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/app/mealie/routes/recipe/recipe_crud_routes.py", line 53, in test_parse_recipe_url
scraped_data = scrape_from_url(url.url)
File "/app/mealie/services/scraper/scraper.py", line 82, in scrape_from_url
scraped_schema = scrape_me(url, wild_mode=True)
File "/opt/pysetup/.venv/lib/python3.9/site-packages/recipe_scrapers/__init__.py", line 374, in scrape_me
wild_scraper = SchemaScraperFactory.generate(url_path, **options)
File "/opt/pysetup/.venv/lib/python3.9/site-packages/recipe_scrapers/_factory.py", line 51, in generate
return cls.SchemaScraper(url, **options)
File "/opt/pysetup/.venv/lib/python3.9/site-packages/recipe_scrapers/_abstract.py", line 33, in __init__
self.page_data = requests.get(
File "/opt/pysetup/.venv/lib/python3.9/site-packages/requests/api.py", line 75, in get
return request('get', url, params=params, **kwargs)
File "/opt/pysetup/.venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
return session.request(method=method, url=url, **kwargs)
File "/opt/pysetup/.venv/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
resp = self.send(prep, **send_kwargs)
File "/opt/pysetup/.venv/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
r = adapter.send(request, **kwargs)
File "/opt/pysetup/.venv/lib/python3.9/site-packages/requests/adapters.py", line 517, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.bulkbarn.ca', port=443): Max retries exceeded with url: /en/Recipes/Categories/Salads-Dressings/Italian-Pasta-Summer-Salad (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))`

### Deployment

Docker (Linux)

### Deployment Details

<html>
<body>

Key | Value
-- | --
APP_PORT | 80
DB_TYPE | sqlite
GPG_KEY | **
HOST_OS | Unraid
LANG | C.UTF-8
LDAP_ADMIN_FILTER | **
LDAP_AUTH_ENABLED | true
LDAP_BIND_TEMPLATE | **
LDAP_SERVER_URL | **
MEALIE_HOME | /app
PATH | /opt/poetry/bin:/opt/pysetup/.venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PIP_DEFAULT_TIMEOUT | 100
PIP_DISABLE_PIP_VERSION_CHECK | on
PIP_NO_CACHE_DIR | off
POETRY_HOME | /opt/poetry
POETRY_NO_INTERACTION | 1
POETRY_VIRTUALENVS_IN_PROJECT | true
PRODUCTION | true
PYSETUP_PATH | /opt/pysetup
PYTHON_GET_PIP_SHA256 | **
PYTHON_GET_PIP_URL | https://github.com/pypa/get-pip/raw/3cb8888cc2869620f57d5d2da64da38f516078c7/public/get-pip.py
PYTHON_PIP_VERSION | 21.2.4
PYTHON_SETUPTOOLS_VERSION | 58.1.0
PYTHON_VERSION | 3.9.10
PYTHONDONTWRITEBYTECODE | 1
PYTHONUNBUFFERED | 1
TZ | America/Chicago
VENV_PATH | /opt/pysetup/.venv

</body>
</html>

<html>
<body>

Setting | Value
-- | --
IMAGE | hkotel/mealie@sha256:c93b14ef60064d7f8a00856db96208e8dea310c0786ff4701f98b4c5117b3143
PORT CONFIGURATION | 0.0.0.0:8829  80/tcp
CMD |  
ENTRYPOINT | /bin/sh -c $MEALIE_HOME/mealie/run.sh

</body>
</html>

### Mealie Version

0.5.6

**Comment by Cobbert** [comment]
Just tired adding this recipe into my running mealie v1.0.0beta4 and it returned an error, my guess is the site you are trying to pull from doesn't have the recipe structured correctly in the site code. Mealie requires the recipe to be stored as json or microdata according to the error message.

`Only websites containing ld+json or microdata can be imported by Mealie. Most major recipe websites support this data structure. If your site cannot be imported but there is json data in the log, please submit a github issue with the URL and data. `


Here is the code storing the recipe on that site.

```
<div id="recipe_image"></div>




<h3 style="padding: 0 !important; margin: 0 !important;">Italian Pasta Summer Salad (Vegan-friendly)</h3>
<hr>

<h3>Ingredients:</h3>
<p><p>
<b>Prep Time:</b> 10 Minutes <br>
<b>Cook Time:</b> 8-10 Minutes <br>
<b>Total Time:</b> 18-20 Minutes <br>
<b>Yield:</b> 8-10 Servings <br>
</p>

<p>&nbsp;</p>

<p><b>Ingredients:</b></p>
<ul>
  <li>3 cups Nonna's Rainbow Bowtie Pasta, cooked</li>
  <li>1 Yellow Bell Pepper, chopped</li>
  <li>1 Orange Bell Pepper, chopped</li>
  <li>1 Red Bell Pepper, chopped</li>
  <li>1 English Cucumber, chopped</li>
  <li>2 cups Grape Tomatoes, halved</li>
  <li>1 tsp Ground Black Pepper</li>
  <li>2 tsp Rubbed Sweet Basil</li>
  <li>1 tbsp Oregano Rubbed</li>
  <li>1/2 cup Red Wine Vinegar</li>
  <li>1/2 cup Extra Virgin Olive Oil</li>
</ul>
</p>

<hr>

<h3>Directions:</h3>
<p><ol>
  <li>Bring 4 - 6 quarts of water to a rolling boil. Add pasta to boiling water, stir gently. Return to a boil and cook uncovered for 8-10 minutes, stirring occasionally.</li>
  <li>In the meantime, chop the bell peppers, cucumber, tomatoes, and toss them into a large salad bowl.</li>
  <li>Measure and add the seasonings, vinegar, and olive oil to the salad bowl.</li>
  <li>Drain and rinse the pasta under cold water to stop the cooking process before adding them to the chopped veggies.</li>
  <li>Gently mix and toss everything together in the bowl to combine.</li>
  <li>Let the pasta salad marinate and chill in the fridge, for at least 30 minutes before serving.</li>
  <li>Enjoy cool, at room temperature.</li>
</ol>

<p><b>Note:</b> Store salad in an airtight container in the fridge for up to 3-5 days.</p>




<p>&nbsp;</p>
```

As you can see, its setup using just simple markup lists basically, so mealie doesn't know how to process it.

In more simple terms, its just not going to work and you next best step is to find a site that will work, or manually add the recipe to the system.

**Comment by Cobbert** [comment]
Should close this as its not an issue with mealie but rather an issue with the site providing the recipe data.
