### ISSUE TITLE
Cannot import recipe from akispetretzikis.com

### ISSUE THREAD

**Issue by kokos1405** [mealie-recipes/mealie#1569]
Cannot scrap anything from web page.

Recipe address: https://akispetretzikis.com/recipe/5859

**Comment by tbornon** [comment]
It seems that they don't support the recipe schema used by Mealie. The ld+json content is incomplete

```JSON
{
  "@context": "https://schema.org/",
  "@type": "Recipe",
  "name": "Αρνίσια παϊδάκια με σάλτσα μυρωδικών",
  "image": [
    "https://akispetretzikis.com/photos/akisrecipes/16852/paidakia_me_saltsa_kapari_-_site.jpg"
  ],
  "author": {
    "@type": "Person",
    "name": "Akis Petretzikis"
  },
  "datePublished": "2021-04-19T04:56:30.000000Z",
  "description": "&Alpha;&rho;&nu;ί&sigma;&iota;&alpha; &pi;&alpha;ϊ&delta;ά&kappa;&iota;&alpha; &mu;&epsilon; &sigma;ά&lambda;&tau;&sigma;&alpha; &mu;&upsilon;&rho;&omega;&delta;&iota;&kappa;ώ&nu; &alpha;&pi;ό &tau;&omicron;&nu; Ά&kappa;&eta; &Pi;&epsilon;&tau;&rho;&epsilon;&tau;&zeta;ί&kappa;&eta;! &Sigma;&upsilon;&nu;&tau;&alpha;&gamma;ή &gamma;&iota;&alpha; &mu;&alpha;&lambda;&alpha;&kappa;ά &kappa;&alpha;&iota; &zeta;&omicron;&upsilon;&mu;&epsilon;&rho;ά &pi;&alpha;ϊ&delta;ά&kappa;&iota;&alpha; &sigma;&tau;&omicron; &mu;&pi;ά&rho;&mu;&pi;&epsilon;&kappa;&iota;&omicron;&upsilon;! &Iota;&delta;&alpha;&nu;&iota;&kappa;ά &gamma;&iota;&alpha; &tau;&omicron; &Pi;ά&sigma;&chi;&alpha;!"
}
```

**Comment by hay-kot** [comment]
@tbornon is correct, the recipe doesn't provide any Schema and the library we use doesn't have a customer scraper for this one.

**Comment by DictumMortuum** [comment]
Hello! It seems that recipe-scrapers supports this site -> https://github.com/hhursev/recipe-scrapers

However I still get an exception while parsing it, not sure if the scraper is used at all to be honest:

```
mealie  | 172.19.0.1:0 - "POST /api/recipes/create-url HTTP/1.1" 500
mealie  | [2023-01-20 01:26:15 -0900] [47] [ERROR] Exception in ASGI application
mealie  | Traceback (most recent call last):
mealie  |   File "/opt/pysetup/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
mealie  |     result = await app(self.scope, self.receive, self.send)
mealie  |   File "/opt/pysetup/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
mealie  |     return await self.app(scope, receive, send)
mealie  |   File "/opt/pysetup/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
mealie  |     await super().__call__(scope, receive, send)
mealie  |   File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
mealie  |     await self.middleware_stack(scope, receive, send)
mealie  |   File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
mealie  |     raise exc from None
mealie  |   File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
mealie  |     await self.app(scope, receive, _send)
mealie  |   File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
mealie  |     raise exc from None
mealie  |   File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
mealie  |     await self.app(scope, receive, sender)
mealie  |   File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
mealie  |     await route.handle(scope, receive, send)
mealie  |   File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
mealie  |     await self.app(scope, receive, send)
mealie  |   File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
mealie  |     response = await func(request)
mealie  |   File "/opt/pysetup/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
mealie  |     raw_response = await run_endpoint_function(
mealie  |   File "/opt/pysetup/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
mealie  |     return await run_in_threadpool(dependant.call, **values)
mealie  |   File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
mealie  |     return await loop.run_in_executor(None, func, *args)
mealie  |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
mealie  |     result = self.fn(*self.args, **self.kwargs)
mealie  |   File "/app/mealie/routes/recipe/recipe_crud_routes.py", line 68, in parse_recipe_url
mealie  |     recipe = create_from_url(url.url)
mealie  |   File "/app/mealie/services/scraper/scraper.py", line 35, in create_from_url
mealie  |     elif og_dict := extract_open_graph_values(url):
mealie  |   File "/app/mealie/services/scraper/scraper.py", line 59, in extract_open_graph_values
mealie  |     if recipe.get("name", "") == "":
```
