### ISSUE TITLE
[v1.0.0b] - All recipe URLs "http(s)://{IP or domain}/recipe/{slug}" return "Server error"

### ISSUE THREAD

**Issue by ghuser238490** [mealie-recipes/mealie#1612]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

All direct links to recipes like "http(s)://{IP or domain}/recipe/{slug}" return a "Server error":

- Log into Mealie
- Open a recipe page
- Reload/refresh the browser page or load the URL in a new browser window
- "Server error"

### Deployment

Docker (Linux)

### Deployment Details

Version
v1.0.0beta-4
Build
3d099ec7c6ee5bdfef297b2ffaca1bcabf53d330

**Comment by hay-kot** [comment]
Could you post the logs from the frontend container?

**Comment by ghuser238490** [comment]
@hay-kot, yes, of course. Those are the lines after a container restart and trying to open a random recipe URL as described above. This issue occured first in this build or in the build before. Thanks for looking into that!
 
```
INFO: 28-Aug-22 20:27:13 	Database connection established.
INFO: 28-Aug-22 20:27:13 	Context impl SQLiteImpl.
INFO: 28-Aug-22 20:27:13 	Will assume non-transactional DDL.
INFO: 28-Aug-22 20:27:13 	Migration not needed.
WARNING: 28-Aug-22 20:27:13 	"get_all" method is deprecated; use "page_all" instead
INFO: 28-Aug-22 20:27:14 	Database exists
INFO: 28-Aug-22 20:27:14 	No food found with slug: 'dairy-products-and-dairy-substitutes' skipping fix
INFO: 28-Aug-22 20:27:44 	Registering daily callback: purge_group_registration
INFO: 28-Aug-22 20:27:44 	Registering daily callback: purge_password_reset_tokens
INFO: 28-Aug-22 20:27:44 	Registering daily callback: purge_group_data_exports
INFO: 28-Aug-22 20:27:44 	Registering minutely callback: post_group_webhooks
INFO: 28-Aug-22 20:27:44 	Registering daily callback: locked_user_reset
INFO: 28-Aug-22 20:27:44 	Daily job: purge_group_registration
INFO: 28-Aug-22 20:27:44 	Daily job: purge_password_reset_tokens
INFO: 28-Aug-22 20:27:44 	Daily job: purge_group_data_exports
INFO: 28-Aug-22 20:27:44 	Hourly job: locked_user_reset
INFO: 28-Aug-22 20:27:44 	Minutely job: post_group_webhooks
INFO: 28-Aug-22 20:27:44 	-----SYSTEM STARTUP----- 

INFO: 28-Aug-22 20:27:44 	------APP SETTINGS------
INFO: 28-Aug-22 20:27:44 	{
    "PRODUCTION": true,
    "BASE_URL": "(DOMAIN)",
    "IS_DEMO": false,
    "API_PORT": 9000,
    "API_DOCS": true,
    "TOKEN_TIME": 48,
    "GIT_COMMIT_HASH": "3d099ec7c6ee5bdfef297b2ffaca1bcabf53d330",
    "ALLOW_SIGNUP": false,
    "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
    "SECURITY_USER_LOCKOUT_TIME": 24,
    "DB_ENGINE": "sqlite",
    "DB_PROVIDER": {
        "data_dir": "/app/data",
        "prefix": ""
    },
    "DEFAULT_GROUP": "Home",
    "DEFAULT_EMAIL": "changeme@email.com",
    "SMTP_HOST": "(DOMAIN)",
    "SMTP_PORT": "(PORT)",
    "SMTP_FROM_NAME": "(NAME)",
    "SMTP_FROM_EMAIL": "(MAIL)",
    "SMTP_AUTH_STRATEGY": "TLS",
    "LDAP_AUTH_ENABLED": false,
    "LDAP_SERVER_URL": null,
    "LDAP_BIND_TEMPLATE": null,
    "LDAP_ADMIN_FILTER": null,
    "TESTING": false
}

```

**Comment by hay-kot** [comment]
That's for the backend container, could you grab the ones from the frontend?

`docker logs mealie-frontend`

**Comment by ghuser238490** [comment]
I'm sorry! Here you are:
```
 {"level":"error","ts":1661713584.952351,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}
{"level":"error","ts":1661713585.9430306,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}
{"level":"error","ts":1661713586.1729388,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}
{"level":"error","ts":1661713589.884402,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}
{"level":"error","ts":1661713591.1990297,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}
{"level":"error","ts":1661713591.3778436,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}
{"level":"error","ts":1661713604.0968194,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}
{"level":"error","ts":1661713606.1471717,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}

ERROR  render function or template not defined in component: anonymous

  at Yi (node_modules/vue-server-renderer/build.prod.js:1:66938)
  at oo (node_modules/vue-server-renderer/build.prod.js:1:70811)
  at no (node_modules/vue-server-renderer/build.prod.js:1:70461)
  at to (node_modules/vue-server-renderer/build.prod.js:1:67708)
  at node_modules/vue-server-renderer/build.prod.js:1:70928
  at eo (node_modules/vue-server-renderer/build.prod.js:1:67418)
  at oo (node_modules/vue-server-renderer/build.prod.js:1:70830)
  at no (node_modules/vue-server-renderer/build.prod.js:1:70461)
  at to (node_modules/vue-server-renderer/build.prod.js:1:67708)
  at node_modules/vue-server-renderer/build.prod.js:1:70928
```

**Comment by hay-kot** [comment]
Should be fixed in the next build, thanks for reporting! 🎉

**Comment by ghuser238490** [comment]
You're most welcome!
