### ISSUE TITLE
[v1.0.0b] - Recipe import error when importing from URL Cheesecakefactory 

### ISSUE THREAD

**Issue by saykalik** [mealie-recipes/mealie#1723]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When trying to import from URL [https://www.thecheesecakefactory.com/recipes/coconut-macaroon-cheesecake-cups](https://www.thecheesecakefactory.com/recipes/coconut-macaroon-cheesecake-cups ) api backend give the following error in the log files:

 During handling of the above exception, another exception occurred:
2022-10-13T13:41:13.405680939Z 
2022-10-13T13:41:13.405687837Z Traceback (most recent call last):
2022-10-13T13:41:13.405694892Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
2022-10-13T13:41:13.405702221Z     resp = conn.urlopen(
2022-10-13T13:41:13.405709090Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
2022-10-13T13:41:13.405716064Z     retries = retries.increment(
2022-10-13T13:41:13.405723237Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
2022-10-13T13:41:13.405730368Z     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2022-10-13T13:41:13.405738193Z urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.thecheesecakefactory.com', port=80): Max retries exceeded with url: /recipes/coconut-macaroon-cheesecake-cups (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f478471d360>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2022-10-13T13:41:13.405746382Z 

### Deployment

Docker (Linux)

**Comment by saykalik** [comment]
This was not an issue with Mealie but with my docker setup.  Sorry
