### ISSUE TITLE
[v1.0.0b] - Restore - Incorrect Database Schema

### ISSUE THREAD

**Issue by chopst1x** [mealie-recipes/mealie#1844]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I'm trying to do a restore from beta3 to beta5 but it comes back with database backup schema does not match current database  and fails. Any idea how to resolve this please?

INFO:     172.21.0.2:58472 - "POST /api/admin/backups/upload HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
ERROR: 21-Nov-22 21:28:14 	Exception in ASGI application
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 249, in app
    content = await serialize_response(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 138, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for SuccessResponse
response
  none is not an allowed value (type=type_error.none.not_allowed)
    await self.app(scope, receive, _send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 249, in app
    content = await serialize_response(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 138, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for SuccessResponse
response
  none is not an allowed value (type=type_error.none.not_allowed)
INFO:     172.21.0.2:58480 - "GET /api/admin/backups HTTP/1.1" 200 OK
INFO: 21-Nov-22 21:28:18 	initially backup restore
/app/./mealie/services/backups_v2/alchemy_exporter.py:106: SAWarning: Cannot correctly sort tables; there are unresolvable cycles between tables "recipes, users", which is usually caused by mutually dependent foreign key constraints.  Foreign key constraints involving these tables will not be considered; this warning may raise an error in a future release.
  table.name: [dict(row) for row in self.engine.execute(table.select())] for table in self.meta.sorted_tables
ERROR: 21-Nov-22 21:28:19 	Invalid backup file. Database schemas do not match
INFO:     172.21.0.2:57726 - "POST /api/admin/backups/mealie_2022.11.21.19.29.19.zip/restore HTTP/1.1" 400 Bad Request
INFO:     127.0.0.1:53888 - "GET /api/app/about HTTP/1.1" 200 OK

### Deployment

Docker (Linux)

### Deployment Details

 mealie-frontend:
   image: hkotel/mealie:frontend-v1.0.0beta-5
   container_name: mealie-frontend
   restart: always
   ports:
     - 9925:3000
   environment:
     - API_URL=http://mealie-api:9000
   volumes:
     - /home/mealie:/app/data/
 mealie-api:
   image: hkotel/mealie:api-v1.0.0beta-5
   container_name: mealie-api
   volumes:
     - /home/mealie:/app/data/
   environment:
     - ALLOW_SIGNUP=true
     - TZ=Europe/London
   restart: always

**Comment by chopst1x** [comment]
Can anybody help here please or give some tips on what could be wrong?

Thanks,

**Comment by michael-genson** [comment]
I've never tried restoring from a backup across versions, have you tried downgrading to beta 3, restoring, then upgrading to beta 5?

**Comment by hay-kot** [comment]
@michael-genson is correct. Cross version restores is no longer supported. You need to downgrade to beta3, restore your backup, then pull the latest container and let it run the migrations
