### ISSUE TITLE
[v1.0.0b] - 'utf-8' codec can't decode byte 0xb3 in position 44

### ISSUE THREAD

**Issue by MG-Sky** [mealie-recipes/mealie#2088]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

when i try to scrape the site following error is shown:
(site https://www mniammniam.com/burgery-buraczane-nie-tylko-dla-wegan-wg-jadlonomii)
"internal server error" in logs i see:

```
`RROR: 02-Feb-23 22:54:05 	Failed to extract microdata, raises 'utf-8' codec can't decode byte 0xb3 in position 44: invalid start byte

Traceback (most recent call last):

  File "/opt/pysetup/.venv/lib/python3.9/site-packages/recipe_scrapers/__init__.py", line 368, in scrape_me

    scraper = SCRAPERS[host_name]

KeyError: 'mniammniam.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/mealie/services/scraper/scraper.py", line 79, in scrape_from_url

    scraped_schema = scrape_me(url)

  File "/opt/pysetup/.venv/lib/python3.9/site-packages/recipe_scrapers/__init__.py", line 371, in scrape_me

    raise WebsiteNotImplementedError(host_name)

recipe_scrapers._exceptions.WebsiteNotImplementedError: recipe-scrapers exception: Website (mniammniam.com) not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/opt/pysetup/.venv/lib/python3.9/site-packages/recipe_scrapers/__init__.py", line 368, in scrape_me

    scraper = SCRAPERS[host_name]

KeyError: 'mniammniam.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/opt/pysetup/.venv/lib/python3.9/site-packages/extruct/_extruct.py", line 108, in extract

    output[syntax] = list(extract(document, base_url=base_url))

  File "/opt/pysetup/.venv/lib/python3.9/site-packages/extruct/w3cmicrodata.py", line 68, in extract_items
```

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
It looks like the URL you posted is missing the dot after `www`. With the complete URL I was able to scrape it just fine:
https://www.mniammniam.com/burgery-buraczane-nie-tylko-dla-wegan-wg-jadlonomii

![image](https://user-images.githubusercontent.com/71845777/219434028-9a5dd02d-5e9a-424a-941d-0d977e35896c.png)

The image doesn't scrape properly but that seems unrelated to Mealie based on the logs.
