### ISSUE TITLE
[v1.0.0b] - Scraping recipe from chefkoch fails despite valid JSON

### ISSUE THREAD

**Issue by DocKDE** [mealie-recipes/mealie#2269]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I tried to add a new recipe from here: https://www.chefkoch.de/rezepte/1153081221555008/Der-perfekte-Milchreis-Grundrezept.html

I get an error but when I view the scraped data they seem to be in order (see below). I saw in other issues that there were problems with this site before that have been fixed but I have tried several recipes from there and the import fails every time for some reason.

```
{
  "@context": "http://schema.org",
  "@type": "Recipe",
  "image": "https://img.chefkoch-cdn.de/rezepte/1153081221555008/bilder/967314/crop-960x540/der-perfekte-milchreis-grundrezept.jpg",
  "recipeCategory": "Vegetarisch",
  "suitableForDiet": "Vegetarisch",
  "recipeIngredient": [
    "1 Liter Vollmilch , zimmerwarm",
    "250 g Milchreis",
    "4 EL Zucker",
    "1 EL Butter",
    "1  Vanilleschote(n) oder 1 Pck.Vanillezucker",
    "n. B. Zimtzucker oder Apfelmus, Rote Grütze bzw. frische Früchte"
  ],
  "name": "Der perfekte Milchreis - Grundrezept",
  "description": "Der perfekte Milchreis - Grundrezept - Keine Milchsuppe, kein verbrannter Reisklumpen - versprochen! Über 1564 Bewertungen und für vorzüglich befunden. Mit ► Portionsrechner ► Kochbuch ► Video-Tipps!",
  "recipeInstructions": "In einem großen(!) Topf die Butter schmelzen, anschließend den Rundkornreis kurz in der Butter anschwitzen. Nun die zimmerwarme Vollmilch sowie 4 EL Zucker hinzugeben. Wenn vorhanden, das Mark einer Vanilleschote sowie die aufgeschlitzte Schote ebenfalls in den Topf geben; andernfalls Vanillezucker hinzufügen. Alles unter vorsichtigem Rühren mit dem Holzkochlöffel einmal aufkochen lassen und dabei aufpassen, dass sich nichts am Topfboden ansetzt. \n\nNun die Temperatur der Herdplatte zurückschalten - die Milch sollte noch leicht weiterköcheln. Den Milchreis im geschlossenen Topf circa 30 Minuten ziehen lassen. Nach ca.15 Minuten evtl. auch früher umrühren. \n\nNach 30 Minuten ist der Reis servierfertig, er kann warm und kalt gegessen werden. \n\nNach Geschmack Zimt und Zucker mischen und über den Milchreis geben oder Apfelmus, Rote Grütze, frisches Obst, etc. dazu reichen.\n\nPro Portion 385 Kcal",
  "author": {
    "@type": "Person",
    "name": "Lea27784"
  },
  "publisher": {
    "@type": "Organization",
    "name": "Chefkoch.de"
  },
  "datePublished": "2008-09-16",
  "prepTime": "P0DT0H10M",
  "cookTime": "P0DT0H35M",
  "totalTime": "P0DT0H45M",
  "recipeYield": "4 Portion(en)",
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingCount": 1564,
    "ratingValue": 4.68,
    "reviewCount": 959,
    "worstRating": 0,
    "bestRating": 5
  },
  "video": [
    {
      "@type": "VideoObject",
      "name": "Video zu Der perfekte Milchreis - Grundrezept",
      "description": "Video zu Der perfekte Milchreis - Grundrezept",
      "thumbnailUrl": "https://static.chefkoch-cdn.de/images/crop-960x540/ck.de/videos/thumbs/1674-org.jpg",
      "contentUrl": "https://www.chefkoch.de/rezepte/1153081221555008/Der-perfekte-Milchreis-Grundrezept.html",
      "embedUrl": "https://video.chefkoch-cdn.de/ck.de/videos/1674-video.mp4",
      "uploadDate": "2008-09-16"
    }
  ],
  "nutrition": {
    "@type": "NutritionInformation",
    "servingSize": "1",
    "calories": "385 kcal",
    "proteinContent": "11,99g",
    "fatContent": "16,79g",
    "carbohydrateContent": "45,88g"
  },
  "keywords": [
    "Hauptspeise",
    "Vegetarisch",
    "Reis",
    "einfach",
    "Süßspeise",
    "Kinder",
    "gekocht",
    "Camping",
    "Studentenküche",
    "Getreide"
  ],
  "reviews": [
    {
      "@type": "Review",
      "reviewBody": "Einfach toll! Meine Familie hat richtig geschlemmt! Habe das Rezept gleich abgespeichert!",
      "datePublished": "2023-03-19",
      "author": {
        "@type": "Person",
        "name": "Julelena1988"
      }
    },
    {
      "@type": "Review",
      "reviewBody": "Unser absoluter Lieblings-Milchreis. Ich gebe noch eine geriebene Tonkabohne und 150ml Sahne hinzu. Sehr cremig und lecker. Auch am nächsten Tag. ",
      "datePublished": "2023-03-18",
      "author": {
        "@type": "Person",
        "name": "tovanda0309"
      }
    },
    {
      "@type": "Review",
      "reviewBody": "Perfekt! Werde ich beibehalten. Danke!",
      "datePublished": "2023-03-16",
      "author": {
        "@type": "Person",
        "name": "Ralf-Schulz"
      }
    },
    {
      "@type": "Review",
      "reviewBody": "Na. Das ist doch mal was feines. Super Rezept, danke",
      "datePublished": "2023-03-09",
      "author": {
        "@type": "Person",
        "name": "peter2663"
      }
    },
    {
      "@type": "Review",
      "reviewBody": "Schade dass ich nur 5 Sterne 🌟 vergeben kann! Das Rezept ist absolut gelingsicher und mega lecker! Sogar mein kleiner Sohn hat eine große Portion verputzt. Rezept ist gespeichert und Milchreis wird ab sofort nur noch nach diesem Rezept gemacht. ",
      "datePublished": "2023-03-09",
      "author": {
        "@type": "Person",
        "name": "AndreaCook83"
      }
    }
  ]
}
```

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
What do the logs say?

**Comment by DocKDE** [comment]
```
ERROR: 21-Mar-23 17:59:45 	Error parsing recipe func_call for 'performTime'
ERROR: 21-Mar-23 17:59:45 	Error parsing recipe func_call for 'cookTime'
<class 'str'>
Chocolate - Lava - Muffins
ERROR: 21-Mar-23 17:59:45 	Error parsing recipe func_call for 'image'
ERROR: 21-Mar-23 17:59:45 	Error parsing recipe func_call for 'description'
<class 'str'>
Chocolate - Lava - Muffins - Schokoladenmuffins mit saftig schokoladigem Kern. Über 568 Bewertungen und für super befunden. Mit ► Portionsrechner ► Kochbuch ► Video-Tipps!
ERROR: 21-Mar-23 17:59:45 	Error parsing recipe func_call for 'nutrition'
<class 'str'>
12 serving(s)
<class 'str'>
225 g Schokolade , zartbitter, am besten 60%-ige
<class 'str'>
115 g Butter , weich
<class 'str'>
1 TL Vanillezucker
<class 'str'>
100 g Zucker
<class 'str'>
35 g Mehl
<class 'str'>
1 Prise(n) Salz
<class 'str'>
4 Ei(er)
<class 'str'>
Butter für die Form
<class 'str'>
2 EL Kakaopulver , ungesüßt
INFO: 21-Mar-23 17:59:45 	Scraped Instructions: (Type: <class 'str'>) 
 Schokolade und Butter über dem Wasserbad schmelzen. In der Zwischenzeit Vanillezucker, Zucker, Salz und Mehl mischen. Ein Ei nach dem anderen unter die trockenen Zutaten rühren, bis ein glatter Teig entsteht. Die leicht abgekühlte, flüssige Schokolade hinzugeben, unterrühren und mit einem Rührgerät auf der höchsten Stufe ca. 4 Minuten lang dick und cremig schlagen. 

Die Mulden eines Muffinblechs gut einfetten und mit Kakaopulver ausstreuen, am besten geht das mit einem kleinen Sieb.

Die Muffinmulden zu ca. 2/3 mit dem Teig befüllen und bei 190°C Ober-/ Unterhitze 10-11 Minuten backen. Außen soll der Muffin kuchenartig sein, innen jedoch noch flüssig bis sehr weich und saftig. Die Muffins im Muffinblech ein wenig auskühlen lassen, dann vorsichtig lösen. Am besten schmecken sie, solange sie noch warm sind. Kalt schmecken sie immer noch sehr gut, der Kern ist dann jedoch nicht mehr ganz so flüssig. 

Die Menge ergibt ca. 12 Stück, eignet sich toll als Dessert, z.B. mit Puderzucker oder Kakaopulver bestäubt. Dazu serviere ich gern Schlagsahne oder Vanilleeis und frische Früchte.
<class 'str'>
Schokolade und Butter über dem Wasserbad schmelzen. In der Zwischenzeit Vanillezucker, Zucker, Salz und Mehl mischen. Ein Ei nach dem anderen unter die trockenen Zutaten rühren, bis ein glatter Teig entsteht. Die leicht abgekühlte, flüssige Schokolade hinzugeben, unterrühren und mit einem Rührgerät auf der höchsten Stufe ca. 4 Minuten lang dick und cremig schlagen.
<class 'str'>
Schokolade und Butter über dem Wasserbad schmelzen. In der Zwischenzeit Vanillezucker, Zucker, Salz und Mehl mischen. Ein Ei nach dem anderen unter die trockenen Zutaten rühren, bis ein glatter Teig entsteht. Die leicht abgekühlte, flüssige Schokolade hinzugeben, unterrühren und mit einem Rührgerät auf der höchsten Stufe ca. 4 Minuten lang dick und cremig schlagen.
<class 'str'>
Die Mulden eines Muffinblechs gut einfetten und mit Kakaopulver ausstreuen, am besten geht das mit einem kleinen Sieb.
<class 'str'>
Die Mulden eines Muffinblechs gut einfetten und mit Kakaopulver ausstreuen, am besten geht das mit einem kleinen Sieb.
<class 'str'>
Die Muffinmulden zu ca. 2/3 mit dem Teig befüllen und bei 190°C Ober-/ Unterhitze 10-11 Minuten backen. Außen soll der Muffin kuchenartig sein, innen jedoch noch flüssig bis sehr weich und saftig. Die Muffins im Muffinblech ein wenig auskühlen lassen, dann vorsichtig lösen. Am besten schmecken sie, solange sie noch warm sind. Kalt schmecken sie immer noch sehr gut, der Kern ist dann jedoch nicht mehr ganz so flüssig.
<class 'str'>
Die Muffinmulden zu ca. 2/3 mit dem Teig befüllen und bei 190°C Ober-/ Unterhitze 10-11 Minuten backen. Außen soll der Muffin kuchenartig sein, innen jedoch noch flüssig bis sehr weich und saftig. Die Muffins im Muffinblech ein wenig auskühlen lassen, dann vorsichtig lösen. Am besten schmecken sie, solange sie noch warm sind. Kalt schmecken sie immer noch sehr gut, der Kern ist dann jedoch nicht mehr ganz so flüssig.
<class 'str'>
Die Menge ergibt ca. 12 Stück, eignet sich toll als Dessert, z.B. mit Puderzucker oder Kakaopulver bestäubt. Dazu serviere ich gern Schlagsahne oder Vanilleeis und frische Früchte.
<class 'str'>
Die Menge ergibt ca. 12 Stück, eignet sich toll als Dessert, z.B. mit Puderzucker oder Kakaopulver bestäubt. Dazu serviere ich gern Schlagsahne oder Vanilleeis und frische Früchte.
INFO: 21-Mar-23 17:59:45 	Cleaned Instructions: (Type: <class 'list'>) 
 [{'text': 'Schokolade und Butter über dem Wasserbad schmelzen. In der Zwischenzeit Vanillezucker, Zucker, Salz und Mehl mischen. Ein Ei nach dem anderen unter die trockenen Zutaten rühren, bis ein glatter Teig entsteht. Die leicht abgekühlte, flüssige Schokolade hinzugeben, unterrühren und mit einem Rührgerät auf der höchsten Stufe ca. 4 Minuten lang dick und cremig schlagen.'}, {'text': 'Die Mulden eines Muffinblechs gut einfetten und mit Kakaopulver ausstreuen, am besten geht das mit einem kleinen Sieb.'}, {'text': 'Die Muffinmulden zu ca. 2/3 mit dem Teig befüllen und bei 190°C Ober-/ Unterhitze 10-11 Minuten backen. Außen soll der Muffin kuchenartig sein, innen jedoch noch flüssig bis sehr weich und saftig. Die Muffins im Muffinblech ein wenig auskühlen lassen, dann vorsichtig lösen. Am besten schmecken sie, solange sie noch warm sind. Kalt schmecken sie immer noch sehr gut, der Kern ist dann jedoch nicht mehr ganz so flüssig.'}, {'text': 'Die Menge ergibt ca. 12 Stück, eignet sich toll als Dessert, z.B. mit Puderzucker oder Kakaopulver bestäubt. Dazu serviere ich gern Schlagsahne oder Vanilleeis und frische Früchte.'}]
ERROR: 21-Mar-23 17:59:45 	Error parsing recipe func_call for 'totalTime'
ERROR: 21-Mar-23 17:59:45 	Error parsing recipe func_call for 'prepTime'
INFO: 21-Mar-23 17:59:45 	Image https://img.chefkoch-cdn.de/rezepte/1736511282639410/bilder/812098/crop-960x540/chocolate-lava-muffins.jpg
INFO: 21-Mar-23 17:59:45 	Image URL: https://img.chefkoch-cdn.de/rezepte/1736511282639410/bilder/812098/crop-960x540/chocolate-lava-muffins.jpg
INFO: 21-Mar-23 17:59:45 	File Name Suffix .jpg
/app/data/recipes/chocolate-lava-muffins/images/original.jpg
INFO: 21-Mar-23 17:59:46 	original.jpg Minified: 143.02 kB -> 37.14 kB -> 17.95 kB
172.19.0.1:0 - "POST /api/recipes/create-url HTTP/1.1" 500
[2023-03-21 17:59:46 +0100] [58] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/mealie/routes/recipe/recipe_crud_routes.py", line 69, in parse_recipe_url
    recipe: Recipe = db.recipes.create(session, recipe.dict())
  File "/app/mealie/db/db_base.py", line 130, in create
    session.commit()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1431, in commit
    self._transaction.commit(_to_root=self.future)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3363, in flush
    self._flush(objects)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush
    flush_context.execute()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 244, in save_obj
    _emit_insert_statements(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1221, in _emit_insert_statements
    result = connection._execute_20(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: recipes.slug
[SQL: INSERT INTO recipes (name, description, image, total_time, prep_time, perform_time, cook_time, recipe_yield, "recipeCuisine", slug, rating, org_url, date_added, date_updated, favorited_by_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('Chocolate - Lava - Muffins', 'Chocolate - Lava - Muffins - Schokoladenmuffins mit saftig schokoladigem Kern. Über 568 Bewertungen und für super befunden. Mit ► Portionsrechner ► Kochbuch ► Video-Tipps!', 'chocolate-lava-muffins', '30 Minutes', '20 Minutes', '10 Minutes', None, '12 serving(s)', None, 'chocolate-lava-muffins', None, 'https://www.chefkoch.de/rezepte/1736511282639410/Chocolate-Lava-Muffins.html', '2023-03-21', '2023-03-21 17:59:46.481289', None)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
172.19.0.1:0 - "GET /api/recipes/summary HTTP/1.1" 200
```

**Comment by fleshgolem** [comment]
I was quite surprised by this, because I use chefkoch for testing purposes all the time and never had a problem with it. I also tried the linked recipe and it works totally fine
That log you posted does not seem to point a general issue with the scraper, but rather the fact that a recipe with the generated slug already exists in your database. This still works for me when i do it twice, the second one just gets the slug "der-perfekte-milchreis-grundrezept-1".
I am not quite sure if this duplicate checking was always part of the app or just added later on. Which version are you running? Can you check if that recipe already might exist for you and if yes, just try to delete it and import again?

**Comment by michael-genson** [comment]
The logs show Python 3.9 so I'm guessing this is a rather old build. I don't know when we switched to 3.10 but it was a while ago
Edit: Jan 9th 2022, which I believe is still 0.5.5: https://github.com/hay-kot/mealie/pull/918

**Comment by fleshgolem** [comment]
Well that PR already links against v1, so i assume this is a 0.5.6 installation?
But yeah, there really is very little chance that this is going to be fixed there, because right now all efforts are put into the v1 release where this does seem to work perfectly fine.
So if you need this to work, i would higly suggest switching to the v1 beta (or nightlies if you are adventurous) and migrate all your data (https://nightly.mealie.io/documentation/getting-started/migrating-to-mealie-v1/)

**Comment by DocKDE** [comment]
This is indeed somewhat confusing. On one hand, you're indeed right, I did not realize that some of the recipes I was trying to scrape already existed in the database. On the other hand I ran into the same issue with another recipe from chefkoch which does not exist in the database.

I am using hkotel/mealie:latest container but as that appears to be outdated I will try again with explicit tags.

**Comment by michael-genson** [comment]
FYI: https://nightly.mealie.io/documentation/getting-started/migrating-to-mealie-v1/

**Comment by DocKDE** [comment]
Thanks for the link. I think I was following outdated documentation (not exactly sure how that happened) and ended up with an outdated version of the application. I tried with the current v1 beta release and didn't run into the same issue. Thanks for reacting so promptly!
