### ISSUE TITLE
Error scraping image on ah.be

### ISSUE THREAD

**Issue by daften** [mealie-recipes/mealie#2328]
E.g. for https://www.ah.be/allerhande/recept/R-R1188954/courgette-carbonara the image isn't scraped. This worked on the 0.5 versions, but not on 1.x. It's a fresh install.

The logs show this:
```
04/05/2023 12:26:04 AM
INFO: 05-Apr-23 00:26:04 	Image URL: ['', 'https://static.ah.nl/static/recepten/img_RAM_PRD122151_1224x900_JPG.jpg']
04/05/2023 12:26:05 AM
ERROR: 05-Apr-23 00:26:04 	Error Scraping Image: Request URL is missing an 'http://' or 'https://' protocol.
04/05/2023 12:26:05 AM
Traceback (most recent call last):
04/05/2023 12:26:05 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
04/05/2023 12:26:05 AM
    yield
04/05/2023 12:26:05 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
04/05/2023 12:26:05 AM
    resp = await self._pool.handle_async_request(req)
04/05/2023 12:26:05 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 208, in handle_async_request
04/05/2023 12:26:05 AM
    raise UnsupportedProtocol(
04/05/2023 12:26:05 AM
httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
04/05/2023 12:26:05 AM
04/05/2023 12:26:05 AM
The above exception was the direct cause of the following exception:
04/05/2023 12:26:05 AM
04/05/2023 12:26:05 AM
Traceback (most recent call last):
04/05/2023 12:26:05 AM
  File "/app/mealie/services/scraper/scraper.py", line 45, in create_from_url
04/05/2023 12:26:05 AM
    await recipe_data_service.scrape_image(new_recipe.image)
04/05/2023 12:26:05 AM
  File "/app/mealie/services/recipe/recipe_data_service.py", line 125, in scrape_image
04/05/2023 12:26:05 AM
    image_url, _ = await largest_content_len(image_url)
04/05/2023 12:26:05 AM
  File "/app/mealie/services/recipe/recipe_data_service.py", line 34, in largest_content_len
04/05/2023 12:26:05 AM
    responses: list[Response] = await gather_with_concurrency(10, *tasks)
04/05/2023 12:26:05 AM
  File "/app/mealie/services/recipe/recipe_data_service.py", line 22, in gather_with_concurrency
04/05/2023 12:26:05 AM
    return await asyncio.gather(*(sem_coro(c) for c in coros))
04/05/2023 12:26:05 AM
  File "/app/mealie/services/recipe/recipe_data_service.py", line 20, in sem_coro
04/05/2023 12:26:05 AM
    return await coro
04/05/2023 12:26:05 AM
  File "/app/mealie/services/recipe/recipe_data_service.py", line 30, in do
04/05/2023 12:26:05 AM
    return await client.head(url, headers={"User-Agent": _FIREFOX_UA})
04/05/2023 12:26:05 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1815, in head
04/05/2023 12:26:05 AM
    return await self.request(
04/05/2023 12:26:05 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1533, in request
04/05/2023 12:26:05 AM
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
04/05/2023 12:26:05 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1620, in send
04/05/2023 12:26:05 AM
    response = await self._send_handling_auth(
04/05/2023 12:26:05 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
04/05/2023 12:26:05 AM
    response = await self._send_handling_redirects(
04/05/2023 12:26:05 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
04/05/2023 12:26:05 AM
    response = await self._send_single_request(request)
04/05/2023 12:26:05 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1722, in _send_single_request
04/05/2023 12:26:05 AM
    response = await transport.handle_async_request(request)
04/05/2023 12:26:05 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
04/05/2023 12:26:05 AM
    with map_httpcore_exceptions():
04/05/2023 12:26:05 AM
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
04/05/2023 12:26:05 AM
    self.gen.throw(typ, value, traceback)
04/05/2023 12:26:05 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
04/05/2023 12:26:05 AM
    raise mapped_exc(message) from exc
04/05/2023 12:26:05 AM
httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
```

**Comment by hay-kot** [comment]
Need to add filtering out zero values in list here:

https://github.com/hay-kot/mealie/blob/mealie-next/mealie/services/scraper/cleaner.py#L82-L111

**Comment by hay-kot** [comment]
Thanks for providing the logs, very easy to find the issue! 

In the future, please use the bug template. 

https://github.com/hay-kot/mealie/issues/new?assignees=&labels=&template=v1-bug-report.yaml&title=%5Bv1.0.0b%5D+-+YOUR+TITLE

In the future, we will be auto-closing issues that don't use the appropriate template if applicable.

**Comment by daften** [comment]
I'm sorry, I missed that somehow, I'll pay attention in the future. Thanks for the quick reply too, looking forward to the fix :)
