### ISSUE TITLE
[v1.0.0b] - Cannot add recipe to list if quantity of ingredient is empty

### ISSUE THREAD

**Issue by Chronophylos** [mealie-recipes/mealie#2390]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Adding a recipe to a list where the quantity field of an ingredient is empty fails.

#### Reproduction Steps

1. Create a recipe
2. Add an ingredient but leave quantity empty, not 0
    - Unit, Ingredient name and Note does not matter
 3. Save the recipe
 4. Click on the 3 dots menu
 5. Click on add to list
 6. Click on a list
 7. nothing will happen
 
The frontend will not display an error. If you open the developer tools you can see the server returned a 500.

<details>
<summary>API Server Log</summary>

```
ERROR: 13-May-23 13:50:53 	Exception in ASGI application
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/app/./mealie/routes/groups/controller_shopping_lists.py", line 227, in add_recipe_ingredients_to_list
    ) = self.service.add_recipe_ingredients_to_list(item_id, recipe_id)
  File "/app/./mealie/services/group_services/shopping_lists.py", line 148, in add_recipe_ingredients_to_list
    ShoppingListItemCreate(
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ShoppingListItemCreate
quantity
  none is not an allowed value (type=type_error.none.not_allowed)
```
</details>

#### Workaround

Set the ingredient amount to 0

#### Suggestion

Set the amount to 0 when saving a recipe.

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
What version of Mealie are you running?

**Comment by Chronophylos** [comment]
**Details**
Version: v1.0.0beta-5
Build: ee121a12f8db33ecb4db5f8582f7ea9788d019e4
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.20.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: Yes
Docker Volumes: success

**Comment by michael-genson** [comment]
This was partially fixed in beta 5, but fully fixed in nightly: https://github.com/hay-kot/mealie/pull/2021
There are a _ton_ of shopping list improvements in nightly, so if you're a heavy shopping list user, I recommend switching

**Comment by Chronophylos** [comment]
I'll try the nightly, thank you
