### ISSUE TITLE
locked database

### ISSUE THREAD

**Issue by nick-dawson** [mealie-recipes/mealie#2409]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

I'm running mealie from docker-compose on an ubuntu server where the the volume is linked to a NAS. I've used Mealie for months without problem, but now the container won't start due to a locked sqlite database. The app just quit working after I restarted my server and the container restarted. This is a similar issue as #1496, but I'm not using azure.

Production
usermod: no changes

    User uid:    1000
    User gid:    1000
    
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/mealie/db/init_db.py", line 5, in <module>
    from mealie.db.db_setup import create_session
  File "/app/mealie/db/db_setup.py", line 5, in <module>
    SessionLocal = sql_global_init(settings.DB_URL)
  File "/app/mealie/db/models/db_session.py", line 17, in sql_global_init
    SqlAlchemyBase.metadata.create_all(engine)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 4785, in create_all
    bind._run_ddl_visitor(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3117, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2113, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 849, in visit_metadata
    self.traverse_single(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 893, in visit_table
    self.connection.execute(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1289, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1381, in _execute_ddl
    ret = self._execute_context(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: 
CREATE TABLE event_notifications (
        id INTEGER NOT NULL, 
        name VARCHAR, 
        type VARCHAR, 
        notification_url VARCHAR, 
        general BOOLEAN, 
        recipe BOOLEAN, 
        backup BOOLEAN, 
        scheduled BOOLEAN, 
        migration BOOLEAN, 
        "group" BOOLEAN, 
        user BOOLEAN, 
        PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

### Deployment

Docker (Linux)

### Deployment Details

services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: unless-stopped
    ports:
      - 9925:80
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Denver

      # Default Recipe Settings
      RECIPE_PUBLIC: 'true'
      RECIPE_SHOW_NUTRITION: 'true'
      RECIPE_SHOW_ASSETS: 'true'
      RECIPE_LANDSCAPE_VIEW: 'true'
      RECIPE_DISABLE_COMMENTS: 'false'
      RECIPE_DISABLE_AMOUNT: 'false'
    volumes:
      - /nasPath/mealie/data/:/app/data

### Mealie Version

latest

**Comment by mgrimace** [comment]
Ok, I appear to have the same issue `sqlite3.OperationalError: database is locked` when using the **omni-nightly** build and mapping volumes to a mounted NAS location:
```
    volumes:
      - /mnt/media/media/recipes:/app/data
```
My container starts and I can access the webui, but as a new user I can't log in using the default credentials.

**Comment by TheRealVira** [comment]
Same issue here with `hkotel/mealie:v0.5.6`:

```
Production
usermod: no changes
    User uid:    1000
    User gid:    1000

Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1381, in _execute_ddl
    ret = self._execute_context(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: 
CREATE TABLE event_notifications (
	id INTEGER NOT NULL, 
	name VARCHAR, 
	type VARCHAR, 
	notification_url VARCHAR, 
	general BOOLEAN, 
	recipe BOOLEAN, 
	backup BOOLEAN, 
	scheduled BOOLEAN, 
	migration BOOLEAN, 
	"group" BOOLEAN, 
	user BOOLEAN, 
	PRIMARY KEY (id)
)
]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by TheRealVira** [comment]
Different error on `omni-nightly`:

```
INFO: 02-Jul-23 13:56:49 	Database connection established.
INFO: 02-Jul-23 13:56:49 	Context impl SQLiteImpl.
INFO: 02-Jul-23 13:56:49 	Will assume non-transactional DDL.
INFO: 02-Jul-23 13:56:49 	Migration needed. Performing migration...
INFO: 02-Jul-23 13:56:49 	Context impl SQLiteImpl.
INFO: 02-Jul-23 13:56:49 	Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/mealie/db/init_db.py", line 110, in <module>
    main()
  File "/app/mealie/db/init_db.py", line 93, in main
    command.upgrade(alembic_cfg, "head")
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 576, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/alembic/env.py", line 77, in <module>
    run_migrations_online()
  File "/app/alembic/env.py", line 71, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/runtime/environment.py", line 868, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/runtime/migration.py", line 604, in run_migrations
    self._ensure_version_table()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/runtime/migration.py", line 542, in _ensure_version_table
    self._version.create(self.connection, checkfirst=True)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 1149, in create
    bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2430, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single
    return meth(obj, **kw)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 963, in visit_table
    )._invoke_with(self.connection)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 315, in _invoke_with
    return bind.execute(self)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1526, in _execute_ddl
    ret = self._execute_context(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: 
CREATE TABLE alembic_version (
	version_num VARCHAR(32) NOT NULL, 
	CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
)
]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
yarn run v1.22.19
$ nuxt start -p 3000
ℹ [HPM] Proxy created: api  -> http://localhost:9000
ℹ [HPM] Proxy rewrite rule created: "api" ~> "/api"
ℹ [HPM] Proxy created: /api  -> http://localhost:9000
ℹ Listening on: http://172.17.0.6:3000/
INFO:     Started server process [15]
INFO:     Waiting for application startup.
INFO: 02-Jul-23 13:57:00 	-----SYSTEM STARTUP----- 
INFO: 02-Jul-23 13:57:00 	------APP SETTINGS------
INFO: 02-Jul-23 13:57:00 	{
    "PRODUCTION": true,
    "BASE_URL": "http://localhost:8080",
    "IS_DEMO": false,
    "API_PORT": 9000,
    "API_DOCS": true,
    "TOKEN_TIME": 48,
    "LOG_LEVEL": "INFO",
    "GIT_COMMIT_HASH": "4af9eec89dd0b309ebea752d715add3fe0980b3d",
    "ALLOW_SIGNUP": true,
    "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
    "SECURITY_USER_LOCKOUT_TIME": 24,
    "DB_ENGINE": "sqlite",
    "DB_PROVIDER": {
        "data_dir": "/app/data",
        "prefix": ""
    },
    "DEFAULT_GROUP": "Home",
    "DEFAULT_EMAIL": "changeme@email.com",
    "SMTP_HOST": null,
    "SMTP_PORT": "587",
    "SMTP_FROM_NAME": "Mealie",
    "SMTP_FROM_EMAIL": null,
    "SMTP_AUTH_STRATEGY": "TLS",
    "LDAP_AUTH_ENABLED": false,
    "LDAP_SERVER_URL": null,
    "LDAP_TLS_INSECURE": false,
    "LDAP_TLS_CACERTFILE": null,
    "LDAP_ENABLE_STARTTLS": false,
    "LDAP_BASE_DN": null,
    "LDAP_QUERY_BIND": null,
    "LDAP_QUERY_PASSWORD": null,
    "LDAP_USER_FILTER": null,
    "LDAP_ADMIN_FILTER": null,
    "LDAP_ID_ATTRIBUTE": "uid",
    "LDAP_MAIL_ATTRIBUTE": "mail",
    "LDAP_NAME_ATTRIBUTE": "name",
    "TESTING": false
}
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
```

**Comment by Toakan** [comment]
This is a known limitation with SQLite. It can't be stored on a networked drive as the FILE_LOCK() call's aren't done in time before the next call is required. This is a problem across multiple projects.

- The solution is to use a persistent volume for the SQLite db file.
- The alternative is to use PostgreSQL.

A better solution would be for the application to support MySQL/MariaDB instances from the outset. Too much can go wrong with SQLite, it causes headaches for everyone who want's to deploy it in a non-volatile solution.

You can also do this, as a workaround. However, the SQLite DB is non-persisted. You will get some level of network storage for the bits you can.

```
  volumes:
    - /var/mnt/storage/mealie/backups:/app/data/backups
    - /var/mnt/storage/mealie/recipes:/app/data/recipes
    - /var/mnt/storage/mealie/templates:/app/data/templates
    - /var/mnt/storage/mealie/users:/app/data/users
    - /var/mnt/storage/mealie/groups:/app/data/groups

    - mealie-data:/app/data/
```

**Comment by mgrimace** [comment]
> This is a known limitation with SQLite. It can't be stored on a networked drive as the FILE_LOCK() call's aren't done in time before the next call is required. This is a problem across multiple projects.
> 
> The solution is to use a persistent volume for the SQLite db file. The alternative is to use PostgreSQL.
> 
> A better solution would be for the application to support MySQL/MariaDB instances from the outset. Too much can go wrong with SQLite, it causes headaches for everyone who want's to deploy it in a non-volatile solution.
> 
> You can also do this, as a workaround. However, the SQLite DB is non-persisted. You will get some level of network storage for the bits you can.
> 
> ```
>   volumes:
>     - /var/mnt/storage/mealie/backups:/app/data/backups
>     - /var/mnt/storage/mealie/recipes:/app/data/recipes
>     - /var/mnt/storage/mealie/templates:/app/data/templates
>     - /var/mnt/storage/mealie/users:/app/data/users
>     - /var/mnt/storage/mealie/groups:/app/data/groups
> 
>     - mealie-data:/app/data/
> ```

Thanks so much for the clear explanation, and the workaround. For what it's worth I'm in full support of a PostgresSQL/MySQL/MariaDB replacement for SQLite to enable network storage of the database (and to resolve other potential DB issues/use-cases).

**Comment by Toakan** [comment]
> > This is a known limitation with SQLite. It can't be stored on a networked drive as the FILE_LOCK() call's aren't done in time before the next call is required. This is a problem across multiple projects.
> > The solution is to use a persistent volume for the SQLite db file. The alternative is to use PostgreSQL.
> > A better solution would be for the application to support MySQL/MariaDB instances from the outset. Too much can go wrong with SQLite, it causes headaches for everyone who want's to deploy it in a non-volatile solution.
> > You can also do this, as a workaround. However, the SQLite DB is non-persisted. You will get some level of network storage for the bits you can.
> > ```
> >   volumes:
> >     - /var/mnt/storage/mealie/backups:/app/data/backups
> >     - /var/mnt/storage/mealie/recipes:/app/data/recipes
> >     - /var/mnt/storage/mealie/templates:/app/data/templates
> >     - /var/mnt/storage/mealie/users:/app/data/users
> >     - /var/mnt/storage/mealie/groups:/app/data/groups
> > 
> >     - mealie-data:/app/data/
> > ```
> 
> Thanks so much for the clear explanation, and the workaround. For what it's worth I'm in full support of a PostgresSQL/MySQL/MariaDB replacement for SQLite to enable network storage of the database (and to resolve other potential DB issues/use-cases).

Glad to be of help!

Just to be clear, this project already supports PostgreSQL, the documentation for which [is here:](https://nightly.mealie.io/documentation/getting-started/installation/postgres/)

**Comment by TheRealVira** [comment]
Thank you for sharing that link @Toakan! I was only aware of this: https://nightly.mealie.io/documentation/getting-started/installation/single-container/

I guess most will land there since it is advertised as single container solution - a deploy and forget config. Sqllite is marked as recommended, which is why I haven't even looked at the other deployment options.

**Comment by mgrimace** [comment]
> Glad to be of help!
> 
> Just to be clear, this project already supports PostgreSQL, the documentation for which [is here:](https://nightly.mealie.io/documentation/getting-started/installation/postgres/)

Thanks again! For my use, I'm speaking specifically to the [omni/single-container version](https://nightly.mealie.io/documentation/getting-started/installation/single-container/), which does look like users can specify postgres with an additional snippet:

"The single container comes with SQLite, and can be used with PostgreSQL by adding a postgres container to the docker-compose file (see the [PostgreSQL install](https://nightly.mealie.io/documentation/getting-started/installation/postgres/) for a snippet)."

**Comment by mgrimace** [comment]
> Thank you for sharing that link @Toakan! I was only aware of this: https://nightly.mealie.io/documentation/getting-started/installation/single-container/
> 
> I guess most will land there since it is advertised as single container solution - a deploy and forget config. Sqllite is marked as recommended, which is why I haven't even looked at the other deployment options.

For what it's worth this is exactly the same scenario that landed me here, perhaps shifting the omni from SQLite -> Postgres as the default database is a valid consideration for the omni version.

**Comment by hay-kot** [comment]
Sounds like the issue here is with SQLite and not on us. So if you want to use network storage, I would suggest looking at deploying with Postgres and not SQLite.
