### ISSUE TITLE
[v1.0.0b] - Tools Using Slug in SQL, Preventing Multi-Tenantcy

### ISSUE THREAD

**Issue by Mrlilal** [mealie-recipes/mealie#2471]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I have two different Groups, each with different recipes and such. I created my group and added all the relevant tools, such as "Air Fryer" and "Baking Sheet." In the second group, when I attempt to create a tool named "Air Fryer," it pops up with an error stating "An Unexpected error occurred," and gives an error log in the API stating the following:
```ERROR: 28-Jul-23 17:09:30 (sqlite3.IntegrityError) UNIQUE constraint failed: tools.slug
[SQL: INSERT INTO tools (id, group_id, name, slug, on_hand, created_at, update_at) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('2353ac597112457696068004bb0f2a42', '32070720b1c445e29b8752528f2aad87', 'Air Fryer', 'air-fryer', 0, '2023-07-28 17:09:30.803396', '2023-07-28 17:09:30.803406')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
self.dialect.do_execute(
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: tools.slug
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/app/mealie/routes/_base/mixins.py", line 68, in create_one
item = self.repo.create(data)
File "/app/mealie/repos/repository_generic.py", line 169, in create
self.session.commit()
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1920, in commit
trans.commit(_to_root=True)
File "<string>", line 2, in commit
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
ret_value = fn(self, *arg, **kw)
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1236, in commit
self._prepare_impl()
File "<string>", line 2, in _prepare_impl
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
ret_value = fn(self, *arg, **kw)
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1211, in _prepare_impl
self.session.flush()
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4163, in flush
self._flush(objects)
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4298, in _flush
with util.safe_reraise():
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
raise exc_value.with_traceback(exc_tb)
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4259, in _flush
flush_context.execute()
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
rec.execute(self)
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
util.preloaded.orm_persistence.save_obj(
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
_emit_insert_statements(
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1226, in _emit_insert_statements
result = connection.execute(
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
return meth(
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
return connection._execute_clauseelement(
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
ret = self._execute_context(
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
return self._exec_single_context(
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
self._handle_dbapi_exception(
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
self.dialect.do_execute(
File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: tools.slug
[SQL: INSERT INTO tools (id, group_id, name, slug, on_hand, created_at, update_at) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('2353ac597112457696068004bb0f2a42', '32070720b1c445e29b8752528f2aad87', 'Air Fryer', 'air-fryer', 0, '2023-07-28 17:09:30.803396', '2023-07-28 17:09:30.803406')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
INFO: 127.0.0.1:40330 - "POST /api/organizers/tools HTTP/1.1" 400 Bad Request
INFO: 127.0.0.1:40346 - "GET /api/organizers/tools?page=1&perPage=-1 HTTP/1.1" 200 OK```

Tags, Categories, and everything else are fine, and it appears that only Tools are having this issue.
I have also checked on the Nightly Demo, and it appears to have the same issue.

### Deployment

Docker (Linux)

### Deployment Details

_No response_

**Comment by michael-genson** [comment]
Thanks for the report! Yup, looks like tool slugs are marked as unique, which shouldn't be the case. There's already a group + slug unique constraint, we just need to remove the unique slug constraint (which makes it unique across groups).
