### ISSUE TITLE
[v1.0.0b] - Can't Import Recipes after Restore

### ISSUE THREAD

**Issue by yottabit42** [mealie-recipes/mealie#2479]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When trying to import any recipe, including from sites I have imported from in the past, I receive the following error message:

> Looks Like We Couldn't Find Anything
> Only websites containing ld+json or microdata can be imported by Mealie. Most major recipe websites support this data structure. If your site cannot be imported but there is json data in the log, please submit a github issue with the URL and data.

I have been unable to import recipes since restoring my database into a new instance of Mealie.

Example recipes that will not import:

- https://www.recipetineats.com/crispy-smashed-potatoes/
- https://littlespoonfarm.com/sourdough-country-loaf-recipe/
- https://www.noracooks.com/vegan-pumpkin-muffins/

### Deployment

Docker (Linux)

### Deployment Details

Mealie v1.0.0beta-5 deployed from TrueCharts repo in TrueNAS.

**Details**
Version: v1.0.0beta-5
Build: ee121a12f8db33ecb4db5f8582f7ea9788d019e4
Application Mode: Production
Demo Status: Not Demo
API Port: 10019
API Docs: Enabled
Database Type: postgres
Recipe Scraper Version: 14.20.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: No
Docker Volumes: success

**Comment by hay-kot** [comment]
Can you provide your logs?

**Comment by yottabit42** [comment]
Hello! In which path can I find the Mealie logs in a docker container? Thanks!

**Comment by yottabit42** [comment]
Found it:

```
/app/data # tail -f -n 0 mealie.log 
INFO: 06-Aug-23 09:36:35        Image ['https://www.recipetineats.com/wp-content/uploads/2018/02/Crispy-Smashed-Potatoes_4a_1500px.jpg', 'https://www.recipetineats.com/wp-content/uploads/2018/02/Crispy-Smashed-Potatoes_4a_1500px.jpg?w=500&h=500&crop=1', 'https://www.recipetineats.com/wp-content/uploads/2018/02/Crispy-Smashed-Potatoes_4a_1500px.jpg?w=500&h=375&crop=1', 'https://www.recipetineats.com/wp-content/uploads/2018/02/Crispy-Smashed-Potatoes_4a_1500px.jpg?w=480&h=270&crop=1']
INFO: 06-Aug-23 09:36:35        File Name Suffix .jpg
INFO: 06-Aug-23 09:36:36        original.jpg minified
INFO: 06-Aug-23 09:36:36        Tiny image saved
ERROR: 06-Aug-23 09:36:36       Exception in ASGI application
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_executemany(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 953, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/psycopg2/extras.py", line 1270, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "recipes_ingredients_pkey"
DETAIL:  Key (id)=(203) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/app/./mealie/routes/_base/routers.py", line 36, in custom_route_handler
    response = await original_route_handler(request)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/app/./mealie/routes/recipe/recipe_crud_routes.py", line 179, in parse_recipe_url
    new_recipe = self.service.create_one(recipe)
  File "/app/./mealie/services/recipe/recipe_service.py", line 135, in create_one
    return self.repos.recipes.create(data)
  File "/app/./mealie/repos/repository_recipes.py", line 33, in create
    return super().create(document)
  File "/app/./mealie/repos/repository_generic.py", line 149, in create
    self.session.commit()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3383, in flush
    self._flush(objects)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3522, in _flush
    with util.safe_reraise():
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3483, in _flush
    flush_context.execute()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1156, in _emit_insert_statements
    c = connection._execute_20(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_executemany(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 953, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/psycopg2/extras.py", line 1270, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "recipes_ingredients_pkey"
DETAIL:  Key (id)=(203) already exists.

[SQL: INSERT INTO recipes_ingredients (created_at, update_at, position, recipe_id, title, note, unit_id, food_id, quantity, original_text, reference_id) VALUES (%(created_at)s, %(update_at)s, %(position)s, %(recipe_id)s, %(title)s, %(note)s, %(unit_id)s, %(food_id)s, %(quantity)s, %(original_text)s, %(reference_id)s) RETURNING recipes_ingredients.id]
[parameters: ({'created_at': datetime.datetime(2023, 8, 6, 9, 36, 36, 184856), 'update_at': datetime.datetime(2023, 8, 6, 9, 36, 36, 184860), 'position': 0, 'recipe_id': UUID('16f49f5c-1f2a-4d0e-9e4f-b48f7ff7e7a5'), 'title': None, 'note': '700g / 1.4 lb small potatoes (12 - 14) ((Note 1))', 'unit_id': None, 'food_id': None, 'quantity': 1.0, 'original_text': None, 'reference_id': UUID('45845e97-5112-4512-98cf-cc69f95097a2')}, {'created_at': datetime.datetime(2023, 8, 6, 9, 36, 36, 184863), 'update_at': datetime.datetime(2023, 8, 6, 9, 36, 36, 184864), 'position': 1, 'recipe_id': UUID('16f49f5c-1f2a-4d0e-9e4f-b48f7ff7e7a5'), 'title': None, 'note': '1 - 1.2kg / 2 - 2.4lb medium potatoes (6 - 8)', 'unit_id': None, 'food_id': None, 'quantity': 1.0, 'original_text': None, 'reference_id': UUID('8a4bf68c-fb21-4527-9867-1fc09015eebb')}, {'created_at': datetime.datetime(2023, 8, 6, 9, 36, 36, 184866), 'update_at': datetime.datetime(2023, 8, 6, 9, 36, 36, 184868), 'position': 2, 'recipe_id': UUID('16f49f5c-1f2a-4d0e-9e4f-b48f7ff7e7a5'), 'title': None, 'note': '1 tbsp salt ((for boiling))', 'unit_id': None, 'food_id': None, 'quantity': 1.0, 'original_text': None, 'reference_id': UUID('cda08ab1-fec9-4668-928d-3373b0c83bc3')}, {'created_at': datetime.datetime(2023, 8, 6, 9, 36, 36, 184870), 'update_at': datetime.datetime(2023, 8, 6, 9, 36, 36, 184871), 'position': 3, 'recipe_id': UUID('16f49f5c-1f2a-4d0e-9e4f-b48f7ff7e7a5'), 'title': None, 'note': '30g / 2 tbsp unsalted butter (, melted)', 'unit_id': None, 'food_id': None, 'quantity': 1.0, 'original_text': None, 'reference_id': UUID('e98ef545-feb1-4137-a8cc-1c271965676e')}, {'created_at': datetime.datetime(2023, 8, 6, 9, 36, 36, 184873), 'update_at': datetime.datetime(2023, 8, 6, 9, 36, 36, 184875), 'position': 4, 'recipe_id': UUID('16f49f5c-1f2a-4d0e-9e4f-b48f7ff7e7a5'), 'title': None, 'note': '1 tbsp olive oil', 'unit_id': None, 'food_id': None, 'quantity': 1.0, 'original_text': None, 'reference_id': UUID('daff9ffd-3c97-4512-a54e-4f541bee0474')}, {'created_at': datetime.datetime(2023, 8, 6, 9, 36, 36, 184877), 'update_at': datetime.datetime(2023, 8, 6, 9, 36, 36, 184878), 'position': 5, 'recipe_id': UUID('16f49f5c-1f2a-4d0e-9e4f-b48f7ff7e7a5'), 'title': None, 'note': '3/4 tsp salt ((for sprinkling))', 'unit_id': None, 'food_id': None, 'quantity': 1.0, 'original_text': None, 'reference_id': UUID('64202b38-714a-4dd8-bd1b-d3bcddc31e4c')}, {'created_at': datetime.datetime(2023, 8, 6, 9, 36, 36, 184880), 'update_at': datetime.datetime(2023, 8, 6, 9, 36, 36, 184882), 'position': 6, 'recipe_id': UUID('16f49f5c-1f2a-4d0e-9e4f-b48f7ff7e7a5'), 'title': None, 'note': '1/4 tsp black pepper', 'unit_id': None, 'food_id': None, 'quantity': 1.0, 'original_text': None, 'reference_id': UUID('95aeee5c-c404-453c-990e-cfd1ca51d00d')}, {'created_at': datetime.datetime(2023, 8, 6, 9, 36, 36, 184884), 'update_at': datetime.datetime(2023, 8, 6, 9, 36, 36, 184885), 'position': 7, 'recipe_id': UUID('16f49f5c-1f2a-4d0e-9e4f-b48f7ff7e7a5'), 'title': None, 'note': 'Finely chopped parsley (, optional garnish)', 'unit_id': None, 'food_id': None, 'quantity': 1.0, 'original_text': None, 'reference_id': UUID('e5f53bd5-c798-4e09-ab22-a711e7dd10f2')})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

**Comment by hay-kot** [comment]
Looks like it's related to this issue

https://github.com/mealie-recipes/mealie/issues/2051

Could you try the work around described there and/or see if the issue is present on the nightly branch?

**Comment by yottabit42** [comment]
Yep, that query fixed it up. Thanks for the help!

**Comment by yottabit42** [comment]
Yep, that query fixed it up. Thanks for the help!
