### ISSUE TITLE
Unable to create shopping list after restore to latest nightly version

### ISSUE THREAD

**Issue by beerbutcher** [mealie-recipes/mealie#2646]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

Came across a shopping list issue after upgrading to the latest nightly version and restoring the backup.  Prior to restoring shopping list functioned correctly after restoring everything seems to function great except when creating a shopping list I can crate and type in a new name then hit the create button a red bar runs across the top of the screen and nothing is saved.  I have tried several times reinstalling Mealie and restoring it with different backups with the same results.  Restoring to demo site causes the same issue.

### Steps to Reproduce

LInk to my backup file:
https://drive.google.com/file/d/119c-i-MwU8unA4NB9pU1GH3CeyBuphrC/view?usp=sharing

1. Fresh docker install pulling the latest nightly version as of 10/16/2023.
2. Upload my backup file, then  Restore.
3. went to create a new shopping list 
4. typed in new list name, click create 
5. nothing is saved. Link

### Please provide relevent logs

INFO:     127.0.0.1:37520 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:34414 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:49086 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     73.235.52.211:38604 - "GET /api/groups/shopping/lists?page=1&perPage=-1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/app/mealie/routes/groups/controller_shopping_lists.py", line 172, in get_all
    response = self.repo.page_all(
  File "/app/mealie/repos/repository_generic.py", line 339, in page_all
    items=[eff_schema.from_orm(s) for s in data],
  File "/app/mealie/repos/repository_generic.py", line 339, in <listcomp>
    items=[eff_schema.from_orm(s) for s in data],
  File "pydantic/main.py", line 579, in pydantic.main.BaseModel.from_orm
pydantic.error_wrappers.ValidationError: 22 validation errors for ShoppingListSummary
labelSettings -> 1 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 3 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 5 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 7 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 9 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 11 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 13 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 15 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 17 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 19 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 21 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 23 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 25 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 27 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 29 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 30 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 32 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 34 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 36 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 38 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 40 -> label
  none is not an allowed value (type=type_error.none.not_allowed)
labelSettings -> 42 -> label
  none is not an allowed value (type=type_error.none.not_allowed)

### Mealie Version

My Build report:
 https://pastebin.com/hsfCi88T

not sure what version,  but pulled Oct 16th, 2023

### Deployment

Docker (Linux)

### Additional Deployment Details

also using swag container in docker-compose.yml

**Comment by michael-genson** [comment]
Can you try restoring this backup and see if it works? I nuked all your shopping list related data:
https://www.transfernow.net/dl/20231016ufplCoAo

**Comment by beerbutcher** [comment]
Works!!!!  Thanks so much been trying all weekend to edit the shopping list database with no success.  How can I buy you some coffee?

**Comment by michael-genson** [comment]
Glad to hear :) None necessary, just glad it's working!

**Comment by beerbutcher** [comment]
Thanks Again!  I will buy a few more cups for the Mealie project then.
