### ISSUE TITLE
[BUG] - LDAPS unsupported

### ISSUE THREAD

**Issue by Mailstorm-ctrl** [mealie-recipes/mealie#2665]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

ldaps returns an error that the ldap server cannot be reached.

### Steps to Reproduce

Create a docker-compose.yaml file and include everything for LDAP. Except for the variable `LDAP_SERVER_URL` instead of using `ldap://url` do `ldaps://url`

### Please provide relevent logs

This populates the console as soon as you try to sign in.
```
mealie  | Traceback (most recent call last):
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
mealie  |     result = await app(  # type: ignore[func-returns-value]
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
mealie  |     return await self.app(scope, receive, send)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
mealie  |     await super().__call__(scope, receive, send)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
mealie  |     await self.middleware_stack(scope, receive, send)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
mealie  |     raise exc
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
mealie  |     await self.app(scope, receive, _send)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
mealie  |     await responder(scope, receive, send)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
mealie  |     await self.app(scope, receive, self.send_with_gzip)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
mealie  |     raise exc
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
mealie  |     await self.app(scope, receive, sender)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
mealie  |     raise e
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
mealie  |     await self.app(scope, receive, send)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
mealie  |     await route.handle(scope, receive, send)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
mealie  |     await self.app(scope, receive, send)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
mealie  |     response = await func(request)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
mealie  |     raw_response = await run_endpoint_function(
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
mealie  |     return await run_in_threadpool(dependant.call, **values)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
mealie  |     return await anyio.to_thread.run_sync(func, *args)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
mealie  |     return await get_asynclib().run_sync_in_worker_thread(
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
mealie  |     return await future
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
mealie  |     result = context.run(func, *args)
mealie  |   File "/app/mealie/routes/auth/auth.py", line 73, in get_token
mealie  |     user = authenticate_user(session, email, password)  # type: ignore
mealie  |   File "/app/mealie/core/security/security.py", line 56, in authenticate_user
mealie  |     return ldap.get_user(db, email, password)
mealie  |   File "/app/mealie/core/security/ldap.py", line 89, in get_user
mealie  |     conn.simple_bind_s(settings.LDAP_QUERY_BIND, settings.LDAP_QUERY_PASSWORD)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/ldap/ldapobject.py", line 248, in simple_bind_s
mealie  |     msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/ldap/ldapobject.py", line 242, in simple_bind
mealie  |     return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/ldap/ldapobject.py", line 128, in _ldap_call
mealie  |     result = func(*args,**kwargs)
mealie  | ldap.SERVER_DOWN: {'result': -1, 'desc': "Can't contact LDAP server", 'ctrls': [], 'info': '(unknown error code)'}```

### Mealie Version

v1.0.0-RC1.1

### Deployment

Docker (Linux)

### Additional Deployment Details

Using normal LDAP works. However, I want to use LDAPS and preferably not STARTTLS

**Comment by Mailstorm-ctrl** [comment]
This was mentioned in https://github.com/mealie-recipes/mealie/pull/681 but that was over a year ago and has been closed

**Comment by cmintey** [comment]
Can you share your environment variables with sensitive information removed?

**Comment by Mailstorm-ctrl** [comment]
> Can you share your environment variables with sensitive information removed?

Sure.

```
volumes:
      - mealie-data:/app/data/
      # I use LE for my auth server, So the CA is Internet Research which isn't present in the docker image
      - /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt:/root/ca-bundle
- LDAP_AUTH_ENABLED=true
      - LDAP_SERVER_URL=ldaps://auth.domain.tld
      - LDAP_TLS_CACERTFILE=/root/ca-bundle.crt
      #- LDAP_ENABLE_STARTTLS=true
      - LDAP_BASE_DN=DC=ldap,DC=goauthentik,DC=io
      - LDAP_QUERY_BIND=cn=mealieldap,ou=users,dc=ldap,dc=goauthentik,dc=io
      - LDAP_QUERY_PASSWORD=passwordhere
      - LDAP_USER_FILTER=(memberOf=cn=groupnamehere,ou=groups,dc=ldap,dc=go>
      - LDAP_ID_ATTRIBUTE=sAMAccountName
```

I've tried various versions trying to see if I was doing something wrong. But it just seems like as soon as you put s in ldap in the server url, it breaks

**Comment by cmintey** [comment]
Admittedly, I use LDAP but not over TLS, so it's hard for me to reproduce the issue. It's been on my todo list to set up TLS on my LDAP server but haven't gotten there yet.

Can you try setting `LDAP_TLS_INSECURE=true` just to see if the TLS verification is the issue?

**Comment by Mailstorm-ctrl** [comment]
Interesting. It worked. I guess I have to look into why TLS is failing.

**Comment by cmintey** [comment]
Yeah, double check your volumes and that your cert bundle is actually getting mounted in the container properly
