### ISSUE TITLE
[BUG] - Updating existing recipe with ingredient list fails 

### ISSUE THREAD

**Issue by b3n3w** [mealie-recipes/mealie#2741]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Whe updating a recipe by calling the /api/recipes PUT / PATCH endpoint, the API throws an error that the referenceId as type none is not allowed. 

### Steps to Reproduce

1)  Create new recipe by UI or API
2) Call PUT or PATCH ednppoint with the following data as body:
```
{
  prepTime: '45 minutes',
  totalTime: '45 minutes',
  description: 'A delicious and quick vegan pasta recipe with tofu.',
  recipeInstructions: [
    {
      title: '',
      text: 'Press the tofu to drain excess water, then cut it into small cubes.',
      ingredientReferences: []
    },
    {
      title: '',
      text: 'Cook the pasta according to package instructions, then drain and set aside.',
      ingredientReferences: []
    },
    {
      title: '',
      text: 'Heat olive oil in a large skillet over medium heat.',
      ingredientReferences: []
    },
    {
      title: '',
      text: 'Add chopped onion and minced garlic to the skillet, sauté until onion is translucent.',
      ingredientReferences: []
    },
    {
      title: '',
      text: 'Add cubed tofu to the skillet and cook until lightly browned.',
      ingredientReferences: []
    },
    {
      title: '',
      text: 'Slice the zucchini into thin half-moons and add them to the skillet.',
      ingredientReferences: []
    },
    {
      title: '',
      text: 'Pour in the diced tomatoes, dried basil, dried oregano, salt, and pepper. Stir well.',
      ingredientReferences: []
    },
    {
      title: '',
      text: 'Simmer the sauce for 10-15 minutes, allowing the flavors to blend.',
      ingredientReferences: []
    },
    {
      title: '',
      text: 'Add the cooked pasta to the skillet and toss it with the sauce to coat evenly.',
      ingredientReferences: []
    },
    {
      title: '',
      text: 'Remove from heat and serve hot. Enjoy your vegan tofu pasta!',
      ingredientReferences: []
    }
  ],
  recipeIngredient: [
    '1 block 200g tofu',
    '1/2 package 250g pasta',
    ' 2 tablespoons olive oil',
    '1 medium 1 onion',
    ' 2 cloves garlic',
    '1 medium 1 zucchini',
    '400g 1 can diced tomatoes',
    ' 1 teaspoon dried basil',
    ' 1/2 teaspoon dried oregano',
    'to taste Salt and pepper'
  ]
}
```

I also tried to parse the ingredients before againts the parsing endpoint and added it like this, but the error remains the same.

```
recipeIngredient: [
    {
      quantity: 1,
      unit: [Object],
      food: [Object],
      note: '',
      isFood: true,
      disableAmount: false,
      display: '1  block 200 gram tofu',
      title: '',
      originalText: null,
      referenceId: 'acc113e5-9358-49f2-abea-918b33e182a2'
    },
    {
      quantity: 0.5,
      unit: [Object],
      food: [Object],
      note: '',
      isFood: true,
      disableAmount: false,
      display: '¹/₂ package 250 gram pasta',
      title: '',
      originalText: null,
      referenceId: '7427c154-8b60-47fa-8af0-774d7d2ab1b2'
    },
    {
      quantity: 2,
      unit: [Object],
      food: [Object],
      note: '',
      isFood: true,
      disableAmount: false,
      display: '2 tablespoon olive oil',
      title: '',
      originalText: null,
      referenceId: 'b1c4dc51-f07f-4a30-a5df-6da08596db10'
    },
    {
      quantity: 1,
      unit: [Object],
      food: [Object],
      note: '',
      isFood: true,
      disableAmount: false,
      display: '1  medium 1 onion',
      title: '',
      originalText: null,
      referenceId: 'acf28ec8-6811-4e99-9973-6101f3921e78'
    },
    {
      quantity: 2,
      unit: [Object],
      food: [Object],
      note: '',
      isFood: true,
      disableAmount: false,
      display: '2 clove garlic',
      title: '',
      originalText: null,
      referenceId: 'aaed8a9b-6893-4bc9-8ba0-c41f9ae28fdf'
    },
    {
      quantity: 1,
      unit: [Object],
      food: [Object],
      note: '',
      isFood: true,
      disableAmount: false,
      display: '1  medium 1 zucchini',
      title: '',
      originalText: null,
      referenceId: '132a956f-f716-4da2-87fd-08e292335c0f'
    },
    {
      quantity: 1,
      unit: [Object],
      food: [Object],
      note: '',
      isFood: true,
      disableAmount: false,
      display: '1  400 gram 1 can diced tomatoes',
      title: '',
      originalText: null,
      referenceId: '65b5d3fc-77e8-4ba6-8af5-62fc43ffc4fc'
    },
    {
      quantity: 1,
      unit: [Object],
      food: [Object],
      note: 'dried',
      isFood: true,
      disableAmount: false,
      display: '1 teaspoon basil dried',
      title: '',
      originalText: null,
      referenceId: '487c5eb9-4550-4216-94f4-58ae19a8cc0a'
    },
    {
      quantity: 0.5,
      unit: [Object],
      food: [Object],
      note: 'dried',
      isFood: true,
      disableAmount: false,
      display: '¹/₂ teaspoon oregano dried',
      title: '',
      originalText: null,
      referenceId: '68751744-9cb6-4471-b524-0ac359beaad6'
    },
    {
      quantity: 1,
      unit: [Object],
      food: [Object],
      note: '',
      isFood: true,
      disableAmount: false,
      display: '1  to taste salt and pepper',
      title: '',
      originalText: null,
      referenceId: '7e5e7007-86ad-40b3-9ded-5208b093cf86'
    }
  ]

```

### Please provide relevant logs

```

ERROR: 20-Nov-23 18:59:55 	Unknown Error on recipe controller action
ERROR: 20-Nov-23 18:59:55 	'NoneType' object is not iterable
Traceback (most recent call last):
  File "/app/mealie/routes/recipe/recipe_crud_routes.py", line 339, in update_one
    recipe = self.service.update_one(slug, data)
  File "/app/mealie/services/recipe/recipe_service.py", line 342, in update_one
    new_data = self.repos.recipes.update(slug, update_data)
  File "/app/mealie/repos/repository_generic.py", line 208, in update
    entry.update(session=self.session, **new_data)
  File "/app/mealie/db/models/_model_base.py", line 24, in update
    self.__init__(*args, **kwarg)
  File "<string>", line 6, in __init__
  File "/app/mealie/db/models/recipe/api_extras.py", line 19, in wrapper
    return func(*args, extras=extras, **kwargs)
  File "/app/mealie/db/models/_model_utils/auto_init.py", line 145, in wrapper
    setattr(self, key, val)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 536, in __set__
    self.impl.set(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1276, in set
    value = self.fire_replace_event(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1291, in fire_replace_event
    value = fn(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/events.py", line 2556, in wrap
    fn(target, *arg)
  File "/app/mealie/db/models/recipe/recipe.py", line 239, in receive_name
    target.name_normalized = RecipeModel.normalize(value)
  File "/app/mealie/db/models/_model_base.py", line 15, in normalize
    return unidecode(val).lower().strip()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/text_unidecode/__init__.py", line 10, in unidecode
    for ch in txt:
TypeError: 'NoneType' object is not iterable
INFO:     192.168.2.201:41434 - "PUT /api/recipes/vegan-tofu-pasta-5 HTTP/1.1" 500 Internal Server Error

```

### Mealie Version

v1.0.0-RC1.1

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
You've not ticked the box saying it can be replicated on demo site. Does that mean you tried and were unable to, or you didn't try?
