### ISSUE TITLE
[BUG] - Database migration does not escape data properly

### ISSUE THREAD

**Issue by doctorjames** [mealie-recipes/mealie#2783]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

During database migration the following SQL is run:

`UPDATE ingredient_foods SET name_normalized='lamb's liver'`

The apostrophe in the existing food's name is not escaped.

### Steps to Reproduce

1) Have a an ingredient in the database containing an apostrophe from a BETA release.
2) Install RC2 and migrate to the latest database schema.

### Please provide relevant logs

```
2023-12-03T21:43:03.970502156Z INFO: 03-Dec-23 21:43:03 	Database connection established.
2023-12-03T21:43:03.976745548Z INFO: 03-Dec-23 21:43:03 	Context impl PostgresqlImpl.
2023-12-03T21:43:03.976822755Z INFO: 03-Dec-23 21:43:03 	Will assume transactional DDL.
2023-12-03T21:43:03.997238852Z INFO: 03-Dec-23 21:43:03 	Migration needed. Performing migration...
2023-12-03T21:43:04.004884711Z INFO: 03-Dec-23 21:43:04 	Context impl PostgresqlImpl.
2023-12-03T21:43:04.004906669Z INFO: 03-Dec-23 21:43:04 	Will assume transactional DDL.
2023-12-03T21:43:04.022398419Z INFO: 03-Dec-23 21:43:04 	Running upgrade b3dbb554ba53 -> 04ac51cbe9a4, added group slug
2023-12-03T21:43:04.095202934Z INFO: 03-Dec-23 21:43:04 	Running upgrade 04ac51cbe9a4 -> 1825b5225403, added recipe note to shopping list recipe ref
2023-12-03T21:43:04.096185660Z INFO: 03-Dec-23 21:43:04 	Running upgrade 1825b5225403 -> bcfdad6b7355, remove tool name and slug unique contraints
2023-12-03T21:43:04.099938404Z INFO: 03-Dec-23 21:43:04 	Running upgrade bcfdad6b7355 -> 0341b154f79a, added normalized unit and food names
2023-12-03T21:43:04.144833543Z Traceback (most recent call last):
2023-12-03T21:43:04.144864959Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
2023-12-03T21:43:04.145511610Z     self.dialect.do_execute(
2023-12-03T21:43:04.145526193Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
2023-12-03T21:43:04.145945391Z     cursor.execute(statement, parameters)
2023-12-03T21:43:04.145966932Z psycopg2.errors.SyntaxError: syntax error at or near "s"
2023-12-03T21:43:04.145975182Z LINE 1: UPDATE ingredient_foods SET name_normalized='lamb's liver' W...
2023-12-03T21:43:04.145983682Z                                                           ^
2023-12-03T21:43:04.146004390Z 
2023-12-03T21:43:04.146013723Z 
2023-12-03T21:43:04.146021181Z The above exception was the direct cause of the following exception:
2023-12-03T21:43:04.146029014Z 
2023-12-03T21:43:04.146036347Z Traceback (most recent call last):
2023-12-03T21:43:04.146049305Z   File "/app/mealie/db/init_db.py", line 110, in <module>
2023-12-03T21:43:04.146061472Z     main()
2023-12-03T21:43:04.146068847Z   File "/app/mealie/db/init_db.py", line 93, in main
2023-12-03T21:43:04.146076597Z     command.upgrade(alembic_cfg, "head")
2023-12-03T21:43:04.146083971Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/command.py", line 382, in upgrade
2023-12-03T21:43:04.146287091Z     script.run_env()
2023-12-03T21:43:04.146296550Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 578, in run_env
2023-12-03T21:43:04.146611292Z     util.load_python_file(self.dir, "env.py")
2023-12-03T21:43:04.146633875Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
2023-12-03T21:43:04.146770955Z     module = load_module_py(module_id, path)
2023-12-03T21:43:04.146779496Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 109, in load_module_py
2023-12-03T21:43:04.146815121Z     spec.loader.exec_module(module)  # type: ignore
2023-12-03T21:43:04.146835912Z   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-12-03T21:43:04.146881744Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-12-03T21:43:04.146925035Z   File "/app/alembic/env.py", line 77, in <module>
2023-12-03T21:43:04.146955951Z     run_migrations_online()
2023-12-03T21:43:04.146964534Z   File "/app/alembic/env.py", line 71, in run_migrations_online
2023-12-03T21:43:04.146993200Z     context.run_migrations()
2023-12-03T21:43:04.147008866Z   File "<string>", line 8, in run_migrations
2023-12-03T21:43:04.147030365Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/runtime/environment.py", line 922, in run_migrations
2023-12-03T21:43:04.147405815Z     self.get_context().run_migrations(**kw)
2023-12-03T21:43:04.147423106Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/runtime/migration.py", line 624, in run_migrations
2023-12-03T21:43:04.147711433Z     step.migration_fn(**kw)
2023-12-03T21:43:04.147722974Z   File "/app/alembic/versions/2023-09-01-14.55.42_0341b154f79a_added_normalized_unit_and_food_names.py", line 78, in upgrade
2023-12-03T21:43:04.147771223Z     populate_normalized_fields()
2023-12-03T21:43:04.147796431Z   File "/app/alembic/versions/2023-09-01-14.55.42_0341b154f79a_added_normalized_unit_and_food_names.py", line 54, in populate_normalized_fields
2023-12-03T21:43:04.147820013Z     session.execute(
2023-12-03T21:43:04.147828513Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2246, in execute
2023-12-03T21:43:04.148587828Z     return self._execute_internal(
2023-12-03T21:43:04.148596120Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2150, in _execute_internal
2023-12-03T21:43:04.148925737Z     result = conn.execute(
2023-12-03T21:43:04.148950903Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
2023-12-03T21:43:04.149151440Z     return meth(
2023-12-03T21:43:04.149160190Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
2023-12-03T21:43:04.149660761Z     return connection._execute_clauseelement(
2023-12-03T21:43:04.149677844Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
2023-12-03T21:43:04.149859215Z     ret = self._execute_context(
2023-12-03T21:43:04.149869714Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
2023-12-03T21:43:04.150101959Z     return self._exec_single_context(
2023-12-03T21:43:04.150131625Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
2023-12-03T21:43:04.150327745Z     self._handle_dbapi_exception(
2023-12-03T21:43:04.150335703Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
2023-12-03T21:43:04.150623988Z     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
2023-12-03T21:43:04.150643238Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
2023-12-03T21:43:04.150866816Z     self.dialect.do_execute(
2023-12-03T21:43:04.150887899Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
2023-12-03T21:43:04.150990813Z     cursor.execute(statement, parameters)
2023-12-03T21:43:04.151013437Z sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "s"
2023-12-03T21:43:04.151023937Z LINE 1: UPDATE ingredient_foods SET name_normalized='lamb's liver' W...
2023-12-03T21:43:04.151033395Z                                                           ^
2023-12-03T21:43:04.151042561Z 
2023-12-03T21:43:04.151058644Z [SQL: UPDATE ingredient_foods SET name_normalized='lamb's liver' WHERE id='0a094185-681a-4de4-944f-9fa7c5bb75bd']
2023-12-03T21:43:04.151068603Z (Background on this error at: https://sqlalche.me/e/20/f405)
2023-12-03T21:43:06.461252848Z INFO:     Started server process [15]
2023-12-03T21:43:06.461290681Z INFO:     Waiting for application startup.

```

### Mealie Version

a130bf88 + PR  #[2773](https://github.com/mealie-recipes/mealie/pull/2773)

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
@doctorjames I'm confused by your `Mealie Version` above, re PR #2773. Are you saying you've had an issue with that PR, or are you just suggesting that PR is expected to resolve this issue?

**Comment by michael-genson** [comment]
Fixed by https://github.com/mealie-recipes/mealie/pull/2773
