### ISSUE TITLE
Docker fails to start on Unraid using :nightly tag.  

### ISSUE THREAD

**Issue by rstuke82** [mealie-recipes/mealie#2847]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Here is part of the error that shows.  If I switch my docker to version to docker tag v1.0.0-RC2 loads without errors
`
Traceback (most recent call last):
  File "/app/mealie/db/init_db.py", line 17, in <module>
    from mealie.repos.seed.init_users import default_user_init
  File "/app/mealie/repos/seed/init_users.py", line 3, in <module>
    from mealie.core.security import hash_password
  File "/app/mealie/core/security/__init__.py", line 1, in <module>
    from .security import *
  File "/app/mealie/core/security/security.py", line 9, in <module>
    from mealie.core.security import ldap
  File "/app/mealie/core/security/ldap.py", line 1, in <module>
    import ldap
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/ldap/__init__.py", line 34, in <module>
    import _ldap
ImportError: libldap-2.5.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/pysetup/.venv/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 403, in main
    run(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/mealie/app.py", line 9, in <module>
    from mealie.routes import router, spa, utility_routes
  File "/app/mealie/routes/__init__.py", line 3, in <module>
    from . import (
  File "/app/mealie/routes/admin/__init__.py", line 3, in <module>
    from . import (
  File "/app/mealie/routes/admin/admin_backups.py", line 9, in <module>
    from mealie.core.security import create_file_token
  File "/app/mealie/core/security/__init__.py", line 1, in <module>
    from .security import *
  File "/app/mealie/core/security/security.py", line 9, in <module>
    from mealie.core.security import ldap
  File "/app/mealie/core/security/ldap.py", line 1, in <module>
    import ldap
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/ldap/__init__.py", line 34, in <module>
    import _ldap
ImportError: libldap-2.5.so.0: cannot open shared object file: No such file or directory`

### Steps to Reproduce

Installing docker app using 'nightly' tag

### Please provide relevant logs

`
Traceback (most recent call last):
  File "/app/mealie/db/init_db.py", line 17, in <module>
    from mealie.repos.seed.init_users import default_user_init
  File "/app/mealie/repos/seed/init_users.py", line 3, in <module>
    from mealie.core.security import hash_password
  File "/app/mealie/core/security/__init__.py", line 1, in <module>
    from .security import *
  File "/app/mealie/core/security/security.py", line 9, in <module>
    from mealie.core.security import ldap
  File "/app/mealie/core/security/ldap.py", line 1, in <module>
    import ldap
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/ldap/__init__.py", line 34, in <module>
    import _ldap
ImportError: libldap-2.5.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/pysetup/.venv/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 403, in main
    run(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/mealie/app.py", line 9, in <module>
    from mealie.routes import router, spa, utility_routes
  File "/app/mealie/routes/__init__.py", line 3, in <module>
    from . import (
  File "/app/mealie/routes/admin/__init__.py", line 3, in <module>
    from . import (
  File "/app/mealie/routes/admin/admin_backups.py", line 9, in <module>
    from mealie.core.security import create_file_token
  File "/app/mealie/core/security/__init__.py", line 1, in <module>
    from .security import *
  File "/app/mealie/core/security/security.py", line 9, in <module>
    from mealie.core.security import ldap
  File "/app/mealie/core/security/ldap.py", line 1, in <module>
    import ldap
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/ldap/__init__.py", line 34, in <module>
    import _ldap
ImportError: libldap-2.5.so.0: cannot open shared object file: No such file or directory`

### Deployment

Unraid

**Comment by mhoenes** [comment]
Same error here. Looks like it got introduced with commit ca9f66e. Prior to pulling that image some hours ago, everything worked fine.

**Comment by randomhouston** [comment]
Same, I am running into the same issue and the container wont start.

**Comment by Dola-Shuvi** [comment]
Can also confirm this issue. Perhaps the commit should be reverted until a fix is found.

**Comment by mhoenes** [comment]
Yes, going back to the previous commit c486803 solved the issue for me.

You can temporarily use ghcr.io/mealie-recipes/mealie@sha256:623cabacec055ead126e59d1d9ef07d6b002ab6f761afff218cf31591af07221 instead of ghcr.io/mealie-recipes/mealie:nightly to get a working image.

**Comment by randomhouston** [comment]
Correction, that image did launch, apologies.

**Comment by hay-kot** [comment]
There's an issue with the build cache, and doesn't really have anything to do with that commit other than it required that step to be re-run.

You _can_ fix this by execing into the container and manually installing the LDAP dependencies. I'm going to kick off another build with no cache and hopefully that will fix it.

**Comment by hay-kot** [comment]
New build here

- https://github.com/mealie-recipes/mealie/actions/runs/7223704528

Without any caches could take 2-3 hours :(

**Comment by McGeaverBeaver** [comment]
If we only replaced LDAP with OAuth2/OpenID Provider  👍

**Comment by hay-kot** [comment]
> If we only replaced LDAP with OAuth2/OpenID Provider 👍

Submit a PR with end to end tests and we'll merge it. Otherwise you can keep those comments to the other half a dozen threads where I've said the same thing.
