### ISSUE TITLE
[BUG] - ImportError: libldap-2.5.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Humschi** [mealie-recipes/mealie#2850]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

libldapt seems to be missing, and the container can't be started correctly. My container was working fine until a few days ago, so I assume the problem was introduced with the latest nightly release. v1.0.0-RC2 is starting correctly.

### Steps to Reproduce

Setup Mealie using the latest nightly image and LDAP configuration. 

### Please provide relevant logs

Traceback (most recent call last):
  File "/app/mealie/db/init_db.py", line 17, in <module>
    from mealie.repos.seed.init_users import default_user_init
  File "/app/mealie/repos/seed/init_users.py", line 3, in <module>
    from mealie.core.security import hash_password
  File "/app/mealie/core/security/__init__.py", line 1, in <module>
    from .security import *
  File "/app/mealie/core/security/security.py", line 9, in <module>
    from mealie.core.security import ldap
  File "/app/mealie/core/security/ldap.py", line 1, in <module>
    import ldap
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/ldap/__init__.py", line 34, in <module>
    import _ldap
ImportError: libldap-2.5.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/pysetup/.venv/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 403, in main
    run(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/mealie/app.py", line 9, in <module>
    from mealie.routes import router, spa, utility_routes
  File "/app/mealie/routes/__init__.py", line 3, in <module>
    from . import (
  File "/app/mealie/routes/admin/__init__.py", line 3, in <module>
    from . import (
  File "/app/mealie/routes/admin/admin_backups.py", line 9, in <module>
    from mealie.core.security import create_file_token
  File "/app/mealie/core/security/__init__.py", line 1, in <module>
    from .security import *
  File "/app/mealie/core/security/security.py", line 9, in <module>
    from mealie.core.security import ldap
  File "/app/mealie/core/security/ldap.py", line 1, in <module>
    import ldap
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/ldap/__init__.py", line 34, in <module>
    import _ldap
ImportError: libldap-2.5.so.0: cannot open shared object file: No such file or directory

### Mealie Version

ghcr.io/mealie-recipes/mealie:nightly

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Should be fixed by https://github.com/mealie-recipes/mealie/pull/2849. The build might take another hour or two, we had to disable the GH cache. If after the new build finishes and you're still seeing this error, feel free to re-open

**Comment by Humschi** [comment]
Yes, thank you. I saw the commit right after I opened the incident... Will take a better look next time.

**Comment by michael-genson** [comment]
No worries!
