### ISSUE TITLE
[BUG] - "Something Went Wrong!" trying to login after database restore

### ISSUE THREAD

**Issue by yottabit42** [mealie-recipes/mealie#2857]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I was running 1.0.0beta as a TrueCharts app. They changed a bunch of stuff and I was no longer able to upgrade from that version to the 1.0.0 release as they published it on a different channel/train. But when I restore the database on the new deployment, I can never login again, with "Something Went Wrong!" message banner at the top. I am using the user/pass that was saved in my password manager. The default user/pass also no longer works after the backup. I have used the python reset password script and it also errors out.

### Steps to Reproduce

1. Deploy 1.0.0
2. Login as default user
3. Upload backup from 1.0.0b
4. Restore uploaded backup
5. Attempt to login again

### Please provide relevant logs

Trying to reset password with the python scripts causes a database error:
```
$ python change_password.py
Please enter the email of the user you want to reset: jacobmcdonald75023@gmail.com
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column users.auth_method does not exist
LINE 1: ...ame, users.username, users.email, users.password, users.auth...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/mealie/scripts/change_password.py", line 40, in <module>
    main()
  File "/app/mealie/scripts/change_password.py", line 17, in main
    user = repos.users.get_one(confirmed, "email")
  File "/app/mealie/repos/repository_generic.py", line 159, in get_one
    result = self.session.execute(q).unique().scalars().one_or_none()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2246, in execute
    return self._execute_internal(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2141, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column users.auth_method does not exist
LINE 1: ...ame, users.username, users.email, users.password, users.auth...
                                                             ^

[SQL: SELECT users.id, users.full_name, users.username, users.email, users.password, users.auth_method, users.admin, users.advanced, users.group_id, users.cache_key, users.login_attemps, users.locked_at, users.can_manage, users.can_invite, users.can_organize, users.owned_recipes_id, users.created_at, users.update_at, groups_1.id AS id_1, groups_1.name, groups_1.slug, groups_1.created_at AS created_at_1, groups_1.update_at AS update_at_1, long_live_tokens_1.name AS name_1, long_live_tokens_1.token, long_live_tokens_1.user_id, long_live_tokens_1.id AS id_2, long_live_tokens_1.created_at AS created_at_2, long_live_tokens_1.update_at AS update_at_2 
FROM users LEFT OUTER JOIN groups AS groups_1 ON groups_1.id = users.group_id LEFT OUTER JOIN long_live_tokens AS long_live_tokens_1 ON users.id = long_live_tokens_1.user_id 
WHERE users.email = %(email_1)s]
[parameters: {'email_1': 'jacobmcdonald75023@gmail.com'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
```

### Mealie Version

1.0.0

### Deployment

TrueNAS

**Comment by michael-genson** [comment]
It looks like something went wrong when setting the database up. Are you able to share the backup file?

**Comment by boc-the-git** [comment]
Also can you provide more specific version numbers for reference? The ones you've provided are not clear.

**Comment by yottabit42** [comment]
[Here](https://drive.google.com/file/d/19cifXO3gi4k69lUzAI_SCN1YeMshCBMb/view?usp=sharing) is the database backup.

I'm working on getting the exact versions now, but it's going to take a while since I can only have one instance running at a time (conflicting port numbers), and they take a long time to stop and deploy. I'll post those shortly.

**Comment by michael-genson** [comment]
I was looking into a different user's backup issue and was able to fix it. I checked yours against the new branch and yours works too with the new fix.

If you're able, try pulling my branch in https://github.com/mealie-recipes/mealie/pull/2859 and migrate your DB using that. If you're unable, and you're using SQLite, I can just send you the migrated db. Otherwise, once that PR is merged you should be able to pull nightly and the restore should work.

**Comment by yottabit42** [comment]
> I was looking into a different user's backup issue and was able to fix it. I checked yours against the new branch and yours works too with the new fix.
> 
> If you're able, try pulling my branch in #2859 and migrate your DB using that. If you're unable, and you're using SQLite, I can just send you the migrated db. Otherwise, once that PR is merged you should be able to pull nightly and the restore should work.

Thanks! I will need to wait a few weeks/months until TrueCharts eventually updates to the new version unfortunately. And they use Postgres instead of Sqlite, and their new charts use cloudnative-pg which I can't even get admin access to, so I can't even manipulate the databases directly. :-/

Old version:
```
**Details**
Version: v1.0.0beta-5
Build: ee121a12f8db33ecb4db5f8582f7ea9788d019e4
Application Mode: Production
Demo Status: Not Demo
API Port: 10019
API Docs: Enabled
Database Type: postgres
Recipe Scraper Version: 14.20.0

**Checks**
Secure Site: No
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: No
Docker Volumes: success
```

**Comment by michael-genson** [comment]
Ah yeah that sucks. If you have the option of doing more incremental upgrades that _might_ work. Specifically upgrading to omni nightly (old single-container version) then to RC1.1, then to RC2, you _might_ get lucky and it might work. Kinda a shot in the dark though

**Comment by yottabit42** [comment]
This is the latest version available in the TrueCharts repo:

```
**Details**
Version: v1.0.0-RC2
Build: c9852daf0e213dc4cadf97971c7787cf6fc66dfc
Application Mode: Production
Demo Status: Not Demo
API Port: 10018
API Docs: Enabled
Database Type: postgres
Recipe Scraper Version: 14.52.0

**Checks**
Secure Site: No
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: No
Docker Volume: success
```

**Comment by michael-genson** [comment]
Yeah that's the latest stable version, that makes sense

**Comment by yottabit42** [comment]
> I was looking into a different user's backup issue and was able to fix it. I checked yours against the new branch and yours works too with the new fix.
> 
> If you're able, try pulling my branch in #2859 and migrate your DB using that. If you're unable, and you're using SQLite, I can just send you the migrated db. Otherwise, once that PR is merged you should be able to pull nightly and the restore should work.

It just occurred to me that if you were able to import my database, could you then export it from your branch and would it import into RC2?

**Comment by michael-genson** [comment]
Looking into this a little bit more it seems there's still an issue to look into. Will try to find time tomorrow

**Comment by jsaathof** [comment]
Im having issues with upgrading Mealie from 1.0.0-beta5 to 1.0.0-RC2 as well, also database related. I ran into this exact same issue after restoring a backup into a new database. 

By the looks of it a database restore throws away the database and restores it with the beta5 version. That means the database migration has not run yet. Upon restarting the container (I am running a docker installation) the migration is run but fails at the last part. Since the upgrade is done in a Postgres transaction, all is reverted.
```
INFO: 18-Dec-23 07:35:42        Database connection established.
INFO: 18-Dec-23 07:35:42        Context impl PostgresqlImpl.
INFO: 18-Dec-23 07:35:42        Will assume transactional DDL.
INFO: 18-Dec-23 07:35:42        Migration needed. Performing migration...
INFO: 18-Dec-23 07:35:42        Context impl PostgresqlImpl.
INFO: 18-Dec-23 07:35:42        Will assume transactional DDL.
INFO: 18-Dec-23 07:35:42        Running upgrade 44e8d670719d -> 2ea7a807915c, add recipe_timeline_events table
INFO: 18-Dec-23 07:35:42        Running upgrade 2ea7a807915c -> 1923519381ad, added recipe last made timestamp
INFO: 18-Dec-23 07:35:42        Running upgrade 1923519381ad -> 167eb69066ad, add recipe_scale to shopping list item ref
INFO: 18-Dec-23 07:35:42        Running upgrade 167eb69066ad -> 165d943c64ee, add related user to mealplan
INFO: 18-Dec-23 07:35:42        Running upgrade 165d943c64ee -> ff5f73b01a7a, add missing foreign key and order indices
INFO: 18-Dec-23 07:35:43        Running upgrade ff5f73b01a7a -> 16160bf731a0, add more indices necessary for search
INFO: 18-Dec-23 07:35:43        Running upgrade 16160bf731a0 -> 5ab195a474eb, add normalized search properties
INFO: 18-Dec-23 07:35:43        Running upgrade 5ab195a474eb -> b04a08da2108, added shopping list label settings
INFO: 18-Dec-23 07:35:44        Running upgrade b04a08da2108 -> 38514b39a824, add auth_method to user table
INFO: 18-Dec-23 07:35:44        Running upgrade 38514b39a824 -> b3dbb554ba53, postgres fuzzy search
INFO: 18-Dec-23 07:35:44        Running upgrade b3dbb554ba53 -> 04ac51cbe9a4, added group slug
INFO: 18-Dec-23 07:35:44        Running upgrade 04ac51cbe9a4 -> 1825b5225403, added recipe note to shopping list recipe ref
INFO: 18-Dec-23 07:35:44        Running upgrade 1825b5225403 -> bcfdad6b7355, remove tool name and slug unique contraints
INFO: 18-Dec-23 07:35:44        Running upgrade bcfdad6b7355 -> 0341b154f79a, added normalized unit and food names
INFO: 18-Dec-23 07:35:44        Running upgrade 0341b154f79a -> dded3119c1fe, added unique constraints
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column ingredient_foods.plural_name does not exist
LINE 1: ..., ingredient_foods.name AS ingredient_foods_name, ingredient...

<exception stack>

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column ingredient_foods.plural_name does not exist
LINE 1: ..., ingredient_foods.name AS ingredient_foods_name, ingredient...
                                                             ^

[SQL: SELECT ingredient_foods.id AS ingredient_foods_id, ingredient_foods.group_id AS ingredient_foods_group_id, ingredient_foods.name AS ingredient_foods_name, ingredient_foods.plural_name AS ingredient_foods_plural_name, ingredient_foods.description AS ingredient_foods_description, ingredient_foods.label_id AS ingredient_foods_label_id, ingredient_foods.name_normalized AS ingredient_foods_name_normalized, ingredient_foods.plural_name_normalized AS ingredient_foods_plural_name_normalized, ingredient_foods.created_at AS ingredient_foods_created_at, ingredient_foods.update_at AS ingredient_foods_update_at
FROM ingredient_foods
WHERE ingredient_foods.id = %(pk_1)s::UUID]
[parameters: {'pk_1': '08b3d57e-dbd8-4f3c-aac7-28b2e2cb2ae5'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
INFO:     Started server process [15]
INFO:     Waiting for application startup.
```

Apparently there is something wrong with the migration or my database.

This is my database version which works well with 1.0.0-beta5.
```
mealie=# select * from alembic_version;
 version_num
--------------
 44e8d670719d
(1 row)
```

Full output:

[exception.txt](https://github.com/mealie-recipes/mealie/files/13700296/exception.txt)
