### ISSUE TITLE
[BUG] - Can't log back in as an admin account

### ISSUE THREAD

**Issue by brunoelgrande** [mealie-recipes/mealie#2908]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [x] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

After login out, I can't log back in my admin account on my computer. 
I'm still log in on my iPad tough, so I set up my wife as admin as a safeguard.

Logs talks about `handle_many_to_many_list`
 
Other users from my group or other groups are able to log in.

---
⁉️ 
Can I delete my account (who created almost all the recipes) and start a new one, or will this affect the recipes ?

### Steps to Reproduce

1. Ask for a password reset at login, didn't receive an email
1. Try for new password from another admin account
2. 1. Restarted the container 
1. Updated to a new nightly build 
1. Looked up the db for duplicate user, group, recipe, etc...
3. Cleared cache
4. Try incognito mode
5. Tried new and old password

### Please provide relevant logs

```
2024-01-05T00:17:58.420223738Z INFO:     127.0.0.1:46544 - "GET /api/app/about HTTP/1.1" 200 OK
2024-01-05T00:18:29.446517257Z INFO:     127.0.0.1:53054 - "GET /api/app/about HTTP/1.1" 200 OK
2024-01-05T00:18:44.390876831Z INFO:     192.168.101.120:39462 - "POST /api/auth/token HTTP/1.1" 500 Internal Server Error
2024-01-05T00:18:44.394307646Z ERROR:    Exception in ASGI application
2024-01-05T00:18:44.394331590Z Traceback (most recent call last):
2024-01-05T00:18:44.394341114Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
2024-01-05T00:18:44.394350174Z     result = await app(  # type: ignore[func-returns-value]
2024-01-05T00:18:44.394358255Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2024-01-05T00:18:44.394366930Z     return await self.app(scope, receive, send)
2024-01-05T00:18:44.394375014Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
2024-01-05T00:18:44.394383087Z     await super().__call__(scope, receive, send)
2024-01-05T00:18:44.394391043Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2024-01-05T00:18:44.394399091Z     await self.middleware_stack(scope, receive, send)
2024-01-05T00:18:44.394407083Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2024-01-05T00:18:44.394415375Z     raise exc
2024-01-05T00:18:44.394423093Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2024-01-05T00:18:44.394431178Z     await self.app(scope, receive, _send)
2024-01-05T00:18:44.394439030Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
2024-01-05T00:18:44.394447122Z     await responder(scope, receive, send)
2024-01-05T00:18:44.394454877Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
2024-01-05T00:18:44.394462949Z     await self.app(scope, receive, self.send_with_gzip)
2024-01-05T00:18:44.394470914Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024-01-05T00:18:44.394479297Z     raise exc
2024-01-05T00:18:44.394535141Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024-01-05T00:18:44.394556137Z     await self.app(scope, receive, sender)
2024-01-05T00:18:44.394571520Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2024-01-05T00:18:44.394586358Z     raise e
2024-01-05T00:18:44.394600258Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2024-01-05T00:18:44.394615021Z     await self.app(scope, receive, send)
2024-01-05T00:18:44.394623833Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2024-01-05T00:18:44.394631686Z     await route.handle(scope, receive, send)
2024-01-05T00:18:44.394640681Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2024-01-05T00:18:44.394649436Z     await self.app(scope, receive, send)
2024-01-05T00:18:44.394657637Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
2024-01-05T00:18:44.394673708Z     response = await func(request)
2024-01-05T00:18:44.394689705Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
2024-01-05T00:18:44.394704379Z     raw_response = await run_endpoint_function(
2024-01-05T00:18:44.394720148Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
2024-01-05T00:18:44.394736231Z     return await run_in_threadpool(dependant.call, **values)
2024-01-05T00:18:44.394752258Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
2024-01-05T00:18:44.394763452Z     return await anyio.to_thread.run_sync(func, *args)
2024-01-05T00:18:44.394784110Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
2024-01-05T00:18:44.394792828Z     return await get_asynclib().run_sync_in_worker_thread(
2024-01-05T00:18:44.394800774Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
2024-01-05T00:18:44.394808965Z     return await future
2024-01-05T00:18:44.394816701Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
2024-01-05T00:18:44.394824734Z     result = context.run(func, *args)
2024-01-05T00:18:44.394832492Z   File "/app/mealie/routes/auth/auth.py", line 73, in get_token
2024-01-05T00:18:44.394840477Z     user = authenticate_user(session, email, password)  # type: ignore
2024-01-05T00:18:44.394848978Z   File "/app/mealie/core/security/security.py", line 77, in authenticate_user
2024-01-05T00:18:44.394856945Z     return db.users.update(user.id, user)
2024-01-05T00:18:44.394864939Z   File "/app/mealie/repos/repository_users.py", line 52, in update
2024-01-05T00:18:44.394882937Z     return super().update(match_value, new_data)
2024-01-05T00:18:44.394891856Z   File "/app/mealie/repos/repository_generic.py", line 208, in update
2024-01-05T00:18:44.394900048Z     entry.update(session=self.session, **new_data)
2024-01-05T00:18:44.394908064Z   File "/app/mealie/db/models/_model_utils/auto_init.py", line 187, in wrapper
2024-01-05T00:18:44.394916271Z     instances = handle_many_to_many(session, get_attr, relation_cls, val)
2024-01-05T00:18:44.394924359Z   File "/app/mealie/db/models/_model_utils/auto_init.py", line 73, in handle_many_to_many
2024-01-05T00:18:44.394932506Z     return handle_one_to_many_list(session, get_attr, relation_cls, all_elements)
2024-01-05T00:18:44.394941792Z   File "/app/mealie/db/models/_model_utils/auto_init.py", line 87, in handle_one_to_many_list
2024-01-05T00:18:44.394950740Z     existing_elem = session.execute(stmt).scalars().one_or_none()
2024-01-05T00:18:44.394958891Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 1815, in one_or_none
2024-01-05T00:18:44.394967587Z     return self._only_one_row(
2024-01-05T00:18:44.394975692Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 813, in _only_one_row
2024-01-05T00:18:44.394984261Z     raise exc.MultipleResultsFound(
2024-01-05T00:18:44.394992265Z sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when one or none was required
```

### Mealie Version

**Details**
Version: nightly
Build: 44ca79e7cdf307caf8118f926124b9008d393261
Mode de l’application: Réalisation
Mode démo: Non
Port de l’API: 9000
Documentation de l’API: Activé
Type de base de données: postgres
Version du Scraper de recette: 14.53.0

**Checks**
Site sécurisé: Oui
URL de base côté serveur: Oui
Prêt pour LDAP: Non
E-mail configuré: Oui

### Deployment

Docker (Linux)

### Additional Deployment Details

Not applicable on the demo site

**Comment by Kuchenpirat** [comment]
There is a password reset script inside the container which might help you get access to your account back. 
Take a look at this section in the docs:

https://docs.mealie.io/documentation/getting-started/faq/#how-can-i-change-my-password

**Comment by brunoelgrande** [comment]
> There is a password reset script inside the container which might help you get access to your account back. Take a look at this section in the docs:
> 
> https://docs.mealie.io/documentation/getting-started/faq/#how-can-i-change-my-password

No luck with the script.

**Comment by boc-the-git** [comment]
> > There is a password reset script inside the container which might help you get access to your account back. Take a look at this section in the docs:
> > https://docs.mealie.io/documentation/getting-started/faq/#how-can-i-change-my-password
> 
> No luck with the script.

Can you provide more info on what happened when you ran the script, and then afterwards when trying to login?

**Comment by boc-the-git** [comment]
My pure guesstimate, is that you have multiple users in your database that share either a username or email address, and when trying to login it is matching to both of them. If you're able to query your database, it'd be good to rule that out.

**Comment by brunoelgrande** [comment]
> > > There is a password reset script inside the container which might help you get access to your account back. Take a look at this section in the docs:
> > > https://docs.mealie.io/documentation/getting-started/faq/#how-can-i-change-my-password
> > 
> > 
> > No luck with the script.
> 
> Can you provide more info on what happened when you ran the script, and then afterwards when trying to login?

I can't change by the username in the script, even tough it is 'Bruno'  that I see in the db.
I can change using the email in the python script and I see it changes the hash in the db.
But I still get the error while trying to log in. (An error occur...)

```
root@xxxxxx:/app/mealie/scripts# python change_password.py
Please enter the email of the user you want to reset: Bruno
ERROR: 13-Jan-24 09:29:09 	no user found
root@xxxxxx:/app/mealie/scripts# python change_password.py
Please enter the email of the user you want to reset: email@myemail.com
INFO: 13-Jan-24 09:29:35 	changing password for Bruno
Please enter the new password:
Please enter the new password again:
INFO: 13-Jan-24 09:29:49 	password change successful
press enter to exit
```

**Comment by brunoelgrande** [comment]
> My pure guesstimate, is that you have multiple users in your database that share either a username or email address, and when trying to login it is matching to both of them. If you're able to query your database, it'd be good to rule that out.

I only have 3 users in 2 groups. 

No matching id, username, email, etc..

**Comment by boc-the-git** [comment]
I need to look into this more in future, but based on your stack trace, it is able to identify you as a user - it crashes with the return on line 77 [here](https://github.com/mealie-recipes/mealie/blob/mealie-next/mealie/core/security/security.py#L77), which means you got past all the error conditions above.
I haven't followed it deeper yet..

**Comment by boc-the-git** [comment]
Are there any postgres logs you can pull from the time you experience this?

**Comment by brunoelgrande** [comment]
> Are there any postgres logs you can pull from the time you experience this?

Do I have to activate the level of logging of the Postgress in the docker-compose ?

I see basic logging in the Postgress logs (via Portainer), but not all transactions.

Thanks for your help
