### ISSUE TITLE
Migrate to V1.1 from v.2 stays at in progress

### ISSUE THREAD

**Issue by SmashSE1** [mealie-recipes/mealie#3087]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I've been running Mealie V.2 for a long time, wanted to upgrade to the latest. When I try to do a migration, I follow the migration instructions for pre v1, take a backup and try to migrate. It says in progress, but never progresses. There are only a few dozen recipes. I will attached the backup taken today. Waited at least 20 minutes, and nothing is showing, still says "In Progress".

[2024-Jan-30.zip](https://github.com/mealie-recipes/mealie/files/14105563/2024-Jan-30.zip)

### Steps to Reproduce

1) Go to migrations
2) Select Mealie pre v1
3) upload file
4) Select "tag all recipes with mealie_alpha" (optional, seems to do the same either way)
5) submit

### Please provide relevant logs

INFO:     192.168.x.x:49634 - "POST /api/groups/migrations HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/app/mealie/routes/groups/controller_migrations.py", line 66, in start_data_migration
    return migrator.migrate(f"{migration_type.value.title()} Migration")
  File "/app/mealie/services/migrations/_migration_base.py", line 107, in migrate
    self._migrate()
  File "/app/mealie/services/migrations/mealie_alpha.py", line 68, in _migrate
    recipes = [self._convert_to_new_schema(x) for x in recipes_as_dicts]
  File "/app/mealie/services/migrations/mealie_alpha.py", line 68, in <listcomp>
    recipes = [self._convert_to_new_schema(x) for x in recipes_as_dicts]
  File "/app/mealie/services/migrations/mealie_alpha.py", line 50, in _convert_to_new_schema
    return Recipe(**recipe)
  File "/app/mealie/schema/recipe/recipe.py", line 189, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Recipe
dateAdded

### Mealie Version

Version
v1.1.0
Build
[0800a8d00a9fa154df40040304d46d4900d42e07]

### Deployment

Docker (Linux)

### Additional Deployment Details

Debian Linux 12, new install of Docker and Mealie. Running on ESXI 6.5, 40GB system drive, 4GB ram, 2 CPU

**Comment by hay-kot** [comment]
> I've been running Mealie V.2 for a long time

What does this mean? Which version is the backup from?

**Comment by SmashSE1** [comment]
Version 0.2. The backup is from Version 0.2. It's been a few years, but it worked for me.

**Comment by hay-kot** [comment]
Ahhhh. Gotcha. v0.2.x is _very_ old and isn't supported by the migration code we have. If I recall correctly it even uses Mongo DB instead of SQL. I would say your best bet is to convert your existing backup into the new format. The JSON shouldn't be too difficult to manipulate if you have any sort of programming background.

**Comment by SmashSE1** [comment]
Yes it was Mongo. I have more a coding background than programming, but json shouldn't be too hard. What's the best way to correct it/get the format? Load a recipe and take a backup or is there a document outlining what the new layout would be?

**Comment by Kuchenpirat** [comment]
It would be easiest to use the api I guess. 

You find a reference here https://demo.mealie.io/docs
Or use your own v1 instance and the page `/docs`
