### ISSUE TITLE
[BUG] - Default group is missing after upgrade from 1.2.0 to 1.3.0

### ISSUE THREAD

**Issue by ghuser238490** [mealie-recipes/mealie#3260]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

After upgrading from 1.2.0 to 1.3.0 the default group seems to be missing:
The page https://my.server/admin/manage/groups shows no group entry and
the pages https://my.server/g/home/recipes/timeline 
and https://my.server/group are blank.

After reverting to 1.2.0 the default group shows up again and the timeline page is ok.

### Steps to Reproduce

Upgrade from 1.2.0 to 1.3.0
Access timeline on https://my.server/g/home/recipes/timeline
Look up default group on https://my.server/admin/manage/groups

### Please provide relevant logs

```
INFO:     xxx.xxx.xxx.xxx:0 - "GET /api/groups/self HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 296, in app
    content = await serialize_response(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 160, in serialize_response
    return field.serialize(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/_compat.py", line 147, in serialize
    return self._type_adapter.dump_python(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 331, in dump_python
    return self.serializer.to_python(
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'mealie.db.models.group.webhooks.GroupWebhooksModel'>

```

### Mealie Version

Version
v1.3.0
Build
[e84e5e2910d128911c0c2050a60dfdc205fe277a](https://github.com/mealie-recipes/mealie/commit/e84e5e2910d128911c0c2050a60dfdc205fe277a)

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
I'm unable to replicate this.

The error log you've attached, is that when running v1.3.0? Attempting to load what page exactly?

I note it references webhooks.. in your v1.2.0 instance can you please go to `/admin/manage/groups/` and take a screenshot for me?
I do not have webhooks enabled, and I'm wondering if maybe you do and that's a key difference..

Are you also able to provide a backup file generated from your v1.2.0 instance? From `/admin/backups`

**Comment by hay-kot** [comment]
@boc-the-git, I replicated it on the demo site. If you create a webhook in a group it will cause https://demo.mealie.io/admin/manage/groups/ to fail.

**Comment by hay-kot** [comment]
Looks like the issue is isolated only to that page. No data loss or anything like that, just a validation error.

**Comment by ghuser238490** [comment]
Hi @boc-the-git and @hay-kot , thanks for looking into this. 
I deleted the webhook and everything's working fine again under v1.3.0.

**Comment by boc-the-git** [comment]
Glad that we have a temporary workaround at least.
I expect we'll publish v1.3.1 once we have a solution for this, though exact ETA on that is unknown.

Thanks for getting the demo instance updated @hay-kot 👍
