### ISSUE TITLE
[BUG] - Internal Server Error when changing Authentication Method

### ISSUE THREAD

**Issue by cmintey** [mealie-recipes/mealie#3282]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [x] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Attempting to change a user's Authentication Method in user management fails with a 500 status.

### Steps to Reproduce

1. Login as admin
2. Navigate to user management screen
3. Click on a user **who has favorite recipes**
4. Attempt to change the auth method to something else

### Please provide relevant logs

```
mealie     | INFO:     10.0.2.1:0 - "PUT /api/admin/users/30c18e66-16ba-4248-937b-97dbf79ee078 HTTP/1.1" 500 Internal Server Error
mealie     | ERROR:    Exception in ASGI application
mealie     | Traceback (most recent call last):
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 412, in run_asgi
mealie     |     result = await app(  # type: ignore[func-returns-value]
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
mealie     |     return await self.app(scope, receive, send)
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
mealie     |     await super().__call__(scope, receive, send)
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
mealie     |     await self.middleware_stack(scope, receive, send)
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
mealie     |     raise exc
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
mealie     |     await self.app(scope, receive, _send)
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
mealie     |     await responder(scope, receive, send)
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
mealie     |     await self.app(scope, receive, self.send_with_gzip)
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
mealie     |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
mealie     |     raise exc
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
mealie     |     await app(scope, receive, sender)
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
mealie     |     await self.middleware_stack(scope, receive, send)
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
mealie     |     await route.handle(scope, receive, send)
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
mealie     |     await self.app(scope, receive, send)
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
mealie     |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
mealie     |     raise exc
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
mealie     |     await app(scope, receive, sender)
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
mealie     |     response = await func(request)
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 269, in app
mealie     |     solved_result = await solve_dependencies(
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 626, in solve_dependencies
mealie     |     ) = await request_body_to_args(  # body_params checked above
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 756, in request_body_to_args
mealie     |     v_, errors_ = field.validate(value, values, loc=loc)
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/_compat.py", line 125, in validate
mealie     |     self._type_adapter.validate_python(value, from_attributes=True),
mealie     |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 256, in validate_python
mealie     |     return self.validator.validate_python(__object, strict=strict, from_attributes=from_attributes, context=context)
mealie     |   File "/app/mealie/schema/user/user.py", line 123, in convert_favorite_recipes_to_slugs
mealie     |     return [recipe.slug for recipe in v] if v else v
mealie     |   File "/app/mealie/schema/user/user.py", line 123, in <listcomp>
mealie     |     return [recipe.slug for recipe in v] if v else v
mealie     | AttributeError: 'str' object has no attribute 'slug'
```

### Mealie Version

Nightly (5f6844eceb29a4be2effec5a6acef40c692471eb)

### Deployment

Docker (Linux)

**Comment by cmintey** [comment]
Seems related to #3134

**Comment by cmintey** [comment]
Seems also to only affect users with favorite recipes

**Comment by boc-the-git** [comment]
> Seems also to only affect users with favorite recipes

Interesting conclusion.

Is it possible to replicate on demo now that you know that?

**Comment by cmintey** [comment]
> Is it possible to replicate on demo now that you know that?

~~The demo site doesn't look to be updated yet~~

Yeah I was able to replicate on demo. I created a new user (see `test` user), logged in as that user, favorited a recipe, then went to try to change the auth method and received error.

If I un-favorite the recipe, I am then able to change the auth method

**Comment by michael-genson** [comment]
Thanks for the report! Just opened a PR to fix it
