### ISSUE TITLE
OIDC Failed login

### ISSUE THREAD

**Issue by jimski427** [mealie-recipes/mealie#3320]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I am unable to login with authentik. I can login with un/pw, but not when using OIDC

### Steps to Reproduce

1. click login with authentik at mealie login screen
2. authenticate with authentik successfully
3. screen refreshes back to mealie login screen but doesn't actually login. 

### Please provide relevant logs

```03/15/2024
10:56:41 AM
Traceback (most recent call last):
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 412, in run_asgi
03/15/2024
10:56:41 AM
    result = await app(  # type: ignore[func-returns-value]
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
03/15/2024
10:56:41 AM
    return await self.app(scope, receive, send)
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
03/15/2024
10:56:41 AM
    await super().__call__(scope, receive, send)
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
03/15/2024
10:56:41 AM
    await self.middleware_stack(scope, receive, send)
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
03/15/2024
10:56:41 AM
    raise exc
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
03/15/2024
10:56:41 AM
    await self.app(scope, receive, _send)
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
03/15/2024
10:56:41 AM
    await responder(scope, receive, send)
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
03/15/2024
10:56:41 AM
    await self.app(scope, receive, self.send_with_gzip)
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
03/15/2024
10:56:41 AM
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
03/15/2024
10:56:41 AM
    raise exc
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
03/15/2024
10:56:41 AM
    await app(scope, receive, sender)
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
03/15/2024
10:56:41 AM
    await self.middleware_stack(scope, receive, send)
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
03/15/2024
10:56:41 AM
    await route.handle(scope, receive, send)
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
03/15/2024
10:56:41 AM
    await self.app(scope, receive, send)
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
03/15/2024
10:56:41 AM
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
03/15/2024
10:56:41 AM
    raise exc
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
03/15/2024
10:56:41 AM
    await app(scope, receive, sender)
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
03/15/2024
10:56:41 AM
    response = await func(request)
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
03/15/2024
10:56:41 AM
    raw_response = await run_endpoint_function(
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
03/15/2024
10:56:41 AM
    return await dependant.call(**values)
03/15/2024
10:56:41 AM
  File "/app/mealie/routes/auth/auth.py", line 50, in get_token
03/15/2024
10:56:41 AM
    auth = await auth_provider.authenticate()
03/15/2024
10:56:41 AM
  File "/app/mealie/core/security/providers/openid_provider.py", line 29, in authenticate
03/15/2024
10:56:41 AM
    claims = self.get_claims()
03/15/2024
10:56:41 AM
  File "/app/mealie/core/security/providers/openid_provider.py", line 82, in get_claims
03/15/2024
10:56:41 AM
    jwks = OpenIDProvider.get_jwks()
03/15/2024
10:56:41 AM
  File "/app/mealie/core/security/providers/openid_provider.py", line 127, in get_jwks
03/15/2024
10:56:41 AM
    return JsonWebKey.import_key_set(response.json())
03/15/2024
10:56:41 AM
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/authlib/jose/rfc7517/jwk.py", line 55, in import_key_set
03/15/2024
10:56:41 AM
    raise ValueError('Invalid key set format')
03/15/2024
10:56:41 AM
ValueError: Invalid key set format```


### Mealie Version

[1af0f426ae7ed19668059929cbe18d4b479f5d75](https://github.com/mealie-recipes/mealie/commit/1af0f426ae7ed19668059929cbe18d4b479f5d75)

### Deployment

Unraid

### Additional Deployment Details

_No response_

**Comment by jimski427** [comment]
disregard, i have a smooth brain. thanks to cmintey for dealing with me on discord!

**Comment by McGeaverBeaver** [comment]
Dude, @jimski427  please post the fix and not " I have a smooth brain " .. This is not helpful. thank you. 

The fix in my case was I missed selecting the cert for the signing key.

**Comment by jimski427** [comment]
That wasn't the fix for me. Mine was a typo. So it wouldn't have helped you either way.

**Comment by tekjoey** [comment]
+1 for @McGeaverBeaver's solution. In the provider settings, ensure something is selected for Signing Key. I created a cert specifically for mealie, but I think the default authentik one would work as well.

**Comment by Eamourinho** [comment]
I just want to add to this for anyone having this problem in the future, I had to generate a ECDSA certificate not an RSA certificate (and therefore the default Authentik one doesn't work)
