### ISSUE TITLE
[BUG] Migration from build bdf6b1054ece531276c62ca7d4f0ee718bfd2efb to latest fails

### ISSUE THREAD

**Issue by timdonovanuk** [mealie-recipes/mealie#3466]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I have an older version of Mealie based on nightly builds. The version is https://github.com/hay-kot/mealie/commit/bdf6b1054ece531276c62ca7d4f0ee718bfd2efb

I can no longer seem to get this up and running (no helpful error in the logs, just):

```
mealie  |  ERROR  connect ECONNREFUSED ::1:3000
mealie  |   at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1481:16)
```

However when I did have it running, I managed to use the export/backup functionality to produce a zipfile with database.json etc in. 

When I try using the /group/migrations tool, it just shows "Failed".

I do notice that in my zip, it is not the same structure as shown here:

![image](https://github.com/mealie-recipes/mealie/assets/8156439/600777e3-c5c8-4bd5-9769-5af524923961)

My zip structure is this:

![image](https://github.com/mealie-recipes/mealie/assets/8156439/c6050151-6ded-42af-b479-85dcf402541b)

### Steps to Reproduce

As above. 

### Please provide relevant logs

I wish I had something helpful from the logs to show. There is nothing.

![image](https://github.com/mealie-recipes/mealie/assets/8156439/8e35c6d3-4144-4c13-b7b6-23c5902ebade)

### Deployment

Docker (Linux)

### Additional Deployment Details

Using external postgres. The database is clean for new mealie version.

**Comment by michael-genson** [comment]
The backup from that version should be used in the backups section, not the migrations section. Migrations are for other applications.

Try restoring the backup from the backups page and see what happens.

**Comment by timdonovanuk** [comment]
Ah thank you! So I did the import of the backup. Now I cannot log in (using my old credentials or changeme@example.com). 

The error is:

`sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column groups.slug does not exist`

If I restart the instance, I can see it doing an upgrade:

```
mealie  | INFO: 15-Apr-24 15:07:32      Database connection established.
mealie  | INFO: 15-Apr-24 15:07:32      Context impl PostgresqlImpl.
mealie  | INFO: 15-Apr-24 15:07:32      Will assume transactional DDL.
mealie  | INFO: 15-Apr-24 15:07:32      Migration needed. Performing migration...
mealie  | INFO: 15-Apr-24 15:07:32      Context impl PostgresqlImpl.
mealie  | INFO: 15-Apr-24 15:07:32      Will assume transactional DDL.
mealie  | INFO: 15-Apr-24 15:07:32      Running upgrade b3dbb554ba53 -> 04ac51cbe9a4, added group slug
mealie  | INFO: 15-Apr-24 15:07:32      Running upgrade 04ac51cbe9a4 -> 1825b5225403, added recipe note to shopping list recipe ref
mealie  | INFO: 15-Apr-24 15:07:32      Running upgrade 1825b5225403 -> bcfdad6b7355, remove tool name and slug unique contraints
mealie  | INFO: 15-Apr-24 15:07:32      Running upgrade bcfdad6b7355 -> 0341b154f79a, added normalized unit and food names
mealie  | INFO: 15-Apr-24 15:07:32      Running upgrade 0341b154f79a -> dded3119c1fe, added unique constraints
mealie  | INFO: 15-Apr-24 15:07:32      Running upgrade dded3119c1fe -> ba1e4a6cfe99, added plural names and alias tables for foods and units
mealie  | INFO: 15-Apr-24 15:07:32      Running upgrade ba1e4a6cfe99 -> 2298bb460ffd, added user to shopping list
mealie  | INFO: 15-Apr-24 15:07:32      Running upgrade 2298bb460ffd -> 09aba125b57a, add OIDC auth method
mealie  | INFO: 15-Apr-24 15:07:32      Checking for migration data fixes
mealie  | INFO: 15-Apr-24 15:07:32      Database contains no users, initializing...
mealie  | INFO: 15-Apr-24 15:07:32      Generating Default Group
mealie  | INFO: 15-Apr-24 15:07:33      Generating Default User
mealie  | INFO: 15-Apr-24 15:07:33      end: database initialization
mealie  | INFO: 15-Apr-24 15:07:33      -----SYSTEM STARTUP-----

```

However, when I log in using changeme, there is nothing there.

Thank you for the help!

**Comment by timdonovanuk** [comment]
I've switched to the nightly build, spotted another error when I run the backup restore:

```
mealie  | INFO: 15-Apr-24 15:23:32      initializing backup restore
mealie  | INFO: 15-Apr-24 15:23:32      dropping all database tables
mealie  | INFO: 15-Apr-24 15:23:32      importing database tables
mealie  | INFO: 15-Apr-24 15:23:32      Context impl PostgresqlImpl.
mealie  | INFO: 15-Apr-24 15:23:32      Will assume transactional DDL.
mealie  | INFO: 15-Apr-24 15:23:32      Running upgrade  -> 6b0f5f32d602, Initial tables
mealie  | INFO: 15-Apr-24 15:23:33      Running upgrade 6b0f5f32d602 -> 263dd6707191, convert quantity from integer to float
mealie  | INFO: 15-Apr-24 15:23:33      Running upgrade 263dd6707191 -> f1a2dbee5fe9, Add original_text column to recipes_ingredients
mealie  | INFO: 15-Apr-24 15:23:33      Running upgrade f1a2dbee5fe9 -> 59eb59135381, add tags to cookbooks
mealie  | INFO: 15-Apr-24 15:23:33      Running upgrade 59eb59135381 -> 09dfc897ad62, add require_all for cookbook filters
mealie  | INFO: 15-Apr-24 15:23:33      Running upgrade 09dfc897ad62 -> ab0bae02578f, Add use_abbreviation column to ingredients
mealie  | INFO: 15-Apr-24 15:23:33      Running upgrade ab0bae02578f -> f30cf048c228, add new webhook fields
mealie  | INFO: 15-Apr-24 15:23:33      Running upgrade f30cf048c228 -> 188374910655, add login_attemps and locked_at field to user table
mealie  | INFO: 15-Apr-24 15:23:33      Running upgrade 188374910655 -> 089bfa50d0ed, Add is_ocr_recipe column to recipes
mealie  | INFO: 15-Apr-24 15:23:33      Running upgrade 089bfa50d0ed -> 44e8d670719d, add extras to shopping lists, list items, and ingredient foods
mealie  | INFO: 15-Apr-24 15:23:33      Running upgrade 44e8d670719d -> 2ea7a807915c, add recipe_timeline_events table
mealie  | INFO: 15-Apr-24 15:23:33      Running upgrade 2ea7a807915c -> 1923519381ad, added recipe last made timestamp
mealie  | INFO: 15-Apr-24 15:23:33      Running upgrade 1923519381ad -> 167eb69066ad, add recipe_scale to shopping list item ref
mealie  | INFO: 15-Apr-24 15:23:33      Running upgrade 167eb69066ad -> 165d943c64ee, add related user to mealplan
mealie  | INFO: 15-Apr-24 15:23:33      Running upgrade 165d943c64ee -> ff5f73b01a7a, add missing foreign key and order indices
mealie  | INFO: 15-Apr-24 15:23:33      Running upgrade ff5f73b01a7a -> 16160bf731a0, add more indices necessary for search
mealie  | INFO: 15-Apr-24 15:23:33      Running upgrade 16160bf731a0 -> 5ab195a474eb, add normalized search properties
mealie  | INFO: 15-Apr-24 15:23:33      Running upgrade 5ab195a474eb -> b04a08da2108, added shopping list label settings
mealie  | INFO: 15-Apr-24 15:23:33      Running upgrade b04a08da2108 -> 38514b39a824, add auth_method to user table
mealie  | INFO: 15-Apr-24 15:23:33      Running upgrade 38514b39a824 -> b3dbb554ba53, postgres fuzzy search
mealie  | ERROR: 15-Apr-24 15:23:33     'ascii' codec can't encode character '\u2013' in position 72: ordinal not in range(128)
mealie  | Traceback (most recent call last):
mealie  |   File "/app/mealie/routes/admin/admin_backups.py", line 105, in import_one
mealie  |     backup.restore(file)
mealie  |   File "/app/mealie/services/backups_v2/backup_v2.py", line 101, in restore
mealie  |     self.db_exporter.restore(database_json)
mealie  |   File "/app/mealie/services/backups_v2/alchemy_exporter.py", line 173, in restore
mealie  |     connection.execute(insert(table), rows)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
mealie  |     return meth(
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
mealie  |     return connection._execute_clauseelement(
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
mealie  |     ret = self._execute_context(
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
mealie  |     return self._exec_insertmany_context(dialect, context)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2128, in _exec_insertmany_context
mealie  |     self._handle_dbapi_exception(
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2360, in _handle_dbapi_exception
mealie  |     raise exc_info[1].with_traceback(exc_info[2])
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2120, in _exec_insertmany_context
mealie  |     dialect.do_execute(
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
mealie  |     cursor.execute(statement, parameters)
mealie  | UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 72: ordinal not in range(128)
```

**Comment by timdonovanuk** [comment]
Solved! Not sure why, but when I cleaned out my mealie database it reverted to ascii not utf8. Fixed that and the migration ran. Thank you @michael-genson
