### ISSUE TITLE
[BUG] - Changing Timezone in docker-compose.yml results in error

### ISSUE THREAD

**Issue by Burschi500** [mealie-recipes/mealie#3584]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When using the "ready to use" docker-compose.yml from https://docs.mealie.io/documentation/getting-started/installation/sqlite/ with 1.6.0 changing the TZ value will result in an error. Any TZ will break starting the container.

Furthermore the "ready to use" snippet is just that - a snippet, there are some things missing, at least for me.

### Steps to Reproduce

1) use docker-compose.yml from source above
2) change the TZ to any value different to "America/Anchorage"
3) see log below

### Please provide relevant logs

Recreating df6aa3946f99_mealie ... 

ERROR: for df6aa3946f99_mealie  'ContainerConfig'

ERROR: for mealie  'ContainerConfig'
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 203, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1186, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1166, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 697, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 679, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 579, in execute_convergence_plan
    return self._execute_convergence_recreate(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 499, in _execute_convergence_recreate
    containers, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 494, in recreate
    return self.recreate_container(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 612, in recreate_container
    new_container = self.create_container(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 330, in create_container
    container_options = self._get_container_create_options(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 921, in _get_container_create_options
    container_options, override_options = self._build_container_volume_options(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 960, in _build_container_volume_options
    binds, affinity = merge_volume_bindings(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1548, in merge_volume_bindings
    old_volumes, old_mounts = get_container_data_volumes(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1579, in get_container_data_volumes
    container.image_config['ContainerConfig'].get('Volumes') or {}
KeyError: 'ContainerConfig'

### Mealie Version

Build 418a8ec72bead3f625827846aafd644c851a4fcc 
image: ghcr.io/mealie-recipes/mealie:v1.6.0 #

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
This looks like an error with docker compose and not with Mealie. The ‘docker-compose’ command is old/deprecated. You may need to upgrade to the ‘docker compose’ command instead. 

Also, the example in the docs should work as is, so if you upgrade and are still having issues please post a reproducible example and your docker and compose versions.

**Comment by Burschi500** [comment]
Yes. With using docker compose everything is fine - sorry for inconvenience!
