### ISSUE TITLE
[BUG] - OpenAI - Error when using Ollama with no API Key

### ISSUE THREAD

**Issue by greirson** [mealie-recipes/mealie#3649]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

With OPENAI_BASE_URL set to http://ollama_url/v1 and OPENAI_API_KEY left blank, as it by default does not need authentication, the parser errors with a `ValueError: OpenAI is not enabled`. The error is mitigate and the parser works as expected when any string of text is included for the key. i.e. `OPENAI_API_KEY=allyourbasearebelongtous`

### Steps to Reproduce

1. Set env variables to
```
OPENAI_BASE_URL=http://ollama_url/v1
OPENAI_API_KEY=
OPENAI_MODEL=llama3:latest
OPENAI_SEND_DATABASE_DATA=false
OPENAI_WORKERS=2
```
2. Parse something under /admin/parser with OpenAI selected

### Please provide relevant logs

```
2024-05-25T20:40:53.446132480Z ERROR    2024-05-25T13:40:53 - Exception in ASGI application
2024-05-25T20:40:53.446146072Z Traceback (most recent call last):
2024-05-25T20:40:53.446148917Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
2024-05-25T20:40:53.446151442Z     result = await app(  # type: ignore[func-returns-value]
2024-05-25T20:40:53.446153731Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
2024-05-25T20:40:53.446156112Z     return await self.app(scope, receive, send)
2024-05-25T20:40:53.446158334Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2024-05-25T20:40:53.446160607Z     await super().__call__(scope, receive, send)
2024-05-25T20:40:53.446162748Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
2024-05-25T20:40:53.446164913Z     await self.middleware_stack(scope, receive, send)
2024-05-25T20:40:53.446167013Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-05-25T20:40:53.446169243Z     raise exc
2024-05-25T20:40:53.446171328Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-05-25T20:40:53.446173547Z     await self.app(scope, receive, _send)
2024-05-25T20:40:53.446175617Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
2024-05-25T20:40:53.446183619Z     await responder(scope, receive, send)
2024-05-25T20:40:53.446185824Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
2024-05-25T20:40:53.446188050Z     await self.app(scope, receive, self.send_with_gzip)
2024-05-25T20:40:53.446190142Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-05-25T20:40:53.446192325Z     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-05-25T20:40:53.446194424Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-05-25T20:40:53.446196667Z     raise exc
2024-05-25T20:40:53.446198721Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-05-25T20:40:53.446200853Z     await app(scope, receive, sender)
2024-05-25T20:40:53.446202917Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
2024-05-25T20:40:53.446205050Z     await self.middleware_stack(scope, receive, send)
2024-05-25T20:40:53.446207574Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
2024-05-25T20:40:53.446209887Z     await route.handle(scope, receive, send)
2024-05-25T20:40:53.446212010Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
2024-05-25T20:40:53.446214324Z     await self.app(scope, receive, send)
2024-05-25T20:40:53.446216448Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
2024-05-25T20:40:53.446218626Z     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-05-25T20:40:53.446221195Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-05-25T20:40:53.446223489Z     raise exc
2024-05-25T20:40:53.446225511Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-05-25T20:40:53.446227673Z     await app(scope, receive, sender)
2024-05-25T20:40:53.446229713Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
2024-05-25T20:40:53.446231850Z     response = await func(request)
2024-05-25T20:40:53.446233973Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
2024-05-25T20:40:53.446236139Z     raw_response = await run_endpoint_function(
2024-05-25T20:40:53.446238231Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-05-25T20:40:53.446240392Z     return await dependant.call(**values)
2024-05-25T20:40:53.446242609Z   File "/app/mealie/routes/parser/ingredient_parser.py", line 21, in parse_ingredient
2024-05-25T20:40:53.446246596Z     response = await parser.parse([ingredient.ingredient])
2024-05-25T20:40:53.446248853Z   File "/app/mealie/services/parser_services/openai/parser.py", line 121, in parse
2024-05-25T20:40:53.446250997Z     response = await self._parse(ingredients)
2024-05-25T20:40:53.446253121Z   File "/app/mealie/services/parser_services/openai/parser.py", line 94, in _parse
2024-05-25T20:40:53.446255339Z     service = OpenAIService()
2024-05-25T20:40:53.446257431Z   File "/app/mealie/services/openai/openai.py", line 48, in __init__
2024-05-25T20:40:53.446259584Z     raise ValueError("OpenAI is not enabled")
2024-05-25T20:40:53.446261707Z ValueError: OpenAI is not enabled
2024-05-25T20:40:53.446860121Z ERROR    2024-05-25T13:40:53 - Exception in ASGI application
2024-05-25T20:40:53.446867956Z Traceback (most recent call last):
2024-05-25T20:40:53.446870639Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
2024-05-25T20:40:53.446876738Z     result = await app(  # type: ignore[func-returns-value]
2024-05-25T20:40:53.446879460Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
2024-05-25T20:40:53.446881747Z     return await self.app(scope, receive, send)
2024-05-25T20:40:53.446883949Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2024-05-25T20:40:53.446886265Z     await super().__call__(scope, receive, send)
2024-05-25T20:40:53.446888453Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
2024-05-25T20:40:53.446890671Z     await self.middleware_stack(scope, receive, send)
2024-05-25T20:40:53.446892820Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-05-25T20:40:53.446895210Z     raise exc
2024-05-25T20:40:53.446897378Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-05-25T20:40:53.446899673Z     await self.app(scope, receive, _send)
2024-05-25T20:40:53.446901803Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
2024-05-25T20:40:53.446904083Z     await responder(scope, receive, send)
2024-05-25T20:40:53.446906252Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
2024-05-25T20:40:53.446908553Z     await self.app(scope, receive, self.send_with_gzip)
2024-05-25T20:40:53.446910703Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-05-25T20:40:53.446912951Z     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-05-25T20:40:53.446915118Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-05-25T20:40:53.446921320Z     raise exc
2024-05-25T20:40:53.446923567Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-05-25T20:40:53.446925819Z     await app(scope, receive, sender)
2024-05-25T20:40:53.446927932Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
2024-05-25T20:40:53.446930143Z     await self.middleware_stack(scope, receive, send)
2024-05-25T20:40:53.446932734Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
2024-05-25T20:40:53.446935059Z     await route.handle(scope, receive, send)
2024-05-25T20:40:53.446937253Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
2024-05-25T20:40:53.446939527Z     await self.app(scope, receive, send)
2024-05-25T20:40:53.446941685Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
2024-05-25T20:40:53.446944005Z     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-05-25T20:40:53.446946188Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-05-25T20:40:53.446948431Z     raise exc
2024-05-25T20:40:53.446950568Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-05-25T20:40:53.446952821Z     await app(scope, receive, sender)
2024-05-25T20:40:53.446955008Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
2024-05-25T20:40:53.446958630Z     response = await func(request)
2024-05-25T20:40:53.446960892Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
2024-05-25T20:40:53.446963217Z     raw_response = await run_endpoint_function(
2024-05-25T20:40:53.446965367Z   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-05-25T20:40:53.446967664Z     return await dependant.call(**values)
2024-05-25T20:40:53.446969907Z   File "/app/mealie/routes/parser/ingredient_parser.py", line 21, in parse_ingredient
2024-05-25T20:40:53.446972196Z     response = await parser.parse([ingredient.ingredient])
2024-05-25T20:40:53.446974384Z   File "/app/mealie/services/parser_services/openai/parser.py", line 121, in parse
2024-05-25T20:40:53.446976663Z     response = await self._parse(ingredients)
2024-05-25T20:40:53.446978853Z   File "/app/mealie/services/parser_services/openai/parser.py", line 94, in _parse
2024-05-25T20:40:53.446981279Z     service = OpenAIService()
2024-05-25T20:40:53.446983417Z   File "/app/mealie/services/openai/openai.py", line 48, in __init__
2024-05-25T20:40:53.446985610Z     raise ValueError("OpenAI is not enabled")
2024-05-25T20:40:53.446989503Z ValueError: OpenAI is not enabled
```

### Mealie Version

1.7.0

### Deployment

Docker (Linux)

**Comment by greirson** [comment]
My 2¢, the OpenAI feature should require `OPENAI_BASE_URL` and `OPENAI_MODEL`, and throw an error in /admin/site-settings if `^.*openai.*$` is in `OPENAI_BASE_URL` and `OPENAI_API_KEY` is blank

**Comment by michael-genson** [comment]
The Ollama docs explicitly specify to supply an API key even though it's unused: https://ollama.com/blog/openai-compatibility

Additionally, I don't think it makes sense to require the base URL when most users are going to want to use OpenAI out of the box. It also wouldn't help anyway since an API key is still required (even if it doesn't get used)

**Comment by greirson** [comment]
Ah thanks @michael-genson, I very much missed the "# required, but unused" for the Python library

**Comment by greirson** [comment]
For anyone looking here for troubleshooting in the future, your env variables for ollama should include:
```yaml
OPENAI_BASE_URL=http://ollama_url/v1
OPENAI_API_KEY=literallyanything
OPENAI_MODEL=llama3:latest # or whatever model, I'm using phi3:latest
```

**Comment by boc-the-git** [comment]
Let us know how performance goes too please @Greirson, once you've used it a bit. Either here or on discord 😊
