### ISSUE TITLE
[BUG] Error when scraping any recipe - NixOs

### ISSUE THREAD

**Issue by poperigby** [mealie-recipes/mealie#4061]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Whenever I try to import a recipe, I get an error:

```
TypeError: AbstractScraper.__init__() got an unexpected keyword argument 'supported_only'
```

### Steps to Reproduce

1. Click Create->Import
2. Paste any recipe URL 
3. Click Create

### Please provide relevant logs

```
TypeError: AbstractScraper.__init__() got an unexpected keyword argument 'supported_only'
ERROR    2024-08-20T19:37:24 - Exception in ASGI application
Traceback (most recent call last):
  File "/nix/store/qwf3m36is6slskm2iqhqi9h3hwnqvvqf-python3.12-uvicorn-0.29.0/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qwf3m36is6slskm2iqhqi9h3hwnqvvqf-python3.12-uvicorn-0.29.0/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/j2pb83hxqmpqzfs1mzqprnx2gi2xsn0s-python3.12-fastapi-0.111.0/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/nix/store/lx1iy3j5fay5hsjch4l7kvj2xqfgskbq-python3.12-starlette-0.37.2/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/nix/store/lx1iy3j5fay5hsjch4l7kvj2xqfgskbq-python3.12-starlette-0.37.2/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/nix/store/lx1iy3j5fay5hsjch4l7kvj2xqfgskbq-python3.12-starlette-0.37.2/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/nix/store/lx1iy3j5fay5hsjch4l7kvj2xqfgskbq-python3.12-starlette-0.37.2/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/nix/store/lx1iy3j5fay5hsjch4l7kvj2xqfgskbq-python3.12-starlette-0.37.2/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/nix/store/lx1iy3j5fay5hsjch4l7kvj2xqfgskbq-python3.12-starlette-0.37.2/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/nix/store/lx1iy3j5fay5hsjch4l7kvj2xqfgskbq-python3.12-starlette-0.37.2/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/nix/store/lx1iy3j5fay5hsjch4l7kvj2xqfgskbq-python3.12-starlette-0.37.2/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/nix/store/lx1iy3j5fay5hsjch4l7kvj2xqfgskbq-python3.12-starlette-0.37.2/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/nix/store/lx1iy3j5fay5hsjch4l7kvj2xqfgskbq-python3.12-starlette-0.37.2/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/nix/store/lx1iy3j5fay5hsjch4l7kvj2xqfgskbq-python3.12-starlette-0.37.2/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/nix/store/lx1iy3j5fay5hsjch4l7kvj2xqfgskbq-python3.12-starlette-0.37.2/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/nix/store/lx1iy3j5fay5hsjch4l7kvj2xqfgskbq-python3.12-starlette-0.37.2/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/nix/store/lx1iy3j5fay5hsjch4l7kvj2xqfgskbq-python3.12-starlette-0.37.2/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/nix/store/lx1iy3j5fay5hsjch4l7kvj2xqfgskbq-python3.12-starlette-0.37.2/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/zaxm3xm1zaq2h9365a0bribkp7mgn7f6-mealie-1.11.0/lib/python3.12/site-packages/mealie/routes/_base/routers.py", line 35, in custom_route_handler
    response = await original_route_handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/j2pb83hxqmpqzfs1mzqprnx2gi2xsn0s-python3.12-fastapi-0.111.0/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/j2pb83hxqmpqzfs1mzqprnx2gi2xsn0s-python3.12-fastapi-0.111.0/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/zaxm3xm1zaq2h9365a0bribkp7mgn7f6-mealie-1.11.0/lib/python3.12/site-packages/mealie/routes/recipe/recipe_crud_routes.py", line 203, in parse_recipe_url
    recipe, extras = await create_from_url(req.url, self.translator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/zaxm3xm1zaq2h9365a0bribkp7mgn7f6-mealie-1.11.0/lib/python3.12/site-packages/mealie/services/scraper/scraper.py", line 34, in create_from_url
    new_recipe, extras = await scraper.scrape(url)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/zaxm3xm1zaq2h9365a0bribkp7mgn7f6-mealie-1.11.0/lib/python3.12/site-packages/mealie/services/scraper/recipe_scraper.py", line 43, in scrape
    result = await scraper.parse()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/zaxm3xm1zaq2h9365a0bribkp7mgn7f6-mealie-1.11.0/lib/python3.12/site-packages/mealie/services/scraper/scraper_strategies.py", line 233, in parse
    scraped_data = await self.scrape_url()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/zaxm3xm1zaq2h9365a0bribkp7mgn7f6-mealie-1.11.0/lib/python3.12/site-packages/mealie/services/scraper/scraper_strategies.py", line 204, in scrape_url
    scraped_schema = scrape_html(recipe_html, org_url=self.url, supported_only=False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/jwn7189wv1wljssi6lr6fjxaqr0byhv5-python3.12-recipe-scrapers-14.56.0/lib/python3.12/site-packages/recipe_scrapers/__init__.py", line 721, in scrape_html
    wild_scraper = SchemaScraperFactory.generate(url=org_url, html=html, **options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/jwn7189wv1wljssi6lr6fjxaqr0byhv5-python3.12-recipe-scrapers-14.56.0/lib/python3.12/site-packages/recipe_scrapers/_factory.py", line 52, in generate
    return cls.SchemaScraper(url, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AbstractScraper.__init__() got an unexpected keyword argument 'supported_only'
```

### Mealie Version

1.11.0 from nixpkgs

### Deployment

Other (please specify below)

### Additional Deployment Details

NixOS

**Comment by Kuchenpirat** [comment]
If the Mealie version on Nix does match the mealie version we are using here than the spcraper version is out of date. For the v1.11.0 release we upgraded to v15. In your logs it shows recipe-scrapers-14.56.0. 

The NixOs mealie package is not supported by us and i have never used NixOs so i have now idea how the whole thing works, but it seems that there is some dependency missalignment.

**Comment by xamino** [comment]
I assume this would be solved by https://github.com/NixOS/nixpkgs/issues/336416 then.

**Comment by Kuchenpirat** [comment]
It might. 
As said i have no idea how nix works and i am a bit confused to why they would not use the dependecies specified here.

**Comment by Kuchenpirat** [comment]
i think the relevant PR would be this one: 
- https://github.com/NixOS/nixpkgs/pull/332206. 

I will go ahead and close this as the nixOS image is not supported by us and the problem should be fixed when the PR above is merged.

**Comment by ambroisie** [comment]
@xamino could you please open such issues on the NixOS-side first in the future, to avoid burdening downstream with packaging issues.

**Comment by xamino** [comment]
Absolutely, but I didn't open this, just found it here first and commented for reference.

**Comment by ambroisie** [comment]
Oops sorry, I should have pinged @poperigby, my bad.

**Comment by poperigby** [comment]
Sorry about that.
