### ISSUE TITLE
[BUG] - log level trace does not exist

### ISSUE THREAD

**Issue by atxbyea** [mealie-recipes/mealie#4110]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

tried setting loglevel to trace, failed miserably

### Steps to Reproduce

set LOG_LEVEL: trace per documentation

### Please provide relevant logs

`Switching to dedicated user

        User uid:    1000
        User gid:    1000
        
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/logging/config.py", line 565, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/local/lib/python3.10/logging/config.py", line 759, in configure_handler
    result.setLevel(logging._checkLevel(level))
  File "/usr/local/lib/python3.10/logging/__init__.py", line 198, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'TRACE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/mealie/main.py", line 3, in <module>
    from mealie.app import settings
  File "/app/mealie/app.py", line 13, in <module>
    from mealie.routes import router, spa, utility_routes
  File "/app/mealie/routes/__init__.py", line 3, in <module>
    from . import (
  File "/app/mealie/routes/admin/__init__.py", line 1, in <module>
    from mealie.routes._base.routers import AdminAPIRouter
  File "/app/mealie/routes/_base/__init__.py", line 1, in <module>
    from .base_controllers import *
  File "/app/mealie/routes/_base/base_controllers.py", line 9, in <module>
    from mealie.core.dependencies.dependencies import get_admin_user, get_current_user, get_integration_id, get_public_group
  File "/app/mealie/core/dependencies/__init__.py", line 1, in <module>
    from .dependencies import *
  File "/app/mealie/core/dependencies/dependencies.py", line 17, in <module>
    from mealie.db.db_setup import generate_session
  File "/app/mealie/db/db_setup.py", line 10, in <module>
    settings = get_app_settings()
  File "/app/mealie/core/config.py", line 43, in get_app_settings
    return app_settings_constructor(env_file=ENV, production=PRODUCTION, data_dir=determine_data_dir())
  File "/app/mealie/core/settings/settings.py", line 356, in app_settings_constructor
    _secrets_dir=get_secrets_dir(),  # type: ignore
  File "/app/mealie/core/settings/settings.py", line 47, in get_secrets_dir
    logger = get_logger()
  File "/app/mealie/core/root_logger.py", line 37, in get_logger
    __root_logger = configured_logger(
  File "/app/mealie/core/logger/config.py", line 66, in configured_logger
    logging_config.dictConfig(config=__conf)
  File "/usr/local/lib/python3.10/logging/config.py", line 811, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/lib/python3.10/logging/config.py", line 572, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'access'
`

### Mealie Version

1.12

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
`trace` is not a valid logging level, https://docs.python.org/3.10/library/logging.html#levels

**Comment by besque** [comment]
Hey, since ```trace``` is not a valid logging level, I have removed it from the list of logging levels from the documentation, please review my PR and merge it, Thank you!
