### ISSUE TITLE
[BUG] - Recipes not showing after upgrade

### ISSUE THREAD

**Issue by rafaelmathieu** [mealie-recipes/mealie#4294]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I recently updated the nightly for the first time in a while. (Last time I updated it, open AI was not a thing)

After the update I cannot see or search for any recipes. I know they are there as I can access them via their direct URL and they are in the DB.

There seem to be an error showing in the logs when the main page is loaded. (URL/g/home)

### Steps to Reproduce

I have not been able to reproduce the issue on the demo site.

### Please provide relevant logs

ERROR    2024-09-30T12:51:15 - **Exception in ASGI application**
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/app/mealie/routes/_base/routers.py", line 35, in custom_route_handler
    response = await original_route_handler(request)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/app/mealie/routes/recipe/recipe_crud_routes.py", line 362, in get_all
    pagination_response = self.group_recipes.by_user(self.user.id).page_all(
  File "/app/mealie/repos/repository_recipes.py", line 222, in page_all
    items = [RecipeSummary.model_validate(item) for item in data]
  File "/app/mealie/repos/repository_recipes.py", line 222, in <listcomp>
    items = [RecipeSummary.model_validate(item) for item in data]
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/pydantic/main.py", line 596, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: **1 validation error for RecipeSummary**
household_id
  UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/uuid_type

### Mealie Version

Docker Version: ghcr.io/mealie-recipes/mealie:nightly
Build Tag: 1bd3d38dfc76ac81c5ebd9710d79486f2d61ab15

Using OIDC

<img width="596" alt="image" src="https://github.com/user-attachments/assets/ab85605c-2a31-429c-8415-792378acf200">

### Deployment

Unraid

**Comment by michael-genson** [comment]
Do you have logs from when you upgraded? Looks like something might have gone wrong with the migration. Can you provide a backup here from before the upgrade?

Also, if you could edit the title on the bug report

**Comment by rafaelmathieu** [comment]
Updated the title.

I do not have any upgrade logs anymore :(.

The only other log error I could find is this:

`[ERROR|scheduler_service|L60] 2024-09-30T13:37:52: Error in scheduled task func='locked_user_reset': exception='group_id must be set'`

I do a backup from april but this is kinda old.

**Comment by michael-genson** [comment]
If you could provide that, it may be helpful

**Comment by michael-genson** [comment]
Also, are you using sqlite or postgres?

**Comment by brandonjkessler** [comment]
I'm having the same issue. The Shopping List feature is also not working

OS: UnRAID 6.12.13
Channel: ghcr.io/mealie-recipes/mealie:nightly
Build: [fa32a6489c35d62eec976e24af14cd179d0bf279](https://github.com/mealie-recipes/mealie/commit/fa32a6489c35d62eec976e24af14cd179d0bf279)
DB engine: SQLite

Attached is my log output from UnRAID for that container

[mealie_error.txt](https://github.com/user-attachments/files/17217473/mealie_error.txt)

**Comment by michael-genson** [comment]
Can you provide the logs from when you upgraded to nightly, and a copy of your backup from before you upgraded?

**Comment by brandonjkessler** [comment]
I don't have any upgrade logs, and my backup is from almost a year ago, but if that will be beneficial I can get you that. Thanks for the effort and sorry I don't have anything more substantial for you to work with.

**Comment by michael-genson** [comment]
That backup would be helpful if you're able to provide! Along with your actual db file if possible

**Comment by rafaelmathieu** [comment]
@michael-genson  I am using postgres.

is there a way to send you the backup directly as putting the backup with user data in the open is not great.

**Comment by michael-genson** [comment]
If you could DM it to me on Discord that will work. In case you're not on the Discord:
https://discord.gg/nvmfQyzn

**Comment by michael-genson** [comment]
After taking a look at the data, it looks like this is related to this: https://github.com/mealie-recipes/mealie/issues/3171 (and this: https://github.com/mealie-recipes/mealie/issues/3219)

Basically, if a recipe exists and its `user_id` doesn't match a real user, we can't find the recipe's `household_id` so we error out. The intermittent fix is to manually edit your data and make sure all recipes point to a valid user.

**Comment by rafaelmathieu** [comment]
Thanks. was able to fix it via DB edit.

**Comment by michael-genson** [comment]
Glad to hear! I've got a PR open to fix this automatically in the future: https://github.com/mealie-recipes/mealie/pull/4325

**Comment by Mladia** [comment]
I am still getting this error while trying to open the overview (default page), after deleting a user.

```
ERROR    2025-05-22T06:47:25 - Exception in ASGI application
Traceback (most recent call last):
  File "/opt/mealie/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mealie/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mealie/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/mealie/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/mealie/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/opt/mealie/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/opt/mealie/lib/python3.12/site-packages/starlette/middleware/sessions.py", line 85, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/opt/mealie/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 22, in __call__
    await self.app(scope, receive, send)
  File "/opt/mealie/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/mealie/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/opt/mealie/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/mealie/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/mealie/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/opt/mealie/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/opt/mealie/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/mealie/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/opt/mealie/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/mealie/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/opt/mealie/lib/python3.12/site-packages/mealie/routes/_base/routers.py", line 35, in custom_route_handler
    response = await original_route_handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mealie/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mealie/lib/python3.12/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mealie/lib/python3.12/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mealie/lib/python3.12/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mealie/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/opt/mealie/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mealie/lib/python3.12/site-packages/mealie/routes/recipe/recipe_crud_routes.py", line 259, in get_all
    pagination_response = self.group_recipes.by_user(self.user.id).page_all(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mealie/lib/python3.12/site-packages/mealie/repos/repository_recipes.py", line 261, in page_all
    items = [RecipeSummary.model_validate(item) for item in data]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mealie/lib/python3.12/site-packages/pydantic/main.py", line 627, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for RecipeSummary
household_id
```

There was one recipe added by this user, probably it didn't get reassigned properly. How could I edit the databse or is there some other manual way to mend the problem?

**Comment by MyriadRising** [comment]
I am not 100% sure this is the same issue, but I was having a problem where on my main page none of my recipes would show.
I could see them in the 'manage data' section of the site, I could search for them, and I could see them in the timeline. but they wouldn't show in my cookbook or on the main page (unless you were signed out).

What I found was that a user had added a recipe but later the user was deleted.
This extra (floating) recipe had no owner and wouldn't show under any view within mealie. (not even manage data or search).

My resolution was to attach to the DB using SQLiteBrowser, Go to recipes, and change the owner of the floating recipe to my own UUID. once I wrote changes and refreshed the main page, everything worked.

Might suggest a method or catch-all for orphaned recipes since it makes all recipes invisible.
` UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]`

**Comment by anoadragon453** [comment]
I hit this after deleting some users who had created recipes on my mealie instance.

The following `psql` query surfaces the recipes:

```sql
SELECT r.id, r.name, r.user_id
FROM recipes r
LEFT JOIN users u ON u.id = r.user_id
WHERE r.user_id IS NOT NULL
  AND u.id IS NULL;
```

And then to fix them:

```sql
UPDATE recipes r
SET user_id = '<ID of user who should now own these recipes>'
WHERE r.user_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM users u WHERE u.id = r.user_id
  );
```

**Comment by judetf** [comment]
> I hit this after deleting some users who had created recipes on my mealie instance.
> 
> The following `psql` query surfaces the recipes:
> 
> SELECT r.id, r.name, r.user_id
> FROM recipes r
> LEFT JOIN users u ON u.id = r.user_id
> WHERE r.user_id IS NOT NULL
>   AND u.id IS NULL;
> And then to fix them:
> 
> UPDATE recipes r
> SET user_id = '<ID of user who should now own these recipes>'
> WHERE r.user_id IS NOT NULL
>   AND NOT EXISTS (
>     SELECT 1 FROM users u WHERE u.id = r.user_id
>   );

I deleted a user and now have the same issue. Can you possibly provide a bit more explanation of how to do this for someone who is less technical? I understand SQL, but I don't know how to install SQLiteBrowser on my RPi Mealie server nor how to find/attach to the Mealie database in order to execute the above queries. Any guidance would be much appreciated!

-Jude

**Comment by MyriadRising** [comment]
I installed SQLiteBrowser as a docker container and attached the same volumes that mealie was using. I don't understand sql or databases at all personally, I just kept poking at headings until I found it.
