### ISSUE TITLE
[BUG] - Meal Planner 400's when updating an entry

### ISSUE THREAD

**Issue by boc-the-git** [mealie-recipes/mealie#4372]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

The Meal Planner 400's when updating an existing entry, regardless of whether it's a note only or an actual recipe.
Looks to be households related.

### Steps to Reproduce

Works on demo:

1. Go to Meal Planner, edit mode
2. Pick a day, and create a note, call it "test", save
3. Edit that note, changing name to "test 2", save
4. 400

Specifically it's editing that fails.. between step 2 and 3 you can do whatever, leave the page etc.. everything is fine until you edit.

### Please provide relevant logs

```
mealie  | ERROR    2024-10-16T20:44:59 - 1 validation error for ReadPlanEntry
mealie  | household_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | Traceback (most recent call last):
mealie  |   File "/app/mealie/routes/_base/mixins.py", line 95, in update_one
mealie  |     item = self.repo.update(item_id, data)  # type: ignore
mealie  |   File "/app/mealie/repos/repository_generic.py", line 209, in update
mealie  |     return self.schema.model_validate(entry)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/pydantic/main.py", line 596, in model_validate
mealie  |     return cls.__pydantic_validator__.validate_python(
mealie  | pydantic_core._pydantic_core.ValidationError: 1 validation error for ReadPlanEntry
mealie  | household_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | ERROR    2024-10-16T20:44:59 - 1 validation error for ReadPlanEntry
mealie  | household_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | Traceback (most recent call last):
mealie  |   File "/app/mealie/routes/_base/mixins.py", line 95, in update_one
mealie  |     item = self.repo.update(item_id, data)  # type: ignore
mealie  |   File "/app/mealie/repos/repository_generic.py", line 209, in update
mealie  |     return self.schema.model_validate(entry)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/pydantic/main.py", line 596, in model_validate
mealie  |     return cls.__pydantic_validator__.validate_python(
mealie  | pydantic_core._pydantic_core.ValidationError: 1 validation error for ReadPlanEntry
mealie  | household_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | INFO     2024-10-16T20:44:59 - [192.168.2.18:0] 400 Bad Request "PUT /api/households/mealplans/531 HTTP/1.1"
```

### Mealie Version

nightly, [a2beab6cbb433aebcc325a9df04ae6fd5cdbacd3](https://github.com/mealie-recipes/mealie/commit/a2beab6cbb433aebcc325a9df04ae6fd5cdbacd3)

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
@michael-genson progress! Kinda..

Now I'm getting a 422..

```
mealie  | INFO     2024-10-17T19:58:13 - [192.168.2.18:0] 200 OK "GET /api/recipes?search=null&page=1&orderBy=name&orderDirection=asc&perPage=20&_searchSeed=1729155493248 HTTP/1.1"
mealie  | INFO     2024-10-17T19:58:17 - [192.168.2.18:0] 201 Created "POST /api/households/mealplans HTTP/1.1"
mealie  | DEBUG    2024-10-17T19:58:17 - Language set to en
mealie  | INFO     2024-10-17T19:58:17 - [192.168.2.18:0] 200 OK "GET /api/households/mealplans?page=1&perPage=-1&start_date=2024-10-17&end_date=2024-10-28 HTTP/1.1"
mealie  | INFO     2024-10-17T19:58:22 - [192.168.2.18:0] 422 Unprocessable Entity "PUT /api/households/mealplans/533 HTTP/1.1"
mealie  | INFO     2024-10-17T19:58:32 - [192.168.2.18:0] 307 Temporary Redirect "GET /household/mealplan/planner/edit HTTP/1.1"
```

I believe the 201 is when I added the note the first time, then the 200 happened immediately after, then the 422 when trying to change the title of the note.

Obviously this is using the very latest nightly.

**Comment by boc-the-git** [comment]
The payload for the PUT request was:

```
{
  date: "2024-10-25",
  entryType: "dinner",
  existing: true,
  groupId: "703cc83d-ee76-4932-b063-f2cacf0d9886",
  id: 533,
  text: "",
  title: "Test 1 2"
}
```

Still missing the user.. :thinking: 

I logged out and in to see if that'd make any difference; no luck.

**Comment by michael-genson** [comment]
Are you sure your frontend wasn't cached? I can't reproduce

**Comment by boc-the-git** [comment]
You're right, it's working. I didn't do anything additional now other than open my laptop after ~15 hours.
As in, I took no action to deal with the cache, but maybe it expired itself.

Sorry for the false alarm!

![image](https://github.com/user-attachments/assets/ccdeba3b-ac29-457a-99ed-a37fbba85219)
