### ISSUE TITLE
[BUG] - Authentik OIDC not working after update to 2.0.0

### ISSUE THREAD

**Issue by Morksen** [mealie-recipes/mealie#4424]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I've upgraded my mealie instance to 2.0.0 (running on docker behind traefik). 

I'm using Authentik as OIDC IPD. After doing the migration steps regarding OIDC (add client secret, change the type to confidential)  in the documentation, the login does not work. 
The log shows a bad request against Authentik. 

### Steps to Reproduce

1) Do the migration steps mentioned in the documentation regardings OIDC with Authentik

This is my config:

```
environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: false
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.xyz.tld
      # Database Settings
      DB_ENGINE: postgres
      DEFAULT_GROUP: Family
      POSTGRES_USER: xxxxxxxx
      POSTGRES_PASSWORD: xxxxxxx
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
      OIDC_AUTH_ENABLED: true
      OIDC_SIGNUP_ENABLED: true
      OIDC_CONFIGURATION_URL: https://auth.xxx.tld/application/o/mealie/.well-known/openid-configuration
      OIDC_CLIENT_ID: xxx
      OIDC_CLIENT_SECRET: xxxxxxxxxxx
      OIDC_USER_GROUP: Family
      OIDC_ADMIN_GROUP: mealie_admin
      OIDC_PROVIDER_NAME: EselAuth
      OIDC_REMEMBER_ME: true
      OIDC_AUTO_REDIRECT: true
      OIDC_GROUPS_CLAIM: groups
      SMTP_HOST: xxx
      SMTP_PORT: 587
      SMTP_FROM_NAME: Mealie Rezepte
      SMTP_AUTH_STRATEGY: TLS
      SMTP_FROM_EMAIL: xxx
      SMTP_USER: xxx
      SMTP_PASSWORD: xxx
      LOG_LEVEL: DEBUG
```

### Please provide relevant logs

```
mealie    | DEBUG    2024-10-23T09:10:36 - load_ssl_context verify=True cert=None trust_env=True http2=False
mealie    | DEBUG    2024-10-23T09:10:36 - load_verify_locations cafile='/opt/pysetup/.venv/lib/python3.10/site-packages/certifi/cacert.pem'
mealie    | DEBUG    2024-10-23T09:10:36 - Using code_verifier: 'efRTRtOtkw5VFHGf6XiyS2nrlU92QRTDRJzlE6zjVy7hP0Sg'
mealie    | INFO     2024-10-23T09:10:36 - [192.168.2.25:0] 302 Found "GET /api/auth/oauth HTTP/1.1"
mealie    | INFO     2024-10-23T09:10:37 - [192.168.2.25:0] 307 Temporary Redirect "GET /login?code=369a209774cd4eeaa725caaa3d3b0108&state=CUwYr2T2vWpBb85lzYVs3jVqqWhAmY HTTP/1.1"
mealie    | INFO     2024-10-23T09:10:37 - [192.168.2.25:0] 200 OK "GET /login/?code=369a209774cd4eeaa725caaa3d3b0108&state=CUwYr2T2vWpBb85lzYVs3jVqqWhAmY HTTP/1.1"
mealie    | DEBUG    2024-10-23T09:10:37 - load_ssl_context verify=True cert=None trust_env=True http2=False
mealie    | DEBUG    2024-10-23T09:10:37 - load_verify_locations cafile='/opt/pysetup/.venv/lib/python3.10/site-packages/certifi/cacert.pem'
mealie    | DEBUG    2024-10-23T09:10:37 - connect_tcp.started host='auth.xxx.xxx.tld' port=443 local_address=None timeout=5.0 socket_options=None
mealie    | INFO     2024-10-23T09:10:37 - [192.168.2.25:0] 200 OK "GET /api/app/about/startup-info HTTP/1.1"
mealie    | INFO     2024-10-23T09:10:37 - [192.168.2.25:0] 200 OK "GET /api/app/about HTTP/1.1"
mealie    | DEBUG    2024-10-23T09:10:37 - connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x7a7ba15d2320>
mealie    | DEBUG    2024-10-23T09:10:37 - start_tls.started ssl_context=<ssl.SSLContext object at 0x7a7ba01badc0> server_hostname='auth.xxx.xxx.tld' timeout=5.0
mealie    | INFO     2024-10-23T09:10:37 - [192.168.2.25:0] 200 OK "GET /api/app/about HTTP/1.1"
mealie    | DEBUG    2024-10-23T09:10:37 - start_tls.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x7a7ba0b30cd0>
mealie    | DEBUG    2024-10-23T09:10:37 - send_request_headers.started request=<Request [b'POST']>
mealie    | DEBUG    2024-10-23T09:10:37 - send_request_headers.complete
mealie    | DEBUG    2024-10-23T09:10:37 - send_request_body.started request=<Request [b'POST']>
mealie    | DEBUG    2024-10-23T09:10:37 - send_request_body.complete
mealie    | DEBUG    2024-10-23T09:10:37 - receive_response_headers.started request=<Request [b'POST']>
mealie    | DEBUG    2024-10-23T09:10:37 - receive_response_headers.complete return_value=(b'HTTP/1.1', 400, b'Bad Request', [(b'Cache-Control', b'no-store'), (b'Content-Encoding', b'gzip'), (b'Content-Length', b'140'), (b'Content-Type', b'application/json'), (b'Date', b'Wed, 23 Oct 2024 07:10:36 GMT'), (b'Pragma', b'no-cache'), (b'Referrer-Policy', b'same-origin'), (b'Vary', b'Accept-Encoding'), (b'Vary', b'Cookie'), (b'X-Authentik-Id', b'1af0f30e088c4ac08fd975eb578c439d'), (b'X-Content-Type-Options', b'nosniff'), (b'X-Frame-Options', b'DENY'), (b'X-Powered-By', b'authentik')])
mealie    | INFO     2024-10-23T09:10:37 - HTTP Request: POST https://auth.xxx.xxx.tld/application/o/token/ "HTTP/1.1 400 Bad Request"
mealie    | DEBUG    2024-10-23T09:10:37 - receive_response_body.started request=<Request [b'POST']>
mealie    | DEBUG    2024-10-23T09:10:37 - receive_response_body.complete
mealie    | DEBUG    2024-10-23T09:10:37 - response_closed.started
mealie    | DEBUG    2024-10-23T09:10:37 - response_closed.complete
mealie    | DEBUG    2024-10-23T09:10:37 - close.started
mealie    | DEBUG    2024-10-23T09:10:37 - close.complete
mealie    | INFO     2024-10-23T09:10:37 - [192.168.2.25:0] 500 Internal Server Error "GET /api/auth/oauth/callback?code=369a209774cd4eeaa725caaa3d3b0108&state=CUwYr2T2vWpBb85lzYVs3jVqqWhAmY HTTP/1.1"
mealie    | ERROR    2024-10-23T09:10:37 - Exception in ASGI application
mealie    | Traceback (most recent call last):
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
mealie    |     result = await app(  # type: ignore[func-returns-value]
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
mealie    |     return await self.app(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
mealie    |     await super().__call__(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
mealie    |     await self.middleware_stack(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
mealie    |     raise exc
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
mealie    |     await self.app(scope, receive, _send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 85, in __call__
mealie    |     await self.app(scope, receive, send_wrapper)
mealie    | ERROR    2024-10-23T09:10:37 - Exception in ASGI application
mealie    | Traceback (most recent call last):
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
mealie    |     result = await app(  # type: ignore[func-returns-value]
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
mealie    |     return await self.app(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
mealie    |     await super().__call__(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
mealie    |     await self.middleware_stack(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
mealie    |     raise exc
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
mealie    |     await self.app(scope, receive, _send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 85, in __call__
mealie    |     await self.app(scope, receive, send_wrapper)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
mealie    |     await responder(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
mealie    |     await self.app(scope, receive, self.send_with_gzip)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
mealie    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
mealie    |     raise exc
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
mealie    |     await app(scope, receive, sender)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
mealie    |     await self.middleware_stack(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
mealie    |     await route.handle(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
mealie    |     await self.app(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
mealie    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
mealie    |     raise exc
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
mealie    |     await app(scope, receive, sender)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
mealie    |     response = await func(request)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
mealie    |     raw_response = await run_endpoint_function(
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
mealie    |     return await dependant.call(**values)
mealie    |   File "/app/mealie/routes/auth/auth.py", line 120, in oauth_callback
mealie    |     token = await client.authorize_access_token(request)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/authlib/integrations/starlette_client/apps.py", line 81, in authorize_access_token
mealie    |     token = await self.fetch_access_token(**params, **kwargs)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/authlib/integrations/base_client/async_app.py", line 125, in fetch_access_token
mealie    |     token = await client.fetch_token(token_endpoint, **params)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 138, in _fetch_token
mealie    |     return self.parse_response_token(resp)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/authlib/oauth2/client.py", line 355, in parse_response_token
mealie    |     raise self.oauth_error_class(
mealie    | authlib.integrations.base_client.errors.OAuthError: invalid_client: Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
mealie    |     await responder(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
mealie    |     await self.app(scope, receive, self.send_with_gzip)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
mealie    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
mealie    |     raise exc
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
mealie    |     await app(scope, receive, sender)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
mealie    |     await self.middleware_stack(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
mealie    |     await route.handle(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
mealie    |     await self.app(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
mealie    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
mealie    |     raise exc
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
mealie    |     await app(scope, receive, sender)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
mealie    |     response = await func(request)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
mealie    |     raw_response = await run_endpoint_function(
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
mealie    |     return await dependant.call(**values)
mealie    |   File "/app/mealie/routes/auth/auth.py", line 120, in oauth_callback
mealie    |     token = await client.authorize_access_token(request)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/authlib/integrations/starlette_client/apps.py", line 81, in authorize_access_token
mealie    |     token = await self.fetch_access_token(**params, **kwargs)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/authlib/integrations/base_client/async_app.py", line 125, in fetch_access_token
mealie    |     token = await client.fetch_token(token_endpoint, **params)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 138, in _fetch_token
mealie    |     return self.parse_response_token(resp)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/authlib/oauth2/client.py", line 355, in parse_response_token
mealie    |     raise self.oauth_error_class(
mealie    | authlib.integrations.base_client.errors.OAuthError: invalid_client: Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)
mealie    | INFO     2024-10-23T09:10:39 - [192.168.2.25:0] 304 Not Modified "GET /sw.js HTTP/1.1"
```

### Mealie Version

ghcr.io/mealie-recipes/mealie:latest

### Deployment

Docker (Linux)

**Comment by Meimax** [comment]
I've got the same problem, a (hopefully temporary) fix is setting your redirect url in authentik to `http://mealie.xyz.tld` instead of `https://mealie.xyz.tld` (without https). 

With `https://mealie.xyz.tld` as the redirect url i get a wrong redirect url message, with `http(s)://mealie.xyz.tld` i get the same error as you get and with `http://mealie.xyz.tld` it works for me.

**Comment by boc-the-git** [comment]
Are you both using Traefik, is that a common denominator? @Meimax

**Comment by Meimax** [comment]
No I'm using NGINX with the following config:

```
server {
    include includes/listen-https;
    include includes/listen-http3;

    server_name mealie.xyz.tld;

    ssl_certificate /mnt/services/legoCertificates/ssl/certificates/xyz.tld.crt;
    ssl_certificate_key /mnt/services/legoCertificates/ssl/certificates/xyz.tld.key;

    location / {
        proxy_pass http://srnm:9925/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 90;
    }
}
```

**Comment by PhoenixofForce** [comment]
I got a similar issue. And im using caddy and authentik.
Setting the redirect uri to http does not resolve the issue. For me its both on http and https

```
mealie    | INFO     2024-10-23T06:51:27 - [192.168.178.24:0] 500 Internal Server Error "GET /api/auth/oauth/callback?code=2e3d952a1cae4359912e5df642074b12&state=3tLAQGs8VJKXWPOnxLy8SF66AUZUeW HTTP/1.1"
mealie    | ERROR    2024-10-23T06:51:27 - Exception in ASGI application
mealie    | Traceback (most recent call last):
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
mealie    |     result = await app(  # type: ignore[func-returns-value]
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
mealie    |     return await self.app(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
mealie    |     await super().__call__(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
mealie    |     await self.middleware_stack(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
mealie    |     raise exc
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
mealie    |     await self.app(scope, receive, _send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 85, in __call__
mealie    |     await self.app(scope, receive, send_wrapper)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
mealie    |     await responder(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
mealie    |     await self.app(scope, receive, self.send_with_gzip)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
mealie    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
mealie    |     raise exc
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
mealie    |     await app(scope, receive, sender)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
mealie    |     await self.middleware_stack(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
mealie    |     await route.handle(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
mealie    |     await self.app(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
mealie    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
mealie    |     raise exc
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
mealie    |     await app(scope, receive, sender)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
mealie    |     response = await func(request)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
mealie    |     raw_response = await run_endpoint_function(
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
mealie    |     return await dependant.call(**values)
mealie    |   File "/app/mealie/routes/auth/auth.py", line 120, in oauth_callback
mealie    |     token = await client.authorize_access_token(request)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/authlib/integrations/starlette_client/apps.py", line 84, in authorize_access_token
mealie    |     userinfo = await self.parse_id_token(token, nonce=state_data['nonce'], claims_options=claims_options)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/authlib/integrations/base_client/async_openid.py", line 78, in parse_id_token
mealie    |     claims.validate(leeway=120)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/authlib/oidc/core/claims.py", line 35, in validate
mealie    |     self.validate_iss()
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/authlib/jose/rfc7519/claims.py", line 117, in validate_iss
mealie    |     self._validate_claim_value('iss')
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/authlib/jose/rfc7519/claims.py", line 74, in _validate_claim_value
mealie    |     raise InvalidClaimError(claim_name)
mealie    | authlib.jose.errors.InvalidClaimError: invalid_claim: Invalid claim "iss"
mealie    | ERROR    2024-10-23T06:51:27 - Exception in ASGI application
mealie    | Traceback (most recent call last):
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
mealie    |     result = await app(  # type: ignore[func-returns-value]
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
mealie    |     return await self.app(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
mealie    |     await super().__call__(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
mealie    |     await self.middleware_stack(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
mealie    |     raise exc
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
mealie    |     await self.app(scope, receive, _send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 85, in __call__
mealie    |     await self.app(scope, receive, send_wrapper)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
mealie    |     await responder(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
mealie    |     await self.app(scope, receive, self.send_with_gzip)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
mealie    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
mealie    |     raise exc
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
mealie    |     await app(scope, receive, sender)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
mealie    |     await self.middleware_stack(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
mealie    |     await route.handle(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
mealie    |     await self.app(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
mealie    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
mealie    |     raise exc
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
mealie    |     await app(scope, receive, sender)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
mealie    |     response = await func(request)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
mealie    |     raw_response = await run_endpoint_function(
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
mealie    |     return await dependant.call(**values)
mealie    |   File "/app/mealie/routes/auth/auth.py", line 120, in oauth_callback
mealie    |     token = await client.authorize_access_token(request)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/authlib/integrations/starlette_client/apps.py", line 84, in authorize_access_token
mealie    |     userinfo = await self.parse_id_token(token, nonce=state_data['nonce'], claims_options=claims_options)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/authlib/integrations/base_client/async_openid.py", line 78, in parse_id_token
mealie    |     claims.validate(leeway=120)
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/authlib/oidc/core/claims.py", line 35, in validate
mealie    |     self.validate_iss()
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/authlib/jose/rfc7519/claims.py", line 117, in validate_iss
mealie    |     self._validate_claim_value('iss')
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/authlib/jose/rfc7519/claims.py", line 74, in _validate_claim_value
mealie    |     raise InvalidClaimError(claim_name)
mealie    | authlib.jose.errors.InvalidClaimError: invalid_claim: Invalid claim "iss"
```

**Comment by cmintey** [comment]
@Morksen are there any logs or issues that you can see in Authentik? Authentik is returning a 400 Bad Request with the folllowing message: `invalid_client: Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)`

**Comment by cmintey** [comment]
@PhoenixofForce Your error message is different, `invalid_claim: Invalid claim "iss"`. That means that the token was issued with something other than what was expected. The `iss` should match the `issuer` field on the `.well-known/openid-configuration` endpoint

Edit: Actually I think it just verifies the existence of the claim

**Comment by Morksen** [comment]
Ok, I've updated Authentik and just copy and pasted the client id and secret again into the mealie config. Now it works. I guess, the secret was pasted not correctly last time. Maybe a whitespace at the end or something like that.
