### ISSUE TITLE
[BUG] - How to Migrate v1 Users & Recipes into v2 Households in Same Group

### ISSUE THREAD

**Issue by tdharris** [mealie-recipes/mealie#4427]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

This may not be a bug precisely, but wasn't sure how else to file this, so my apologies, but please consider the following scenario, as I suspect I'm not the only one wondering about this.

With the introduction of [Households](https://docs.mealie.io/documentation/getting-started/features/#groups-and-households) in Mealie v2, I'm having trouble finding a way to migrate my existing users & recipes into this new preferred Household approach within the same group. The goal being so that we can more easily share recipes between households. My upgrade to v2 appears to have gone fine, but I'm having trouble adopting the following.

To better illustrate this, is it possible to migrate existing users/recipes into the new household approach within a single group? How can I achieve the following and retain recipes (see `DESIRED` state on bottom).

![image](https://github.com/user-attachments/assets/0e81d315-2aef-4f8f-9964-f88bcc86c209)

Here are some observations, which I'm sure have been all for good reasons in a v2 context, but appear to be limiting factors for me in wanting to jump into the preferred v2 approach outlined above:

- I'm unable to move users to a different group (the input field is locked). I understand this makes sense from a v2 security perspective with the intent of each group being a separate mealie instance, but now I'm unsure how I can have a single group with those existing users and recipes.
- I think all user recipes are primarily associated to the group, so even if I could move a user to a new group, their recipes would not come with. Is that correct?

Any recommendations for an approach to migrate Mealie v1 users into the same group, but under separate households and preserve their recipes? I can't seem to find a way to do this, but certainly, I can't be the only one wondering how to do this. Almost seems like we just have to start totally over, which can't be the case, so I must be missing something. Any help would be most appreciated, thank you!

### Steps to Reproduce

1) Within a Mealie v1 instance:
    - Create Group A with User A
    - Create Group B with User B
    - User A create recipe(s)
    - User B create recipe(s)
2) Upgrade to Mealie v2. Try to consolidate existing structure into the new household approach under a single group and retain existing users/recipes.

### Please provide relevant logs

N/A.

### Mealie Version

Docker Image
b5e65f1389f6 - v2.0.0
Version
v2.0.0
Build
a7c8b33cca37882f687a0528f93631545de74f1d

### Deployment

Docker (Linux)

### Additional Deployment Details

- Users auth method are all configured with OIDC.

**Comment by michael-genson** [comment]
Currently there isn't an easy way to do this. Groups have always effectively been isolated instances (even in V1) and have some fundamental incompatibilities. For instance, since each group has its own tags, categories, foods, units, etc. there's no simple way to combine recipes from different groups. It's basically the equivalent of asking "how do I combine multiple instances of Mealie into one?"

This request makes sense in context of V2, but unfortunately since your data is already set up with multiple groups it's not going to be an easy task to consolidate.

> I'm unable to move users to a different group (the input field is locked)

This used to be enabled, but since groups are fundamentally incompatible with each other it led to a ton of bugs/edge-cases (e.g. recipes would not be moved with the user and are effectively orphaned with no owner) so we had to disable it.

---

So then, what to do about it? There's no easy one-size-fits-all solution. My recommendation would be to get all recipes/users into one group, and then use the data management tool to divvy everything up according to household (you can bulk assign owners in the recipe data management page).

The easiest way to get all recipes into one group is using the bulk URL import. Mealie can scrape itself/other instances, though you will lose any parsing you did. If you want to preserve your foods/units/categories/etc. you will have to figure out a way to map those programmatically and import them via the API, but it's not something Mealie is able to do by itself.

**Comment by tdharris** [comment]
Yah this makes a lot of sense. Thanks for your quick response!

Ok, so a theoretical approach to explore could be:

1. Export ALL recipes from each of the current groups. One zip file per group that we can use to bulk zip import.
2. Create the new primary target group or repurpose an existing group.
3. Import the recipes for one of the groups. Make sure things look right and they likely won't have an owner assigned or could sort by `Date Added`, which will make it easy to pick out in the recipe data management page and re-assign..
    - I noticed even importing recipes from another group fails since the `id` of the recipe is the same in the db despite being part of different groups:
        ```sql
        UNIQUE constraint failed: recipes.id
        ```
    - So it seems like I'll need to purge the existing recipe data from the old group to proceed with the import, which feels slightly scary.. Then I suspect the import would be successful.
5. With the recipes in the new group, but not yet assigned, I could delete the old user/group, re-create as a new user and assign to their new household in my primary group.
6. Then from the recipe data management page, add the `Owner` column and bulk `Change Owner` for the hopefully obviously unassigned recipes (or sort by `Date Added`) and update them to their rightful owner.
7. Repeat for each group/user..

Seem like a good approach? Any suggestions or warnings? Thanks for your help!

**Comment by michael-genson** [comment]
Yup, that sounds like it should work! One note is that recipe data (images, assets) is tied to a folder labeled by the recipe id, so you definitely want to maintain the same id (group/household doesn't matter). Your approach should conserve ids, so that should work.

And definitely grab a backup or two before doing anything; take a backup from the app, _and_ take one from disk (while our backups are pretty good, nothing beats backing up the actual database + data).

Lastly, if logging-in as your other users is an option, whoever does the bulk import becomes the owner, so theoretically you could log in as each new owner and do their imports. You could always set a dummy password for import, then change it later.

**Comment by tdharris** [comment]
Ok cool, so I've created a `test` group/household/user and imported a single recipe to attempt the above move approach. I export the recipe as a zip, delete the user, household, but then deleting the group fails: `An unexpected error occurred` .. I suspect this is because there are recipes within the group maybe? Here is the error in the log:

```shell
ERROR    2024-10-25T13:47:29 - (sqlite3.IntegrityError) NOT NULL constraint failed: recipes.group_id
[SQL: UPDATE recipes SET group_id=?, update_at=? WHERE recipes.id = ?]
[parameters: (None, '2024-10-25 19:47:29.926651', '2e860e956dce4a21b7fcb069d0c316ef')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: recipes.group_id
```

<details>
<summary>Show Full Error</summary>

```shell
ERROR    2024-10-25T13:47:29 - (sqlite3.IntegrityError) NOT NULL constraint failed: recipes.group_id
[SQL: UPDATE recipes SET group_id=?, update_at=? WHERE recipes.id = ?]
[parameters: (None, '2024-10-25 19:47:29.926651', '2e860e956dce4a21b7fcb069d0c316ef')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: recipes.group_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/mealie/routes/_base/mixins.py", line 120, in delete_one
    item = self.repo.delete(item_id)
  File "/app/mealie/repos/repository_generic.py", line 250, in delete
    raise e
  File "/app/mealie/repos/repository_generic.py", line 247, in delete
    self.session.commit()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
ERROR    2024-10-25T13:47:29 - (sqlite3.IntegrityError) NOT NULL constraint failed: recipes.group_id
[SQL: UPDATE recipes SET group_id=?, update_at=? WHERE recipes.id = ?]
[parameters: (None, '2024-10-25 19:47:29.926651', '2e860e956dce4a21b7fcb069d0c316ef')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: recipes.group_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/mealie/routes/_base/mixins.py", line 120, in delete_one
    item = self.repo.delete(item_id)
  File "/app/mealie/repos/repository_generic.py", line 250, in delete
    raise e
  File "/app/mealie/repos/repository_generic.py", line 247, in delete
    self.session.commit()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self._flush(objects)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    self.session.flush()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    return connection._execute_clauseelement(
    _emit_update_statements(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
    ret = self._execute_context(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return self._exec_single_context(
    return connection._execute_clauseelement(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: recipes.group_id
[SQL: UPDATE recipes SET group_id=?, update_at=? WHERE recipes.id = ?]
[parameters: (None, '2024-10-25 19:47:29.926651', '2e860e956dce4a21b7fcb069d0c316ef')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: recipes.group_id
[SQL: UPDATE recipes SET group_id=?, update_at=? WHERE recipes.id = ?]
[parameters: (None, '2024-10-25 19:47:29.926651', '2e860e956dce4a21b7fcb069d0c316ef')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
INFO     2024-10-25T13:47:29 - [192.168.1.1:0] 400 Bad Request "DELETE /api/admin/groups/65f283e8-2283-4281-ad60-a33b02887433 HTTP/1.1"
INFO     2024-10-25T13:47:29 - [192.168.1.1:0] 200 OK "GET /api/admin/groups?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1"
```
</details>

- So then perhaps I should delete the recipes as the owner first, then delete the user, household, then hopefully group delete will work.
- I've recreated a `test` user and assigned them back to this group, but there are no recipes, none displayed in data management page either. So somehow these steps appear to have orphaned the recipe within this group? I'm not able to see any recipes in that group, but I also can't delete the group.. Perhaps the above error gives more insight. 🤔 

UPDATE; I've restored the db, so I'm back to normal.. Though now I'm curious about the `mealie.db` and some `sqlite3` statements to just re-assign recipes from old group to a new group 🤔

**Comment by michael-genson** [comment]
Yeah I would recommend deleting things in this order:
1. recipes
2. users
3. households
4. groups

That _should_ work

**Comment by tdharris** [comment]
Yup that order works! Bulk delete the group recipes from the data management page first. Recreate the user in the new group/household, login and then bulk create recipes from zip and all good. 

I also validated a sqlite approach that seems pretty straightforward. Would you mind if I share that or prefer that I don't share here? I'm good either way, I know manual db statements aren't an ideal for most, but taking backups all the ways will help to restore should anything go wrong.

**Comment by michael-genson** [comment]
For sure! No harm in sharing it! It could definitely help someone else out if they run into a similar scenario

**Comment by tdharris** [comment]
Ok cool, this approach also has worked for me:

1. **Take Backups**. There is risk of corrupting the db, so making a full backup in Mealie UI, stopping mealie and making a directory backup are all good ideas. Don't skip this.

2. Move recipes from one group to another:
	- Identify both the current and target group id:
		```sql
		select * from groups;
		```
	- Confirm the recipes:
		```sql
		select * from recipes where group_id='<CURRENT_GROUP_ID>';
		```
	- Move recipes to other group:
		```sql
		UPDATE recipes
		SET group_id='<TARGET_GROUP_ID>'
		WHERE group_id='<CURRENT_GROUP_ID>';
		```

	**Note**: User will now no longer see ANY of their recipes as long as they are a member of the old group.

3. Move user to the new target group:

	- Identify the target group id:
		```sql
		select * from groups;
		```
	- Identify the target household id:
		```sql
		select id, name from households where group_id='<TARGET_GROUP_ID>';
		```
	- Identify the user id to move:
		```sql
		select id, username, email from users where username='<TARGET_USERNAME>';
		```
	- Move the user to the new group and household:
		```sql
		UPDATE users
		SET group_id = '<TARGET_GROUP_ID>',
		    household_id = '<TARGET_HOUSEHOLD_ID>'
		WHERE id = '<USER_ID>';
		```

4. Consolidate Categories and Recipe Tags into the new target group (if needed):

	- Categories:

		```sql
		UPDATE categories
		SET group_id = '<TARGET_GROUP_ID>'
		WHERE id = '<CURRENT_GROUP_ID>';
		```

	- Recipe Tags:

		```sql
		UPDATE tags
		SET group_id = '<TARGET_GROUP_ID>'
		WHERE id = '<CURRENT_GROUP_ID>';
		```

	**Note**: I was ok to skip on other resource types like cookbooks, tools, ingredients, units, etc. Can at least `seed` the food and units from data management in the new group.

5. Start Mealie, Login as the user and verify everything looks ok. Since the recipes are owned by the same user id, everything _should_ look great: they are now a member of the new group and household with all their recipes still available.

	**Note**: If any of the above was done incorrectly, the db may be corrupt and data may not load correctly in UI. If so, restore db as needed.

**Comment by tdharris** [comment]
Thanks for the guidance @michael-genson. I finished consolidating all the recipes/groups into a new one and moved users into their own households within that group. Everything is looking great! I went with the above sql approach for the actual migration.
